// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuctionDataForPrivate = `-- name: GetAuctionDataForPrivate :many
SELECT
    COALESCE(auction_packages.id, 0)::bigint                  AS package_id,
    COALESCE(auction_packages.name, '')::text                 AS package_name,
    COALESCE(auction_items.id, 0)::bigint                     AS item_id,
    COALESCE(auction_items.name, '')::text                    AS item_name,
    COALESCE(auction_items.description, '')::text             AS item_description,
    COALESCE(auction_items.unit, '')::text                    AS item_unit,
    COALESCE(auction_items.quantity, 0)::float8               AS item_quantity,
    COALESCE(auction_items.note, '')::text                    AS item_note,
    COALESCE(auction_participant_prices.comments, '')::text   AS participant_comment,
    COALESCE(users.id, 0)::bigint                             AS participant_user_id,
    COALESCE(auction_participant_prices.unit_price, '0')::text AS participant_price,
    COALESCE(workers.job_title_in_project, '')::text          AS participant_title
FROM auction_items
FULL JOIN auction_packages ON auction_packages.id = auction_items.auction_package_id
FULL JOIN auctions ON auctions.id = auction_packages.auction_id
LEFT JOIN auction_participant_prices ON auction_participant_prices.auction_item_id = auction_items.id
LEFT JOIN users ON users.id = auction_participant_prices.user_id
LEFT JOIN workers ON workers.id = users.worker_id
WHERE auctions.id = $1
ORDER BY auction_packages.id
`

type GetAuctionDataForPrivateRow struct {
	PackageID          int64   `json:"package_id"`
	PackageName        string  `json:"package_name"`
	ItemID             int64   `json:"item_id"`
	ItemName           string  `json:"item_name"`
	ItemDescription    string  `json:"item_description"`
	ItemUnit           string  `json:"item_unit"`
	ItemQuantity       float64 `json:"item_quantity"`
	ItemNote           string  `json:"item_note"`
	ParticipantComment string  `json:"participant_comment"`
	ParticipantUserID  int64   `json:"participant_user_id"`
	ParticipantPrice   string  `json:"participant_price"`
	ParticipantTitle   string  `json:"participant_title"`
}

func (q *Queries) GetAuctionDataForPrivate(ctx context.Context, id int64) ([]GetAuctionDataForPrivateRow, error) {
	rows, err := q.db.Query(ctx, getAuctionDataForPrivate, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuctionDataForPrivateRow{}
	for rows.Next() {
		var i GetAuctionDataForPrivateRow
		if err := rows.Scan(
			&i.PackageID,
			&i.PackageName,
			&i.ItemID,
			&i.ItemName,
			&i.ItemDescription,
			&i.ItemUnit,
			&i.ItemQuantity,
			&i.ItemNote,
			&i.ParticipantComment,
			&i.ParticipantUserID,
			&i.ParticipantPrice,
			&i.ParticipantTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuctionDataForPublic = `-- name: GetAuctionDataForPublic :many
SELECT
    COALESCE(auction_packages.id, 0)::bigint                  AS package_id,
    COALESCE(auction_packages.name, '')::text                 AS package_name,
    COALESCE(auction_items.name, '')::text                    AS item_name,
    COALESCE(auction_items.description, '')::text             AS item_description,
    COALESCE(auction_items.unit, '')::text                    AS item_unit,
    COALESCE(auction_items.quantity, 0)::float8               AS item_quantity,
    COALESCE(auction_items.note, '')::text                    AS item_note,
    COALESCE(auction_participant_prices.unit_price, '0')::text AS participant_price,
    COALESCE(workers.job_title_in_project, '')::text          AS participant_title
FROM auction_items
FULL JOIN auction_packages ON auction_packages.id = auction_items.auction_package_id
FULL JOIN auctions ON auctions.id = auction_packages.auction_id
LEFT JOIN auction_participant_prices ON auction_participant_prices.auction_item_id = auction_items.id
LEFT JOIN users ON users.id = auction_participant_prices.user_id
LEFT JOIN workers ON workers.id = users.worker_id
WHERE auctions.id = $1
ORDER BY auction_packages.id, auction_items.id, auction_participant_prices.user_id
`

type GetAuctionDataForPublicRow struct {
	PackageID        int64   `json:"package_id"`
	PackageName      string  `json:"package_name"`
	ItemName         string  `json:"item_name"`
	ItemDescription  string  `json:"item_description"`
	ItemUnit         string  `json:"item_unit"`
	ItemQuantity     float64 `json:"item_quantity"`
	ItemNote         string  `json:"item_note"`
	ParticipantPrice string  `json:"participant_price"`
	ParticipantTitle string  `json:"participant_title"`
}

func (q *Queries) GetAuctionDataForPublic(ctx context.Context, id int64) ([]GetAuctionDataForPublicRow, error) {
	rows, err := q.db.Query(ctx, getAuctionDataForPublic, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuctionDataForPublicRow{}
	for rows.Next() {
		var i GetAuctionDataForPublicRow
		if err := rows.Scan(
			&i.PackageID,
			&i.PackageName,
			&i.ItemName,
			&i.ItemDescription,
			&i.ItemUnit,
			&i.ItemQuantity,
			&i.ItemNote,
			&i.ParticipantPrice,
			&i.ParticipantTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAuctionParticipantPrice = `-- name: UpsertAuctionParticipantPrice :exec
INSERT INTO auction_participant_prices (auction_item_id, user_id, unit_price, comments)
VALUES ($1, $2, $3, $4)
ON CONFLICT (auction_item_id, user_id)
DO UPDATE SET unit_price = EXCLUDED.unit_price, comments = EXCLUDED.comments
`

type UpsertAuctionParticipantPriceParams struct {
	AuctionItemID pgtype.Int8 `json:"auction_item_id"`
	UserID        pgtype.Int8 `json:"user_id"`
	UnitPrice     pgtype.Text `json:"unit_price"`
	Comments      pgtype.Text `json:"comments"`
}

// Migration 00002 added a unique index on (auction_item_id, user_id),
// so the lookup-then-update-or-insert dance collapses into a single
// atomic upsert that's safe under concurrent writes.
func (q *Queries) UpsertAuctionParticipantPrice(ctx context.Context, arg UpsertAuctionParticipantPriceParams) error {
	_, err := q.db.Exec(ctx, upsertAuctionParticipantPrice,
		arg.AuctionItemID,
		arg.UserID,
		arg.UnitPrice,
		arg.Comments,
	)
	return err
}
