// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEffectivePermissionsForUser = `-- name: ListEffectivePermissionsForUser :many
SELECT
    ur.project_id,
    rg.resource_type_code,
    rg.action_code
FROM user_roles ur
INNER JOIN role_grants rg ON rg.role_id = ur.role_id
WHERE ur.user_id = $1
`

type ListEffectivePermissionsForUserRow struct {
	ProjectID        pgtype.Int8 `json:"project_id"`
	ResourceTypeCode string      `json:"resource_type_code"`
	ActionCode       string      `json:"action_code"`
}

// Permissions v2 resolver query. Returns one row per (project_id, resource,
// action) the user is granted via any role assignment. project_id IS NULL
// means a global grant; non-null project_id is a per-project grant. The
// resolver merges these against the request's project_id.
func (q *Queries) ListEffectivePermissionsForUser(ctx context.Context, userID int64) ([]ListEffectivePermissionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listEffectivePermissionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectivePermissionsForUserRow{}
	for rows.Next() {
		var i ListEffectivePermissionsForUserRow
		if err := rows.Scan(&i.ProjectID, &i.ResourceTypeCode, &i.ActionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
