// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateInvoiceMaterialsBatch implements pgx.CopyFromSource.
type iteratorForCreateInvoiceMaterialsBatch struct {
	rows                 []CreateInvoiceMaterialsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateInvoiceMaterialsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateInvoiceMaterialsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProjectID,
		r.rows[0].MaterialCostID,
		r.rows[0].InvoiceID,
		r.rows[0].InvoiceType,
		r.rows[0].IsDefected,
		r.rows[0].Amount,
		r.rows[0].Notes,
	}, nil
}

func (r iteratorForCreateInvoiceMaterialsBatch) Err() error {
	return nil
}

func (q *Queries) CreateInvoiceMaterialsBatch(ctx context.Context, arg []CreateInvoiceMaterialsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"invoice_materials"}, []string{"project_id", "material_cost_id", "invoice_id", "invoice_type", "is_defected", "amount", "notes"}, &iteratorForCreateInvoiceMaterialsBatch{rows: arg})
}

// iteratorForCreateInvoiceOperationsBatch implements pgx.CopyFromSource.
type iteratorForCreateInvoiceOperationsBatch struct {
	rows                 []CreateInvoiceOperationsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateInvoiceOperationsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateInvoiceOperationsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProjectID,
		r.rows[0].OperationID,
		r.rows[0].InvoiceID,
		r.rows[0].InvoiceType,
		r.rows[0].Amount,
		r.rows[0].Notes,
	}, nil
}

func (r iteratorForCreateInvoiceOperationsBatch) Err() error {
	return nil
}

func (q *Queries) CreateInvoiceOperationsBatch(ctx context.Context, arg []CreateInvoiceOperationsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"invoice_operations"}, []string{"project_id", "operation_id", "invoice_id", "invoice_type", "amount", "notes"}, &iteratorForCreateInvoiceOperationsBatch{rows: arg})
}

// iteratorForCreateMaterialCostsBatch implements pgx.CopyFromSource.
type iteratorForCreateMaterialCostsBatch struct {
	rows                 []CreateMaterialCostsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateMaterialCostsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateMaterialCostsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MaterialID,
		r.rows[0].CostPrime,
		r.rows[0].CostM19,
		r.rows[0].CostWithCustomer,
	}, nil
}

func (r iteratorForCreateMaterialCostsBatch) Err() error {
	return nil
}

func (q *Queries) CreateMaterialCostsBatch(ctx context.Context, arg []CreateMaterialCostsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"material_costs"}, []string{"material_id", "cost_prime", "cost_m19", "cost_with_customer"}, &iteratorForCreateMaterialCostsBatch{rows: arg})
}

// iteratorForCreateMaterialsBatch implements pgx.CopyFromSource.
type iteratorForCreateMaterialsBatch struct {
	rows                 []CreateMaterialsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateMaterialsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateMaterialsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Category,
		r.rows[0].Code,
		r.rows[0].Name,
		r.rows[0].Unit,
		r.rows[0].Notes,
		r.rows[0].HasSerialNumber,
		r.rows[0].Article,
		r.rows[0].ProjectID,
		r.rows[0].PlannedAmountForProject,
		r.rows[0].ShowPlannedAmountInReport,
	}, nil
}

func (r iteratorForCreateMaterialsBatch) Err() error {
	return nil
}

func (q *Queries) CreateMaterialsBatch(ctx context.Context, arg []CreateMaterialsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"materials"}, []string{"category", "code", "name", "unit", "notes", "has_serial_number", "article", "project_id", "planned_amount_for_project", "show_planned_amount_in_report"}, &iteratorForCreateMaterialsBatch{rows: arg})
}

// iteratorForCreateObjectSupervisorsBatch implements pgx.CopyFromSource.
type iteratorForCreateObjectSupervisorsBatch struct {
	rows                 []CreateObjectSupervisorsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateObjectSupervisorsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateObjectSupervisorsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SupervisorWorkerID,
		r.rows[0].ObjectID,
	}, nil
}

func (r iteratorForCreateObjectSupervisorsBatch) Err() error {
	return nil
}

func (q *Queries) CreateObjectSupervisorsBatch(ctx context.Context, arg []CreateObjectSupervisorsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"object_supervisors"}, []string{"supervisor_worker_id", "object_id"}, &iteratorForCreateObjectSupervisorsBatch{rows: arg})
}

// iteratorForCreateObjectTeamsBatch implements pgx.CopyFromSource.
type iteratorForCreateObjectTeamsBatch struct {
	rows                 []CreateObjectTeamsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateObjectTeamsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateObjectTeamsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ObjectID,
		r.rows[0].TeamID,
	}, nil
}

func (r iteratorForCreateObjectTeamsBatch) Err() error {
	return nil
}

func (q *Queries) CreateObjectTeamsBatch(ctx context.Context, arg []CreateObjectTeamsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"object_teams"}, []string{"object_id", "team_id"}, &iteratorForCreateObjectTeamsBatch{rows: arg})
}

// iteratorForCreatePermissionsBatch implements pgx.CopyFromSource.
type iteratorForCreatePermissionsBatch struct {
	rows                 []CreatePermissionsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePermissionsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePermissionsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RoleID,
		r.rows[0].ResourceID,
		r.rows[0].R,
		r.rows[0].W,
		r.rows[0].U,
		r.rows[0].D,
	}, nil
}

func (r iteratorForCreatePermissionsBatch) Err() error {
	return nil
}

func (q *Queries) CreatePermissionsBatch(ctx context.Context, arg []CreatePermissionsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"permissions"}, []string{"role_id", "resource_id", "r", "w", "u", "d"}, &iteratorForCreatePermissionsBatch{rows: arg})
}

// iteratorForCreateSerialNumberLocationsBatch implements pgx.CopyFromSource.
type iteratorForCreateSerialNumberLocationsBatch struct {
	rows                 []CreateSerialNumberLocationsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSerialNumberLocationsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSerialNumberLocationsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SerialNumberID,
		r.rows[0].ProjectID,
		r.rows[0].LocationID,
		r.rows[0].LocationType,
	}, nil
}

func (r iteratorForCreateSerialNumberLocationsBatch) Err() error {
	return nil
}

func (q *Queries) CreateSerialNumberLocationsBatch(ctx context.Context, arg []CreateSerialNumberLocationsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"serial_number_locations"}, []string{"serial_number_id", "project_id", "location_id", "location_type"}, &iteratorForCreateSerialNumberLocationsBatch{rows: arg})
}

// iteratorForCreateSerialNumberMovementsBatch implements pgx.CopyFromSource.
type iteratorForCreateSerialNumberMovementsBatch struct {
	rows                 []CreateSerialNumberMovementsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSerialNumberMovementsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSerialNumberMovementsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SerialNumberID,
		r.rows[0].ProjectID,
		r.rows[0].InvoiceID,
		r.rows[0].InvoiceType,
		r.rows[0].IsDefected,
		r.rows[0].Confirmation,
	}, nil
}

func (r iteratorForCreateSerialNumberMovementsBatch) Err() error {
	return nil
}

func (q *Queries) CreateSerialNumberMovementsBatch(ctx context.Context, arg []CreateSerialNumberMovementsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"serial_number_movements"}, []string{"serial_number_id", "project_id", "invoice_id", "invoice_type", "is_defected", "confirmation"}, &iteratorForCreateSerialNumberMovementsBatch{rows: arg})
}

// iteratorForCreateTPNourashesObjectsBatch implements pgx.CopyFromSource.
type iteratorForCreateTPNourashesObjectsBatch struct {
	rows                 []CreateTPNourashesObjectsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTPNourashesObjectsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTPNourashesObjectsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TpObjectID,
		r.rows[0].TargetID,
		r.rows[0].TargetType,
	}, nil
}

func (r iteratorForCreateTPNourashesObjectsBatch) Err() error {
	return nil
}

func (q *Queries) CreateTPNourashesObjectsBatch(ctx context.Context, arg []CreateTPNourashesObjectsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tp_nourashes_objects"}, []string{"tp_object_id", "target_id", "target_type"}, &iteratorForCreateTPNourashesObjectsBatch{rows: arg})
}

// iteratorForCreateTeamLeadersBatch implements pgx.CopyFromSource.
type iteratorForCreateTeamLeadersBatch struct {
	rows                 []CreateTeamLeadersBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTeamLeadersBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTeamLeadersBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TeamID,
		r.rows[0].LeaderWorkerID,
	}, nil
}

func (r iteratorForCreateTeamLeadersBatch) Err() error {
	return nil
}

func (q *Queries) CreateTeamLeadersBatch(ctx context.Context, arg []CreateTeamLeadersBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"team_leaders"}, []string{"team_id", "leader_worker_id"}, &iteratorForCreateTeamLeadersBatch{rows: arg})
}

// iteratorForCreateUserInProjectsBatch implements pgx.CopyFromSource.
type iteratorForCreateUserInProjectsBatch struct {
	rows                 []CreateUserInProjectsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateUserInProjectsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateUserInProjectsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].ProjectID,
	}, nil
}

func (r iteratorForCreateUserInProjectsBatch) Err() error {
	return nil
}

func (q *Queries) CreateUserInProjectsBatch(ctx context.Context, arg []CreateUserInProjectsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_in_projects"}, []string{"user_id", "project_id"}, &iteratorForCreateUserInProjectsBatch{rows: arg})
}

// iteratorForCreateWorkerAttendancesBatch implements pgx.CopyFromSource.
type iteratorForCreateWorkerAttendancesBatch struct {
	rows                 []CreateWorkerAttendancesBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateWorkerAttendancesBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateWorkerAttendancesBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProjectID,
		r.rows[0].WorkerID,
		r.rows[0].Start,
		r.rows[0].End,
	}, nil
}

func (r iteratorForCreateWorkerAttendancesBatch) Err() error {
	return nil
}

func (q *Queries) CreateWorkerAttendancesBatch(ctx context.Context, arg []CreateWorkerAttendancesBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"worker_attendances"}, []string{"project_id", "worker_id", "start", "end"}, &iteratorForCreateWorkerAttendancesBatch{rows: arg})
}

// iteratorForCreateWorkersBatch implements pgx.CopyFromSource.
type iteratorForCreateWorkersBatch struct {
	rows                 []CreateWorkersBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateWorkersBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateWorkersBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProjectID,
		r.rows[0].Name,
		r.rows[0].CompanyWorkerID,
		r.rows[0].JobTitleInCompany,
		r.rows[0].JobTitleInProject,
		r.rows[0].MobileNumber,
	}, nil
}

func (r iteratorForCreateWorkersBatch) Err() error {
	return nil
}

func (q *Queries) CreateWorkersBatch(ctx context.Context, arg []CreateWorkersBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"workers"}, []string{"project_id", "name", "company_worker_id", "job_title_in_company", "job_title_in_project", "mobile_number"}, &iteratorForCreateWorkersBatch{rows: arg})
}
