// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: district.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDistricts = `-- name: CountDistricts :one
SELECT COUNT(*) FROM districts WHERE project_id = $1
`

func (q *Queries) CountDistricts(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countDistricts, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDistrict = `-- name: CreateDistrict :one
INSERT INTO districts (name, project_id)
VALUES ($1, $2)
RETURNING id, name, project_id
`

type CreateDistrictParams struct {
	Name      pgtype.Text `json:"name"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) CreateDistrict(ctx context.Context, arg CreateDistrictParams) (District, error) {
	row := q.db.QueryRow(ctx, createDistrict, arg.Name, arg.ProjectID)
	var i District
	err := row.Scan(&i.ID, &i.Name, &i.ProjectID)
	return i, err
}

const deleteDistrict = `-- name: DeleteDistrict :exec
DELETE FROM districts WHERE id = $1
`

func (q *Queries) DeleteDistrict(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDistrict, id)
	return err
}

const getDistrict = `-- name: GetDistrict :one
SELECT id, name, project_id
FROM districts
WHERE id = $1
`

func (q *Queries) GetDistrict(ctx context.Context, id int64) (District, error) {
	row := q.db.QueryRow(ctx, getDistrict, id)
	var i District
	err := row.Scan(&i.ID, &i.Name, &i.ProjectID)
	return i, err
}

const getDistrictByName = `-- name: GetDistrictByName :one
SELECT id, name, project_id
FROM districts
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetDistrictByName(ctx context.Context, name pgtype.Text) (District, error) {
	row := q.db.QueryRow(ctx, getDistrictByName, name)
	var i District
	err := row.Scan(&i.ID, &i.Name, &i.ProjectID)
	return i, err
}

const listDistricts = `-- name: ListDistricts :many
SELECT id, name, project_id
FROM districts
WHERE project_id = $1
ORDER BY id DESC
`

func (q *Queries) ListDistricts(ctx context.Context, projectID pgtype.Int8) ([]District, error) {
	rows, err := q.db.Query(ctx, listDistricts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []District{}
	for rows.Next() {
		var i District
		if err := rows.Scan(&i.ID, &i.Name, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictsPaginated = `-- name: ListDistrictsPaginated :many
SELECT id, name, project_id
FROM districts
WHERE project_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListDistrictsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListDistrictsPaginated(ctx context.Context, arg ListDistrictsPaginatedParams) ([]District, error) {
	rows, err := q.db.Query(ctx, listDistrictsPaginated, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []District{}
	for rows.Next() {
		var i District
		if err := rows.Scan(&i.ID, &i.Name, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDistrict = `-- name: UpdateDistrict :one
UPDATE districts
SET name = $2, project_id = $3
WHERE id = $1
RETURNING id, name, project_id
`

type UpdateDistrictParams struct {
	ID        int64       `json:"id"`
	Name      pgtype.Text `json:"name"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) UpdateDistrict(ctx context.Context, arg UpdateDistrictParams) (District, error) {
	row := q.db.QueryRow(ctx, updateDistrict, arg.ID, arg.Name, arg.ProjectID)
	var i District
	err := row.Scan(&i.ID, &i.Name, &i.ProjectID)
	return i, err
}
