// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_output.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmInvoiceOutput = `-- name: ConfirmInvoiceOutput :exec
UPDATE invoice_outputs
SET confirmation = true
WHERE id = $1
`

func (q *Queries) ConfirmInvoiceOutput(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, confirmInvoiceOutput, id)
	return err
}

const confirmSerialNumberLocationsByOutputInvoice = `-- name: ConfirmSerialNumberLocationsByOutputInvoice :exec
UPDATE serial_number_locations
SET location_type = 'team', location_id = $1::bigint
WHERE serial_number_locations.serial_number_id IN (
    SELECT serial_number_movements.serial_number_id
    FROM serial_number_movements
    WHERE
        serial_number_movements.invoice_type = 'output'
        AND serial_number_movements.invoice_id = $2::bigint
)
`

type ConfirmSerialNumberLocationsByOutputInvoiceParams struct {
	TeamID    int64 `json:"team_id"`
	InvoiceID int64 `json:"invoice_id"`
}

// After invoice_output confirmation, serial_number_locations rows for the
// invoice's serial numbers are flipped from warehouse to team.
func (q *Queries) ConfirmSerialNumberLocationsByOutputInvoice(ctx context.Context, arg ConfirmSerialNumberLocationsByOutputInvoiceParams) error {
	_, err := q.db.Exec(ctx, confirmSerialNumberLocationsByOutputInvoice, arg.TeamID, arg.InvoiceID)
	return err
}

const countInvoiceOutputsByProject = `-- name: CountInvoiceOutputsByProject :one
SELECT COUNT(*)::bigint FROM invoice_outputs WHERE project_id = $1
`

func (q *Queries) CountInvoiceOutputsByProject(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceOutputsByProject, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvoiceOutput = `-- name: CreateInvoiceOutput :one
INSERT INTO invoice_outputs (
    district_id, project_id, warehouse_manager_worker_id, released_worker_id,
    recipient_worker_id, team_id, delivery_code, date_of_invoice, notes, confirmation
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, district_id, project_id, warehouse_manager_worker_id, released_worker_id,
          recipient_worker_id, team_id, delivery_code, date_of_invoice, notes, confirmation
`

type CreateInvoiceOutputParams struct {
	DistrictID               pgtype.Int8        `json:"district_id"`
	ProjectID                pgtype.Int8        `json:"project_id"`
	WarehouseManagerWorkerID pgtype.Int8        `json:"warehouse_manager_worker_id"`
	ReleasedWorkerID         pgtype.Int8        `json:"released_worker_id"`
	RecipientWorkerID        pgtype.Int8        `json:"recipient_worker_id"`
	TeamID                   pgtype.Int8        `json:"team_id"`
	DeliveryCode             pgtype.Text        `json:"delivery_code"`
	DateOfInvoice            pgtype.Timestamptz `json:"date_of_invoice"`
	Notes                    pgtype.Text        `json:"notes"`
	Confirmation             pgtype.Bool        `json:"confirmation"`
}

func (q *Queries) CreateInvoiceOutput(ctx context.Context, arg CreateInvoiceOutputParams) (InvoiceOutput, error) {
	row := q.db.QueryRow(ctx, createInvoiceOutput,
		arg.DistrictID,
		arg.ProjectID,
		arg.WarehouseManagerWorkerID,
		arg.ReleasedWorkerID,
		arg.RecipientWorkerID,
		arg.TeamID,
		arg.DeliveryCode,
		arg.DateOfInvoice,
		arg.Notes,
		arg.Confirmation,
	)
	var i InvoiceOutput
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.ProjectID,
		&i.WarehouseManagerWorkerID,
		&i.ReleasedWorkerID,
		&i.RecipientWorkerID,
		&i.TeamID,
		&i.DeliveryCode,
		&i.DateOfInvoice,
		&i.Notes,
		&i.Confirmation,
	)
	return i, err
}

const deleteInvoiceOutput = `-- name: DeleteInvoiceOutput :exec
DELETE FROM invoice_outputs WHERE id = $1
`

func (q *Queries) DeleteInvoiceOutput(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceOutput, id)
	return err
}

const getInvoiceOutput = `-- name: GetInvoiceOutput :one
SELECT id, district_id, project_id, warehouse_manager_worker_id, released_worker_id,
       recipient_worker_id, team_id, delivery_code, date_of_invoice, notes, confirmation
FROM invoice_outputs
WHERE id = $1
`

func (q *Queries) GetInvoiceOutput(ctx context.Context, id int64) (InvoiceOutput, error) {
	row := q.db.QueryRow(ctx, getInvoiceOutput, id)
	var i InvoiceOutput
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.ProjectID,
		&i.WarehouseManagerWorkerID,
		&i.ReleasedWorkerID,
		&i.RecipientWorkerID,
		&i.TeamID,
		&i.DeliveryCode,
		&i.DateOfInvoice,
		&i.Notes,
		&i.Confirmation,
	)
	return i, err
}

const getInvoiceOutputByDeliveryCode = `-- name: GetInvoiceOutputByDeliveryCode :one
SELECT id, district_id, project_id, warehouse_manager_worker_id, released_worker_id,
       recipient_worker_id, team_id, delivery_code, date_of_invoice, notes, confirmation
FROM invoice_outputs
WHERE delivery_code = $1
LIMIT 1
`

func (q *Queries) GetInvoiceOutputByDeliveryCode(ctx context.Context, deliveryCode pgtype.Text) (InvoiceOutput, error) {
	row := q.db.QueryRow(ctx, getInvoiceOutputByDeliveryCode, deliveryCode)
	var i InvoiceOutput
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.ProjectID,
		&i.WarehouseManagerWorkerID,
		&i.ReleasedWorkerID,
		&i.RecipientWorkerID,
		&i.TeamID,
		&i.DeliveryCode,
		&i.DateOfInvoice,
		&i.Notes,
		&i.Confirmation,
	)
	return i, err
}

const getInvoiceOutputDataForExcel = `-- name: GetInvoiceOutputDataForExcel :one
SELECT
    invoice_outputs.id                                  AS id,
    COALESCE(projects.name, '')::text                   AS project_name,
    COALESCE(invoice_outputs.delivery_code, '')::text   AS delivery_code,
    COALESCE(districts.name, '')::text                  AS district_name,
    COALESCE(team_leader.name, '')::text                AS team_leader_name,
    COALESCE(warehouse_manager.name, '')::text          AS warehouse_manager_name,
    COALESCE(released.name, '')::text                   AS released_name,
    COALESCE(recipient.name, '')::text                  AS recipient_name,
    invoice_outputs.date_of_invoice                     AS date_of_invoice
FROM invoice_outputs
INNER JOIN projects ON projects.id = invoice_outputs.project_id
INNER JOIN districts ON districts.id = invoice_outputs.district_id
INNER JOIN teams ON teams.id = invoice_outputs.team_id
INNER JOIN team_leaders ON team_leaders.team_id = teams.id
INNER JOIN workers AS team_leader ON team_leader.id = team_leaders.leader_worker_id
INNER JOIN workers AS warehouse_manager ON warehouse_manager.id = invoice_outputs.warehouse_manager_worker_id
INNER JOIN workers AS released ON released.id = invoice_outputs.released_worker_id
INNER JOIN workers AS recipient ON recipient.id = invoice_outputs.recipient_worker_id
WHERE invoice_outputs.id = $1
ORDER BY team_leaders.id DESC
LIMIT 1
`

type GetInvoiceOutputDataForExcelRow struct {
	ID                   int64              `json:"id"`
	ProjectName          string             `json:"project_name"`
	DeliveryCode         string             `json:"delivery_code"`
	DistrictName         string             `json:"district_name"`
	TeamLeaderName       string             `json:"team_leader_name"`
	WarehouseManagerName string             `json:"warehouse_manager_name"`
	ReleasedName         string             `json:"released_name"`
	RecipientName        string             `json:"recipient_name"`
	DateOfInvoice        pgtype.Timestamptz `json:"date_of_invoice"`
}

func (q *Queries) GetInvoiceOutputDataForExcel(ctx context.Context, id int64) (GetInvoiceOutputDataForExcelRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceOutputDataForExcel, id)
	var i GetInvoiceOutputDataForExcelRow
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.DeliveryCode,
		&i.DistrictName,
		&i.TeamLeaderName,
		&i.WarehouseManagerName,
		&i.ReleasedName,
		&i.RecipientName,
		&i.DateOfInvoice,
	)
	return i, err
}

const getTotalAmountInWarehouse = `-- name: GetTotalAmountInWarehouse :one
SELECT COALESCE(SUM(material_locations.amount), 0)::numeric AS total_amount
FROM materials
INNER JOIN material_costs ON material_costs.material_id = materials.id
INNER JOIN material_locations ON material_locations.material_cost_id = material_costs.id
WHERE
    material_locations.project_id = $1
    AND material_locations.location_type = 'warehouse'
    AND materials.id = $2
`

type GetTotalAmountInWarehouseParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) GetTotalAmountInWarehouse(ctx context.Context, arg GetTotalAmountInWarehouseParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalAmountInWarehouse, arg.ProjectID, arg.ID)
	var total_amount pgtype.Numeric
	err := row.Scan(&total_amount)
	return total_amount, err
}

const listInvoiceOutputAvailableMaterialsInWarehouse = `-- name: ListInvoiceOutputAvailableMaterialsInWarehouse :many
SELECT
    materials.id                                                  AS id,
    COALESCE(materials.name, '')::text                            AS name,
    COALESCE(materials.unit, '')::text                            AS unit,
    COALESCE(materials.has_serial_number, false)::boolean         AS has_serial_number,
    COALESCE(material_locations.amount, 0)::numeric               AS amount
FROM material_locations
INNER JOIN material_costs ON material_costs.id = material_locations.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    material_locations.project_id = $1
    AND material_locations.location_type = 'warehouse'
    AND material_locations.amount > 0
ORDER BY materials.name
`

type ListInvoiceOutputAvailableMaterialsInWarehouseRow struct {
	ID              int64          `json:"id"`
	Name            string         `json:"name"`
	Unit            string         `json:"unit"`
	HasSerialNumber bool           `json:"has_serial_number"`
	Amount          pgtype.Numeric `json:"amount"`
}

func (q *Queries) ListInvoiceOutputAvailableMaterialsInWarehouse(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputAvailableMaterialsInWarehouseRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputAvailableMaterialsInWarehouse, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputAvailableMaterialsInWarehouseRow{}
	for rows.Next() {
		var i ListInvoiceOutputAvailableMaterialsInWarehouseRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.HasSerialNumber,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputMaterialDataForReport = `-- name: ListInvoiceOutputMaterialDataForReport :many
SELECT
    materials.id                                        AS material_id,
    COALESCE(materials.name, '')::text                  AS material_name,
    COALESCE(materials.unit, '')::text                  AS material_unit,
    COALESCE(material_costs.cost_m19, 0)::numeric       AS material_cost_m19,
    COALESCE(invoice_materials.notes, '')::text         AS notes,
    COALESCE(invoice_materials.amount, 0)::numeric      AS amount
FROM invoice_materials
INNER JOIN material_costs ON material_costs.id = invoice_materials.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    invoice_materials.invoice_type = 'output'
    AND invoice_materials.invoice_id = $1
`

type ListInvoiceOutputMaterialDataForReportRow struct {
	MaterialID      int64          `json:"material_id"`
	MaterialName    string         `json:"material_name"`
	MaterialUnit    string         `json:"material_unit"`
	MaterialCostM19 pgtype.Numeric `json:"material_cost_m19"`
	Notes           string         `json:"notes"`
	Amount          pgtype.Numeric `json:"amount"`
}

func (q *Queries) ListInvoiceOutputMaterialDataForReport(ctx context.Context, invoiceID pgtype.Int8) ([]ListInvoiceOutputMaterialDataForReportRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputMaterialDataForReport, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputMaterialDataForReportRow{}
	for rows.Next() {
		var i ListInvoiceOutputMaterialDataForReportRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialName,
			&i.MaterialUnit,
			&i.MaterialCostM19,
			&i.Notes,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputMaterialsForEdit = `-- name: ListInvoiceOutputMaterialsForEdit :many
SELECT
    materials.id                                                  AS material_id,
    COALESCE(materials.name, '')::text                            AS material_name,
    COALESCE(materials.unit, '')::text                            AS material_unit,
    COALESCE(material_locations.amount, 0)::numeric               AS warehouse_amount,
    COALESCE(invoice_materials.amount, 0)::numeric                AS amount,
    COALESCE(invoice_materials.notes, '')::text                   AS notes,
    COALESCE(materials.has_serial_number, false)::boolean         AS has_serial_number
FROM invoice_materials
INNER JOIN material_costs ON material_costs.id = invoice_materials.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
INNER JOIN material_locations ON material_locations.material_cost_id = invoice_materials.material_cost_id
WHERE
    material_locations.location_type = 'warehouse'
    AND invoice_materials.invoice_type = 'output'
    AND invoice_materials.invoice_id = $1
`

type ListInvoiceOutputMaterialsForEditRow struct {
	MaterialID      int64          `json:"material_id"`
	MaterialName    string         `json:"material_name"`
	MaterialUnit    string         `json:"material_unit"`
	WarehouseAmount pgtype.Numeric `json:"warehouse_amount"`
	Amount          pgtype.Numeric `json:"amount"`
	Notes           string         `json:"notes"`
	HasSerialNumber bool           `json:"has_serial_number"`
}

func (q *Queries) ListInvoiceOutputMaterialsForEdit(ctx context.Context, invoiceID pgtype.Int8) ([]ListInvoiceOutputMaterialsForEditRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputMaterialsForEdit, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputMaterialsForEditRow{}
	for rows.Next() {
		var i ListInvoiceOutputMaterialsForEditRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialName,
			&i.MaterialUnit,
			&i.WarehouseAmount,
			&i.Amount,
			&i.Notes,
			&i.HasSerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputReportFilterData = `-- name: ListInvoiceOutputReportFilterData :many
SELECT
    invoice_outputs.id                                  AS id,
    COALESCE(invoice_outputs.delivery_code, '')::text   AS delivery_code,
    COALESCE(warehouse_manager.name, '')::text          AS warehouse_manager_name,
    COALESCE(recipient_worker.name, '')::text           AS recipient_name,
    COALESCE(teams.number, '')::text                    AS team_number,
    COALESCE(leader_worker.name, '')::text              AS team_leader_name,
    invoice_outputs.date_of_invoice                     AS date_of_invoice
FROM invoice_outputs
INNER JOIN workers AS warehouse_manager ON warehouse_manager.id = invoice_outputs.warehouse_manager_worker_id
INNER JOIN workers AS recipient_worker ON recipient_worker.id = invoice_outputs.recipient_worker_id
INNER JOIN teams ON teams.id = invoice_outputs.team_id
INNER JOIN team_leaders ON teams.id = team_leaders.team_id
INNER JOIN workers AS leader_worker ON leader_worker.id = team_leaders.leader_worker_id
WHERE
    invoice_outputs.project_id = $1
    AND COALESCE(invoice_outputs.confirmation, false) = true
    AND (NULLIF($2::text, '') IS NULL OR invoice_outputs.delivery_code = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR invoice_outputs.recipient_worker_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR invoice_outputs.warehouse_manager_worker_id = $4)
    AND (NULLIF($5::bigint, 0) IS NULL OR invoice_outputs.team_id = $5)
    AND (NULLIF($6::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR $6 <= invoice_outputs.date_of_invoice)
    AND (NULLIF($7::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR invoice_outputs.date_of_invoice <= $7)
ORDER BY invoice_outputs.id DESC
`

type ListInvoiceOutputReportFilterDataParams struct {
	ProjectID pgtype.Int8        `json:"project_id"`
	Column2   string             `json:"column_2"`
	Column3   int64              `json:"column_3"`
	Column4   int64              `json:"column_4"`
	Column5   int64              `json:"column_5"`
	Column6   pgtype.Timestamptz `json:"column_6"`
	Column7   pgtype.Timestamptz `json:"column_7"`
}

type ListInvoiceOutputReportFilterDataRow struct {
	ID                   int64              `json:"id"`
	DeliveryCode         string             `json:"delivery_code"`
	WarehouseManagerName string             `json:"warehouse_manager_name"`
	RecipientName        string             `json:"recipient_name"`
	TeamNumber           string             `json:"team_number"`
	TeamLeaderName       string             `json:"team_leader_name"`
	DateOfInvoice        pgtype.Timestamptz `json:"date_of_invoice"`
}

func (q *Queries) ListInvoiceOutputReportFilterData(ctx context.Context, arg ListInvoiceOutputReportFilterDataParams) ([]ListInvoiceOutputReportFilterDataRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputReportFilterData,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputReportFilterDataRow{}
	for rows.Next() {
		var i ListInvoiceOutputReportFilterDataRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryCode,
			&i.WarehouseManagerName,
			&i.RecipientName,
			&i.TeamNumber,
			&i.TeamLeaderName,
			&i.DateOfInvoice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputUniqueCodes = `-- name: ListInvoiceOutputUniqueCodes :many
SELECT
    COALESCE(delivery_code, '')::text AS label,
    COALESCE(delivery_code, '')::text AS value
FROM invoice_outputs
WHERE project_id = $1
ORDER BY id DESC
`

type ListInvoiceOutputUniqueCodesRow struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

func (q *Queries) ListInvoiceOutputUniqueCodes(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueCodesRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputUniqueCodes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputUniqueCodesRow{}
	for rows.Next() {
		var i ListInvoiceOutputUniqueCodesRow
		if err := rows.Scan(&i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputUniqueDistricts = `-- name: ListInvoiceOutputUniqueDistricts :many
SELECT
    districts.id                       AS value,
    COALESCE(districts.name, '')::text AS label
FROM districts
WHERE districts.project_id = $1
`

type ListInvoiceOutputUniqueDistrictsRow struct {
	Value int64  `json:"value"`
	Label string `json:"label"`
}

func (q *Queries) ListInvoiceOutputUniqueDistricts(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueDistrictsRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputUniqueDistricts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputUniqueDistrictsRow{}
	for rows.Next() {
		var i ListInvoiceOutputUniqueDistrictsRow
		if err := rows.Scan(&i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputUniqueRecieved = `-- name: ListInvoiceOutputUniqueRecieved :many
SELECT
    workers.id                       AS value,
    COALESCE(workers.name, '')::text AS label
FROM workers
WHERE workers.id IN (
    SELECT DISTINCT(invoice_outputs.recipient_worker_id)
    FROM invoice_outputs
    WHERE invoice_outputs.project_id = $1 AND invoice_outputs.recipient_worker_id IS NOT NULL
)
`

type ListInvoiceOutputUniqueRecievedRow struct {
	Value int64  `json:"value"`
	Label string `json:"label"`
}

func (q *Queries) ListInvoiceOutputUniqueRecieved(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueRecievedRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputUniqueRecieved, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputUniqueRecievedRow{}
	for rows.Next() {
		var i ListInvoiceOutputUniqueRecievedRow
		if err := rows.Scan(&i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputUniqueTeams = `-- name: ListInvoiceOutputUniqueTeams :many
SELECT
    teams.id                                                                                  AS value,
    (COALESCE(teams.number, '') || ' (' || COALESCE(workers.name, '') || ')')::text           AS label
FROM teams
INNER JOIN team_leaders ON team_leaders.team_id = teams.id
INNER JOIN workers ON workers.id = team_leaders.leader_worker_id
WHERE teams.id IN (
    SELECT DISTINCT(invoice_outputs.team_id)
    FROM invoice_outputs
    WHERE invoice_outputs.project_id = $1 AND invoice_outputs.team_id IS NOT NULL
)
`

type ListInvoiceOutputUniqueTeamsRow struct {
	Value int64  `json:"value"`
	Label string `json:"label"`
}

func (q *Queries) ListInvoiceOutputUniqueTeams(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueTeamsRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputUniqueTeams, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputUniqueTeamsRow{}
	for rows.Next() {
		var i ListInvoiceOutputUniqueTeamsRow
		if err := rows.Scan(&i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputUniqueWarehouseManagers = `-- name: ListInvoiceOutputUniqueWarehouseManagers :many
SELECT
    workers.id                       AS value,
    COALESCE(workers.name, '')::text AS label
FROM workers
WHERE workers.id IN (
    SELECT DISTINCT(invoice_outputs.warehouse_manager_worker_id)
    FROM invoice_outputs
    WHERE invoice_outputs.project_id = $1 AND invoice_outputs.warehouse_manager_worker_id IS NOT NULL
)
`

type ListInvoiceOutputUniqueWarehouseManagersRow struct {
	Value int64  `json:"value"`
	Label string `json:"label"`
}

func (q *Queries) ListInvoiceOutputUniqueWarehouseManagers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueWarehouseManagersRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputUniqueWarehouseManagers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputUniqueWarehouseManagersRow{}
	for rows.Next() {
		var i ListInvoiceOutputUniqueWarehouseManagersRow
		if err := rows.Scan(&i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputs = `-- name: ListInvoiceOutputs :many
SELECT id, district_id, project_id, warehouse_manager_worker_id, released_worker_id,
       recipient_worker_id, team_id, delivery_code, date_of_invoice, notes, confirmation
FROM invoice_outputs
ORDER BY id DESC
`

func (q *Queries) ListInvoiceOutputs(ctx context.Context) ([]InvoiceOutput, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceOutput{}
	for rows.Next() {
		var i InvoiceOutput
		if err := rows.Scan(
			&i.ID,
			&i.DistrictID,
			&i.ProjectID,
			&i.WarehouseManagerWorkerID,
			&i.ReleasedWorkerID,
			&i.RecipientWorkerID,
			&i.TeamID,
			&i.DeliveryCode,
			&i.DateOfInvoice,
			&i.Notes,
			&i.Confirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputsPaginated = `-- name: ListInvoiceOutputsPaginated :many
SELECT id, district_id, project_id, warehouse_manager_worker_id, released_worker_id,
       recipient_worker_id, team_id, delivery_code, date_of_invoice, notes, confirmation
FROM invoice_outputs
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListInvoiceOutputsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInvoiceOutputsPaginated(ctx context.Context, arg ListInvoiceOutputsPaginatedParams) ([]InvoiceOutput, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceOutput{}
	for rows.Next() {
		var i InvoiceOutput
		if err := rows.Scan(
			&i.ID,
			&i.DistrictID,
			&i.ProjectID,
			&i.WarehouseManagerWorkerID,
			&i.ReleasedWorkerID,
			&i.RecipientWorkerID,
			&i.TeamID,
			&i.DeliveryCode,
			&i.DateOfInvoice,
			&i.Notes,
			&i.Confirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputsPaginatedFiltered = `-- name: ListInvoiceOutputsPaginatedFiltered :many
SELECT
    invoice_outputs.id                                  AS id,
    COALESCE(invoice_outputs.delivery_code, '')::text   AS delivery_code,
    COALESCE(districts.name, '')::text                  AS district_name,
    districts.id                                        AS district_id,
    COALESCE(teams.number, '')::text                    AS team_name,
    teams.id                                            AS team_id,
    warehouse_manager.id                                AS warehouse_manager_id,
    COALESCE(warehouse_manager.name, '')::text          AS warehouse_manager_name,
    COALESCE(released.name, '')::text                   AS released_name,
    recipient.id                                        AS recipient_id,
    COALESCE(recipient.name, '')::text                  AS recipient_name,
    invoice_outputs.date_of_invoice                     AS date_of_invoice,
    COALESCE(invoice_outputs.confirmation, false)::boolean AS confirmation,
    COALESCE(invoice_outputs.notes, '')::text           AS notes
FROM invoice_outputs
INNER JOIN districts ON districts.id = invoice_outputs.district_id
INNER JOIN teams ON teams.id = invoice_outputs.team_id
INNER JOIN workers AS warehouse_manager ON warehouse_manager.id = invoice_outputs.warehouse_manager_worker_id
INNER JOIN workers AS released ON released.id = invoice_outputs.released_worker_id
INNER JOIN workers AS recipient ON recipient.id = invoice_outputs.recipient_worker_id
WHERE
    invoice_outputs.project_id = $1
    AND (NULLIF($2::bigint, 0) IS NULL OR invoice_outputs.district_id = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR invoice_outputs.warehouse_manager_worker_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR invoice_outputs.released_worker_id = $4)
    AND (NULLIF($5::bigint, 0) IS NULL OR invoice_outputs.recipient_worker_id = $5)
    AND (NULLIF($6::bigint, 0) IS NULL OR invoice_outputs.team_id = $6)
    AND (NULLIF($7::text, '') IS NULL OR invoice_outputs.delivery_code = $7)
ORDER BY invoice_outputs.id DESC
LIMIT $8 OFFSET $9
`

type ListInvoiceOutputsPaginatedFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   int64       `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Column5   int64       `json:"column_5"`
	Column6   int64       `json:"column_6"`
	Column7   string      `json:"column_7"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListInvoiceOutputsPaginatedFilteredRow struct {
	ID                   int64              `json:"id"`
	DeliveryCode         string             `json:"delivery_code"`
	DistrictName         string             `json:"district_name"`
	DistrictID           int64              `json:"district_id"`
	TeamName             string             `json:"team_name"`
	TeamID               int64              `json:"team_id"`
	WarehouseManagerID   int64              `json:"warehouse_manager_id"`
	WarehouseManagerName string             `json:"warehouse_manager_name"`
	ReleasedName         string             `json:"released_name"`
	RecipientID          int64              `json:"recipient_id"`
	RecipientName        string             `json:"recipient_name"`
	DateOfInvoice        pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmation         bool               `json:"confirmation"`
	Notes                string             `json:"notes"`
}

func (q *Queries) ListInvoiceOutputsPaginatedFiltered(ctx context.Context, arg ListInvoiceOutputsPaginatedFilteredParams) ([]ListInvoiceOutputsPaginatedFilteredRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputsPaginatedFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputsPaginatedFilteredRow{}
	for rows.Next() {
		var i ListInvoiceOutputsPaginatedFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryCode,
			&i.DistrictName,
			&i.DistrictID,
			&i.TeamName,
			&i.TeamID,
			&i.WarehouseManagerID,
			&i.WarehouseManagerName,
			&i.ReleasedName,
			&i.RecipientID,
			&i.RecipientName,
			&i.DateOfInvoice,
			&i.Confirmation,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialAmountSortedByCostM19InLocation = `-- name: ListMaterialAmountSortedByCostM19InLocation :many
SELECT
    materials.id                                            AS material_id,
    material_costs.id                                       AS material_cost_id,
    COALESCE(material_costs.cost_m19, 0)::numeric           AS material_cost_m19,
    COALESCE(material_locations.amount, 0)::numeric         AS material_amount
FROM material_locations
INNER JOIN material_costs ON material_costs.id = material_locations.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    material_locations.project_id = $1
    AND material_locations.location_type = $2
    AND material_locations.location_id = $3
    AND materials.id = $4
    AND material_locations.amount > 0
ORDER BY material_costs.cost_m19 DESC
`

type ListMaterialAmountSortedByCostM19InLocationParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	LocationType pgtype.Text `json:"location_type"`
	LocationID   pgtype.Int8 `json:"location_id"`
	ID           int64       `json:"id"`
}

type ListMaterialAmountSortedByCostM19InLocationRow struct {
	MaterialID      int64          `json:"material_id"`
	MaterialCostID  int64          `json:"material_cost_id"`
	MaterialCostM19 pgtype.Numeric `json:"material_cost_m19"`
	MaterialAmount  pgtype.Numeric `json:"material_amount"`
}

func (q *Queries) ListMaterialAmountSortedByCostM19InLocation(ctx context.Context, arg ListMaterialAmountSortedByCostM19InLocationParams) ([]ListMaterialAmountSortedByCostM19InLocationRow, error) {
	rows, err := q.db.Query(ctx, listMaterialAmountSortedByCostM19InLocation,
		arg.ProjectID,
		arg.LocationType,
		arg.LocationID,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialAmountSortedByCostM19InLocationRow{}
	for rows.Next() {
		var i ListMaterialAmountSortedByCostM19InLocationRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialCostID,
			&i.MaterialCostM19,
			&i.MaterialAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialCostIDAndSerialNumberIDByCodes = `-- name: ListMaterialCostIDAndSerialNumberIDByCodes :many
SELECT
    material_costs.id                                       AS material_cost_id,
    serial_numbers.id                                       AS serial_number_id,
    serial_number_locations.id                              AS serial_number_location_id
FROM serial_numbers
INNER JOIN material_costs ON material_costs.id = serial_numbers.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
INNER JOIN serial_number_locations ON serial_number_locations.serial_number_id = serial_numbers.id
WHERE
    materials.id = $1
    AND serial_number_locations.location_type = $2
    AND serial_number_locations.location_id = $3
    AND serial_numbers.code = ANY($4::text[])
ORDER BY material_costs.id
`

type ListMaterialCostIDAndSerialNumberIDByCodesParams struct {
	ID           int64       `json:"id"`
	LocationType pgtype.Text `json:"location_type"`
	LocationID   pgtype.Int8 `json:"location_id"`
	Codes        []string    `json:"codes"`
}

type ListMaterialCostIDAndSerialNumberIDByCodesRow struct {
	MaterialCostID         int64 `json:"material_cost_id"`
	SerialNumberID         int64 `json:"serial_number_id"`
	SerialNumberLocationID int64 `json:"serial_number_location_id"`
}

func (q *Queries) ListMaterialCostIDAndSerialNumberIDByCodes(ctx context.Context, arg ListMaterialCostIDAndSerialNumberIDByCodesParams) ([]ListMaterialCostIDAndSerialNumberIDByCodesRow, error) {
	rows, err := q.db.Query(ctx, listMaterialCostIDAndSerialNumberIDByCodes,
		arg.ID,
		arg.LocationType,
		arg.LocationID,
		arg.Codes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialCostIDAndSerialNumberIDByCodesRow{}
	for rows.Next() {
		var i ListMaterialCostIDAndSerialNumberIDByCodesRow
		if err := rows.Scan(&i.MaterialCostID, &i.SerialNumberID, &i.SerialNumberLocationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSerialNumberCodesByMaterialID = `-- name: ListSerialNumberCodesByMaterialID :many
SELECT COALESCE(serial_numbers.code, '')::text AS code
FROM materials
INNER JOIN material_costs ON material_costs.material_id = materials.id
INNER JOIN serial_numbers ON material_costs.id = serial_numbers.material_cost_id
INNER JOIN serial_number_locations ON serial_number_locations.serial_number_id = serial_numbers.id
WHERE
    materials.project_id = serial_numbers.project_id
    AND materials.project_id = serial_number_locations.project_id
    AND materials.project_id = $1
    AND materials.id = $2
    AND serial_number_locations.location_type = $3
    AND serial_number_locations.location_id = 0
`

type ListSerialNumberCodesByMaterialIDParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	ID           int64       `json:"id"`
	LocationType pgtype.Text `json:"location_type"`
}

func (q *Queries) ListSerialNumberCodesByMaterialID(ctx context.Context, arg ListSerialNumberCodesByMaterialIDParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSerialNumberCodesByMaterialID, arg.ProjectID, arg.ID, arg.LocationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceOutput = `-- name: UpdateInvoiceOutput :one
UPDATE invoice_outputs
SET district_id = $2, project_id = $3, warehouse_manager_worker_id = $4,
    released_worker_id = $5, recipient_worker_id = $6, team_id = $7,
    delivery_code = $8, date_of_invoice = $9, notes = $10, confirmation = $11
WHERE id = $1
RETURNING id, district_id, project_id, warehouse_manager_worker_id, released_worker_id,
          recipient_worker_id, team_id, delivery_code, date_of_invoice, notes, confirmation
`

type UpdateInvoiceOutputParams struct {
	ID                       int64              `json:"id"`
	DistrictID               pgtype.Int8        `json:"district_id"`
	ProjectID                pgtype.Int8        `json:"project_id"`
	WarehouseManagerWorkerID pgtype.Int8        `json:"warehouse_manager_worker_id"`
	ReleasedWorkerID         pgtype.Int8        `json:"released_worker_id"`
	RecipientWorkerID        pgtype.Int8        `json:"recipient_worker_id"`
	TeamID                   pgtype.Int8        `json:"team_id"`
	DeliveryCode             pgtype.Text        `json:"delivery_code"`
	DateOfInvoice            pgtype.Timestamptz `json:"date_of_invoice"`
	Notes                    pgtype.Text        `json:"notes"`
	Confirmation             pgtype.Bool        `json:"confirmation"`
}

func (q *Queries) UpdateInvoiceOutput(ctx context.Context, arg UpdateInvoiceOutputParams) (InvoiceOutput, error) {
	row := q.db.QueryRow(ctx, updateInvoiceOutput,
		arg.ID,
		arg.DistrictID,
		arg.ProjectID,
		arg.WarehouseManagerWorkerID,
		arg.ReleasedWorkerID,
		arg.RecipientWorkerID,
		arg.TeamID,
		arg.DeliveryCode,
		arg.DateOfInvoice,
		arg.Notes,
		arg.Confirmation,
	)
	var i InvoiceOutput
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.ProjectID,
		&i.WarehouseManagerWorkerID,
		&i.ReleasedWorkerID,
		&i.RecipientWorkerID,
		&i.TeamID,
		&i.DeliveryCode,
		&i.DateOfInvoice,
		&i.Notes,
		&i.Confirmation,
	)
	return i, err
}
