// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_input.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmInvoiceInput = `-- name: ConfirmInvoiceInput :exec
UPDATE invoice_inputs
SET confirmed = true
WHERE id = $1
`

func (q *Queries) ConfirmInvoiceInput(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, confirmInvoiceInput, id)
	return err
}

const countInvoiceInputsByMaterials = `-- name: CountInvoiceInputsByMaterials :one
SELECT COUNT(*)::bigint
FROM invoice_inputs
INNER JOIN workers AS warehouse_manager ON warehouse_manager.id = invoice_inputs.warehouse_manager_worker_id
INNER JOIN workers AS released ON released.id = invoice_inputs.released_worker_id
WHERE
    invoice_inputs.project_id = $1
    AND invoice_inputs.id IN (
        SELECT invoice_materials.invoice_id
        FROM invoice_materials
        WHERE
            invoice_materials.project_id = $1
            AND invoice_materials.invoice_type = 'input'
            AND invoice_materials.material_cost_id IN (
                SELECT material_costs.id
                FROM material_costs
                WHERE material_costs.material_id = ANY($2::bigint[])
            )
    )
`

type CountInvoiceInputsByMaterialsParams struct {
	ProjectID   pgtype.Int8 `json:"project_id"`
	MaterialIds []int64     `json:"material_ids"`
}

func (q *Queries) CountInvoiceInputsByMaterials(ctx context.Context, arg CountInvoiceInputsByMaterialsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceInputsByMaterials, arg.ProjectID, arg.MaterialIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoiceInputsFiltered = `-- name: CountInvoiceInputsFiltered :one
SELECT COUNT(*)::bigint
FROM invoice_inputs
INNER JOIN workers AS warehouse_manager ON warehouse_manager.id = invoice_inputs.warehouse_manager_worker_id
INNER JOIN workers AS released ON released.id = invoice_inputs.released_worker_id
WHERE
    invoice_inputs.project_id = $1
    AND (NULLIF($2::bigint, 0) IS NULL OR warehouse_manager_worker_id = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR released_worker_id = $3)
    AND (NULLIF($4::text, '') IS NULL OR delivery_code = $4)
    AND (NULLIF($5::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR $5 <= invoice_inputs.date_of_invoice)
    AND (NULLIF($6::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR invoice_inputs.date_of_invoice <= $6)
`

type CountInvoiceInputsFilteredParams struct {
	ProjectID pgtype.Int8        `json:"project_id"`
	Column2   int64              `json:"column_2"`
	Column3   int64              `json:"column_3"`
	Column4   string             `json:"column_4"`
	Column5   pgtype.Timestamptz `json:"column_5"`
	Column6   pgtype.Timestamptz `json:"column_6"`
}

func (q *Queries) CountInvoiceInputsFiltered(ctx context.Context, arg CountInvoiceInputsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceInputsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvoiceInput = `-- name: CreateInvoiceInput :one
INSERT INTO invoice_inputs (project_id, warehouse_manager_worker_id, released_worker_id,
                            delivery_code, notes, date_of_invoice, confirmed)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, warehouse_manager_worker_id, released_worker_id,
          delivery_code, notes, date_of_invoice, confirmed
`

type CreateInvoiceInputParams struct {
	ProjectID                pgtype.Int8        `json:"project_id"`
	WarehouseManagerWorkerID pgtype.Int8        `json:"warehouse_manager_worker_id"`
	ReleasedWorkerID         pgtype.Int8        `json:"released_worker_id"`
	DeliveryCode             pgtype.Text        `json:"delivery_code"`
	Notes                    pgtype.Text        `json:"notes"`
	DateOfInvoice            pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmed                pgtype.Bool        `json:"confirmed"`
}

func (q *Queries) CreateInvoiceInput(ctx context.Context, arg CreateInvoiceInputParams) (InvoiceInput, error) {
	row := q.db.QueryRow(ctx, createInvoiceInput,
		arg.ProjectID,
		arg.WarehouseManagerWorkerID,
		arg.ReleasedWorkerID,
		arg.DeliveryCode,
		arg.Notes,
		arg.DateOfInvoice,
		arg.Confirmed,
	)
	var i InvoiceInput
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WarehouseManagerWorkerID,
		&i.ReleasedWorkerID,
		&i.DeliveryCode,
		&i.Notes,
		&i.DateOfInvoice,
		&i.Confirmed,
	)
	return i, err
}

const deleteInvoiceInput = `-- name: DeleteInvoiceInput :exec
DELETE FROM invoice_inputs WHERE id = $1
`

func (q *Queries) DeleteInvoiceInput(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceInput, id)
	return err
}

const getInvoiceInput = `-- name: GetInvoiceInput :one
SELECT id, project_id, warehouse_manager_worker_id, released_worker_id,
       delivery_code, notes, date_of_invoice, confirmed
FROM invoice_inputs
WHERE id = $1
`

func (q *Queries) GetInvoiceInput(ctx context.Context, id int64) (InvoiceInput, error) {
	row := q.db.QueryRow(ctx, getInvoiceInput, id)
	var i InvoiceInput
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WarehouseManagerWorkerID,
		&i.ReleasedWorkerID,
		&i.DeliveryCode,
		&i.Notes,
		&i.DateOfInvoice,
		&i.Confirmed,
	)
	return i, err
}

const listInvoiceInputAllDeliveryCodes = `-- name: ListInvoiceInputAllDeliveryCodes :many
SELECT COALESCE(delivery_code, '')::text AS delivery_code
FROM invoice_inputs
WHERE project_id = $1
`

func (q *Queries) ListInvoiceInputAllDeliveryCodes(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputAllDeliveryCodes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var delivery_code string
		if err := rows.Scan(&delivery_code); err != nil {
			return nil, err
		}
		items = append(items, delivery_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputAllMaterialsThatExist = `-- name: ListInvoiceInputAllMaterialsThatExist :many
SELECT DISTINCT
    materials.id                       AS value,
    COALESCE(materials.name, '')::text AS label
FROM invoice_materials
INNER JOIN material_costs ON invoice_materials.material_cost_id = material_costs.id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    invoice_materials.project_id = $1
    AND invoice_materials.invoice_type = 'input'
`

type ListInvoiceInputAllMaterialsThatExistRow struct {
	Value int64  `json:"value"`
	Label string `json:"label"`
}

func (q *Queries) ListInvoiceInputAllMaterialsThatExist(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputAllMaterialsThatExistRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputAllMaterialsThatExist, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputAllMaterialsThatExistRow{}
	for rows.Next() {
		var i ListInvoiceInputAllMaterialsThatExistRow
		if err := rows.Scan(&i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputAllReleasedWorkers = `-- name: ListInvoiceInputAllReleasedWorkers :many
SELECT DISTINCT
    workers.id                       AS value,
    COALESCE(workers.name, '')::text AS label
FROM invoice_inputs
INNER JOIN workers ON workers.id = invoice_inputs.released_worker_id
WHERE invoice_inputs.project_id = $1
`

type ListInvoiceInputAllReleasedWorkersRow struct {
	Value int64  `json:"value"`
	Label string `json:"label"`
}

func (q *Queries) ListInvoiceInputAllReleasedWorkers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputAllReleasedWorkersRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputAllReleasedWorkers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputAllReleasedWorkersRow{}
	for rows.Next() {
		var i ListInvoiceInputAllReleasedWorkersRow
		if err := rows.Scan(&i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputAllWarehouseManagers = `-- name: ListInvoiceInputAllWarehouseManagers :many
SELECT DISTINCT
    workers.id                       AS value,
    COALESCE(workers.name, '')::text AS label
FROM invoice_inputs
INNER JOIN workers ON workers.id = invoice_inputs.warehouse_manager_worker_id
WHERE invoice_inputs.project_id = $1
`

type ListInvoiceInputAllWarehouseManagersRow struct {
	Value int64  `json:"value"`
	Label string `json:"label"`
}

func (q *Queries) ListInvoiceInputAllWarehouseManagers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputAllWarehouseManagersRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputAllWarehouseManagers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputAllWarehouseManagersRow{}
	for rows.Next() {
		var i ListInvoiceInputAllWarehouseManagersRow
		if err := rows.Scan(&i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputMaterialsForEdit = `-- name: ListInvoiceInputMaterialsForEdit :many
SELECT
    materials.id                                            AS material_id,
    COALESCE(materials.name, '')::text                      AS material_name,
    COALESCE(materials.unit, '')::text                      AS unit,
    COALESCE(invoice_materials.amount, 0)::numeric          AS amount,
    material_costs.id                                       AS material_cost_id,
    COALESCE(material_costs.cost_m19, 0)::numeric           AS material_cost,
    COALESCE(invoice_materials.notes, '')::text             AS notes,
    COALESCE(materials.has_serial_number, false)::boolean   AS has_serial_number
FROM invoice_materials
INNER JOIN material_costs ON invoice_materials.material_cost_id = material_costs.id
INNER JOIN materials ON material_costs.material_id = materials.id
WHERE
    invoice_materials.invoice_type = 'input'
    AND invoice_materials.invoice_id = $1
    AND invoice_materials.project_id = $2
`

type ListInvoiceInputMaterialsForEditParams struct {
	InvoiceID pgtype.Int8 `json:"invoice_id"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

type ListInvoiceInputMaterialsForEditRow struct {
	MaterialID      int64          `json:"material_id"`
	MaterialName    string         `json:"material_name"`
	Unit            string         `json:"unit"`
	Amount          pgtype.Numeric `json:"amount"`
	MaterialCostID  int64          `json:"material_cost_id"`
	MaterialCost    pgtype.Numeric `json:"material_cost"`
	Notes           string         `json:"notes"`
	HasSerialNumber bool           `json:"has_serial_number"`
}

func (q *Queries) ListInvoiceInputMaterialsForEdit(ctx context.Context, arg ListInvoiceInputMaterialsForEditParams) ([]ListInvoiceInputMaterialsForEditRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputMaterialsForEdit, arg.InvoiceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputMaterialsForEditRow{}
	for rows.Next() {
		var i ListInvoiceInputMaterialsForEditRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialName,
			&i.Unit,
			&i.Amount,
			&i.MaterialCostID,
			&i.MaterialCost,
			&i.Notes,
			&i.HasSerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputReportFilterData = `-- name: ListInvoiceInputReportFilterData :many
SELECT
    invoice_inputs.id                                AS id,
    COALESCE(warehouse_manager.name, '')::text       AS warehouse_manager_name,
    COALESCE(released.name, '')::text                AS released_name,
    COALESCE(invoice_inputs.delivery_code, '')::text AS delivery_code,
    COALESCE(invoice_inputs.notes, '')::text         AS notes,
    invoice_inputs.date_of_invoice                   AS date_of_invoice
FROM invoice_inputs
INNER JOIN workers AS warehouse_manager ON warehouse_manager.id = invoice_inputs.warehouse_manager_worker_id
INNER JOIN workers AS released ON released.id = invoice_inputs.released_worker_id
WHERE
    invoice_inputs.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR invoice_inputs.delivery_code = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR invoice_inputs.released_worker_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR invoice_inputs.warehouse_manager_worker_id = $4)
    AND (NULLIF($5::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR $5 <= invoice_inputs.date_of_invoice)
    AND (NULLIF($6::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR invoice_inputs.date_of_invoice <= $6)
ORDER BY invoice_inputs.id DESC
`

type ListInvoiceInputReportFilterDataParams struct {
	ProjectID pgtype.Int8        `json:"project_id"`
	Column2   string             `json:"column_2"`
	Column3   int64              `json:"column_3"`
	Column4   int64              `json:"column_4"`
	Column5   pgtype.Timestamptz `json:"column_5"`
	Column6   pgtype.Timestamptz `json:"column_6"`
}

type ListInvoiceInputReportFilterDataRow struct {
	ID                   int64              `json:"id"`
	WarehouseManagerName string             `json:"warehouse_manager_name"`
	ReleasedName         string             `json:"released_name"`
	DeliveryCode         string             `json:"delivery_code"`
	Notes                string             `json:"notes"`
	DateOfInvoice        pgtype.Timestamptz `json:"date_of_invoice"`
}

func (q *Queries) ListInvoiceInputReportFilterData(ctx context.Context, arg ListInvoiceInputReportFilterDataParams) ([]ListInvoiceInputReportFilterDataRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputReportFilterData,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputReportFilterDataRow{}
	for rows.Next() {
		var i ListInvoiceInputReportFilterDataRow
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseManagerName,
			&i.ReleasedName,
			&i.DeliveryCode,
			&i.Notes,
			&i.DateOfInvoice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputUniqueDeliveryCodes = `-- name: ListInvoiceInputUniqueDeliveryCodes :many
SELECT
    COALESCE(delivery_code, '')::text AS label,
    COALESCE(delivery_code, '')::text AS value
FROM invoice_inputs
WHERE project_id = $1
ORDER BY id DESC
`

type ListInvoiceInputUniqueDeliveryCodesRow struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

func (q *Queries) ListInvoiceInputUniqueDeliveryCodes(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputUniqueDeliveryCodesRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputUniqueDeliveryCodes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputUniqueDeliveryCodesRow{}
	for rows.Next() {
		var i ListInvoiceInputUniqueDeliveryCodesRow
		if err := rows.Scan(&i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputUniqueReleasedWorkers = `-- name: ListInvoiceInputUniqueReleasedWorkers :many
SELECT
    workers.id                       AS value,
    COALESCE(workers.name, '')::text AS label
FROM workers
WHERE workers.id IN (
    SELECT DISTINCT(invoice_inputs.released_worker_id)
    FROM invoice_inputs
    WHERE invoice_inputs.project_id = $1 AND invoice_inputs.released_worker_id IS NOT NULL
)
`

type ListInvoiceInputUniqueReleasedWorkersRow struct {
	Value int64  `json:"value"`
	Label string `json:"label"`
}

func (q *Queries) ListInvoiceInputUniqueReleasedWorkers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputUniqueReleasedWorkersRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputUniqueReleasedWorkers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputUniqueReleasedWorkersRow{}
	for rows.Next() {
		var i ListInvoiceInputUniqueReleasedWorkersRow
		if err := rows.Scan(&i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputUniqueWarehouseManagers = `-- name: ListInvoiceInputUniqueWarehouseManagers :many
SELECT
    workers.id                       AS value,
    COALESCE(workers.name, '')::text AS label
FROM workers
WHERE workers.id IN (
    SELECT DISTINCT(invoice_inputs.warehouse_manager_worker_id)
    FROM invoice_inputs
    WHERE invoice_inputs.project_id = $1 AND invoice_inputs.warehouse_manager_worker_id IS NOT NULL
)
`

type ListInvoiceInputUniqueWarehouseManagersRow struct {
	Value int64  `json:"value"`
	Label string `json:"label"`
}

func (q *Queries) ListInvoiceInputUniqueWarehouseManagers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputUniqueWarehouseManagersRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputUniqueWarehouseManagers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputUniqueWarehouseManagersRow{}
	for rows.Next() {
		var i ListInvoiceInputUniqueWarehouseManagersRow
		if err := rows.Scan(&i.Value, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputs = `-- name: ListInvoiceInputs :many
SELECT id, project_id, warehouse_manager_worker_id, released_worker_id,
       delivery_code, notes, date_of_invoice, confirmed
FROM invoice_inputs
ORDER BY id DESC
`

func (q *Queries) ListInvoiceInputs(ctx context.Context) ([]InvoiceInput, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceInput{}
	for rows.Next() {
		var i InvoiceInput
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WarehouseManagerWorkerID,
			&i.ReleasedWorkerID,
			&i.DeliveryCode,
			&i.Notes,
			&i.DateOfInvoice,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputsPaginated = `-- name: ListInvoiceInputsPaginated :many
SELECT id, project_id, warehouse_manager_worker_id, released_worker_id,
       delivery_code, notes, date_of_invoice, confirmed
FROM invoice_inputs
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListInvoiceInputsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInvoiceInputsPaginated(ctx context.Context, arg ListInvoiceInputsPaginatedParams) ([]InvoiceInput, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceInput{}
	for rows.Next() {
		var i InvoiceInput
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.WarehouseManagerWorkerID,
			&i.ReleasedWorkerID,
			&i.DeliveryCode,
			&i.Notes,
			&i.DateOfInvoice,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputsPaginatedByMaterials = `-- name: ListInvoiceInputsPaginatedByMaterials :many
SELECT
    invoice_inputs.id                                                AS id,
    COALESCE(invoice_inputs.confirmed, false)::boolean               AS confirmation,
    COALESCE(invoice_inputs.delivery_code, '')::text                 AS delivery_code,
    COALESCE(warehouse_manager.name, '')::text                       AS warehouse_manager_name,
    COALESCE(released.name, '')::text                                AS released_name,
    invoice_inputs.date_of_invoice                                   AS date_of_invoice
FROM invoice_inputs
INNER JOIN workers AS warehouse_manager ON warehouse_manager.id = invoice_inputs.warehouse_manager_worker_id
INNER JOIN workers AS released ON released.id = invoice_inputs.released_worker_id
WHERE
    invoice_inputs.project_id = $1
    AND invoice_inputs.id IN (
        SELECT invoice_materials.invoice_id
        FROM invoice_materials
        WHERE
            invoice_materials.project_id = $1
            AND invoice_materials.invoice_type = 'input'
            AND invoice_materials.material_cost_id IN (
                SELECT material_costs.id
                FROM material_costs
                WHERE material_costs.material_id = ANY($4::bigint[])
            )
    )
ORDER BY invoice_inputs.id DESC
LIMIT $2 OFFSET $3
`

type ListInvoiceInputsPaginatedByMaterialsParams struct {
	ProjectID   pgtype.Int8 `json:"project_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	MaterialIds []int64     `json:"material_ids"`
}

type ListInvoiceInputsPaginatedByMaterialsRow struct {
	ID                   int64              `json:"id"`
	Confirmation         bool               `json:"confirmation"`
	DeliveryCode         string             `json:"delivery_code"`
	WarehouseManagerName string             `json:"warehouse_manager_name"`
	ReleasedName         string             `json:"released_name"`
	DateOfInvoice        pgtype.Timestamptz `json:"date_of_invoice"`
}

func (q *Queries) ListInvoiceInputsPaginatedByMaterials(ctx context.Context, arg ListInvoiceInputsPaginatedByMaterialsParams) ([]ListInvoiceInputsPaginatedByMaterialsRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputsPaginatedByMaterials,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.MaterialIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputsPaginatedByMaterialsRow{}
	for rows.Next() {
		var i ListInvoiceInputsPaginatedByMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Confirmation,
			&i.DeliveryCode,
			&i.WarehouseManagerName,
			&i.ReleasedName,
			&i.DateOfInvoice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputsPaginatedFiltered = `-- name: ListInvoiceInputsPaginatedFiltered :many
SELECT
    invoice_inputs.id                                                AS id,
    COALESCE(invoice_inputs.confirmed, false)::boolean               AS confirmation,
    COALESCE(invoice_inputs.delivery_code, '')::text                 AS delivery_code,
    COALESCE(warehouse_manager.name, '')::text                       AS warehouse_manager_name,
    COALESCE(released.name, '')::text                                AS released_name,
    invoice_inputs.date_of_invoice                                   AS date_of_invoice
FROM invoice_inputs
INNER JOIN workers AS warehouse_manager ON warehouse_manager.id = invoice_inputs.warehouse_manager_worker_id
INNER JOIN workers AS released ON released.id = invoice_inputs.released_worker_id
WHERE
    invoice_inputs.project_id = $1
    AND (NULLIF($2::bigint, 0) IS NULL OR warehouse_manager_worker_id = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR released_worker_id = $3)
    AND (NULLIF($4::text, '') IS NULL OR delivery_code = $4)
    AND (NULLIF($5::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR $5 <= invoice_inputs.date_of_invoice)
    AND (NULLIF($6::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR invoice_inputs.date_of_invoice <= $6)
ORDER BY invoice_inputs.id DESC
LIMIT $7 OFFSET $8
`

type ListInvoiceInputsPaginatedFilteredParams struct {
	ProjectID pgtype.Int8        `json:"project_id"`
	Column2   int64              `json:"column_2"`
	Column3   int64              `json:"column_3"`
	Column4   string             `json:"column_4"`
	Column5   pgtype.Timestamptz `json:"column_5"`
	Column6   pgtype.Timestamptz `json:"column_6"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
}

type ListInvoiceInputsPaginatedFilteredRow struct {
	ID                   int64              `json:"id"`
	Confirmation         bool               `json:"confirmation"`
	DeliveryCode         string             `json:"delivery_code"`
	WarehouseManagerName string             `json:"warehouse_manager_name"`
	ReleasedName         string             `json:"released_name"`
	DateOfInvoice        pgtype.Timestamptz `json:"date_of_invoice"`
}

func (q *Queries) ListInvoiceInputsPaginatedFiltered(ctx context.Context, arg ListInvoiceInputsPaginatedFilteredParams) ([]ListInvoiceInputsPaginatedFilteredRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputsPaginatedFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceInputsPaginatedFilteredRow{}
	for rows.Next() {
		var i ListInvoiceInputsPaginatedFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Confirmation,
			&i.DeliveryCode,
			&i.WarehouseManagerName,
			&i.ReleasedName,
			&i.DateOfInvoice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceInput = `-- name: UpdateInvoiceInput :one
UPDATE invoice_inputs
SET project_id = $2, warehouse_manager_worker_id = $3, released_worker_id = $4,
    delivery_code = $5, notes = $6, date_of_invoice = $7, confirmed = $8
WHERE id = $1
RETURNING id, project_id, warehouse_manager_worker_id, released_worker_id,
          delivery_code, notes, date_of_invoice, confirmed
`

type UpdateInvoiceInputParams struct {
	ID                       int64              `json:"id"`
	ProjectID                pgtype.Int8        `json:"project_id"`
	WarehouseManagerWorkerID pgtype.Int8        `json:"warehouse_manager_worker_id"`
	ReleasedWorkerID         pgtype.Int8        `json:"released_worker_id"`
	DeliveryCode             pgtype.Text        `json:"delivery_code"`
	Notes                    pgtype.Text        `json:"notes"`
	DateOfInvoice            pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmed                pgtype.Bool        `json:"confirmed"`
}

func (q *Queries) UpdateInvoiceInput(ctx context.Context, arg UpdateInvoiceInputParams) (InvoiceInput, error) {
	row := q.db.QueryRow(ctx, updateInvoiceInput,
		arg.ID,
		arg.ProjectID,
		arg.WarehouseManagerWorkerID,
		arg.ReleasedWorkerID,
		arg.DeliveryCode,
		arg.Notes,
		arg.DateOfInvoice,
		arg.Confirmed,
	)
	var i InvoiceInput
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.WarehouseManagerWorkerID,
		&i.ReleasedWorkerID,
		&i.DeliveryCode,
		&i.Notes,
		&i.DateOfInvoice,
		&i.Confirmed,
	)
	return i, err
}

const upsertMaterialLocationByID = `-- name: UpsertMaterialLocationByID :exec
UPDATE material_locations
SET amount = $1::numeric
WHERE id = $2
`

type UpsertMaterialLocationByIDParams struct {
	Amount pgtype.Numeric `json:"amount"`
	ID     int64          `json:"id"`
}

// Used by invoice_input.Confirmation: when an existing material_locations
// row is found for (project_id, material_cost_id, location_type='warehouse'),
// its amount is updated to the supplied total. The GORM-era code did this
// via clause.OnConflict on id; here it's an explicit UPDATE since the id
// is already known at this point.
func (q *Queries) UpsertMaterialLocationByID(ctx context.Context, arg UpsertMaterialLocationByIDParams) error {
	_, err := q.db.Exec(ctx, upsertMaterialLocationByID, arg.Amount, arg.ID)
	return err
}
