// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_count.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoiceCount = `-- name: CreateInvoiceCount :exec
INSERT INTO invoice_counts (project_id, invoice_type, count) VALUES ($1, $2, $3)
`

type CreateInvoiceCountParams struct {
	ProjectID   pgtype.Int8 `json:"project_id"`
	InvoiceType pgtype.Text `json:"invoice_type"`
	Count       pgtype.Int8 `json:"count"`
}

func (q *Queries) CreateInvoiceCount(ctx context.Context, arg CreateInvoiceCountParams) error {
	_, err := q.db.Exec(ctx, createInvoiceCount, arg.ProjectID, arg.InvoiceType, arg.Count)
	return err
}

const getInvoiceCount = `-- name: GetInvoiceCount :one
SELECT COALESCE(count, 0)::bigint AS count
FROM invoice_counts
WHERE invoice_type = $1 AND project_id = $2
LIMIT 1
`

type GetInvoiceCountParams struct {
	InvoiceType pgtype.Text `json:"invoice_type"`
	ProjectID   pgtype.Int8 `json:"project_id"`
}

func (q *Queries) GetInvoiceCount(ctx context.Context, arg GetInvoiceCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getInvoiceCount, arg.InvoiceType, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementInvoiceCount = `-- name: IncrementInvoiceCount :exec
UPDATE invoice_counts
SET count = COALESCE(count, 0) + 1
WHERE invoice_type = $1 AND project_id = $2
`

type IncrementInvoiceCountParams struct {
	InvoiceType pgtype.Text `json:"invoice_type"`
	ProjectID   pgtype.Int8 `json:"project_id"`
}

func (q *Queries) IncrementInvoiceCount(ctx context.Context, arg IncrementInvoiceCountParams) error {
	_, err := q.db.Exec(ctx, incrementInvoiceCount, arg.InvoiceType, arg.ProjectID)
	return err
}

const incrementInvoiceCountBy = `-- name: IncrementInvoiceCountBy :exec
UPDATE invoice_counts
SET count = COALESCE(count, 0) + $3::bigint
WHERE invoice_type = $1 AND project_id = $2
`

type IncrementInvoiceCountByParams struct {
	InvoiceType pgtype.Text `json:"invoice_type"`
	ProjectID   pgtype.Int8 `json:"project_id"`
	Amount      int64       `json:"amount"`
}

func (q *Queries) IncrementInvoiceCountBy(ctx context.Context, arg IncrementInvoiceCountByParams) error {
	_, err := q.db.Exec(ctx, incrementInvoiceCountBy, arg.InvoiceType, arg.ProjectID, arg.Amount)
	return err
}
