// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_writeoff.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoiceWriteOffsFiltered = `-- name: CountInvoiceWriteOffsFiltered :one
SELECT COUNT(*)::bigint
FROM invoice_write_offs
WHERE
    invoice_write_offs.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR invoice_write_offs.write_off_type = $2)
`

type CountInvoiceWriteOffsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
}

func (q *Queries) CountInvoiceWriteOffsFiltered(ctx context.Context, arg CountInvoiceWriteOffsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceWriteOffsFiltered, arg.ProjectID, arg.Column2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvoiceWriteOff = `-- name: CreateInvoiceWriteOff :one
INSERT INTO invoice_write_offs (
    project_id, released_worker_id, write_off_type, write_off_location_id,
    delivery_code, date_of_invoice, confirmation, date_of_confirmation, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, released_worker_id, write_off_type, write_off_location_id,
          delivery_code, date_of_invoice, confirmation, date_of_confirmation, notes
`

type CreateInvoiceWriteOffParams struct {
	ProjectID          pgtype.Int8        `json:"project_id"`
	ReleasedWorkerID   pgtype.Int8        `json:"released_worker_id"`
	WriteOffType       pgtype.Text        `json:"write_off_type"`
	WriteOffLocationID pgtype.Int8        `json:"write_off_location_id"`
	DeliveryCode       pgtype.Text        `json:"delivery_code"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmation       pgtype.Bool        `json:"confirmation"`
	DateOfConfirmation pgtype.Timestamptz `json:"date_of_confirmation"`
	Notes              pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateInvoiceWriteOff(ctx context.Context, arg CreateInvoiceWriteOffParams) (InvoiceWriteOff, error) {
	row := q.db.QueryRow(ctx, createInvoiceWriteOff,
		arg.ProjectID,
		arg.ReleasedWorkerID,
		arg.WriteOffType,
		arg.WriteOffLocationID,
		arg.DeliveryCode,
		arg.DateOfInvoice,
		arg.Confirmation,
		arg.DateOfConfirmation,
		arg.Notes,
	)
	var i InvoiceWriteOff
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleasedWorkerID,
		&i.WriteOffType,
		&i.WriteOffLocationID,
		&i.DeliveryCode,
		&i.DateOfInvoice,
		&i.Confirmation,
		&i.DateOfConfirmation,
		&i.Notes,
	)
	return i, err
}

const deleteInvoiceWriteOff = `-- name: DeleteInvoiceWriteOff :exec
DELETE FROM invoice_write_offs WHERE id = $1
`

func (q *Queries) DeleteInvoiceWriteOff(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceWriteOff, id)
	return err
}

const getInvoiceWriteOff = `-- name: GetInvoiceWriteOff :one
SELECT id, project_id, released_worker_id, write_off_type, write_off_location_id,
       delivery_code, date_of_invoice, confirmation, date_of_confirmation, notes
FROM invoice_write_offs
WHERE id = $1
`

func (q *Queries) GetInvoiceWriteOff(ctx context.Context, id int64) (InvoiceWriteOff, error) {
	row := q.db.QueryRow(ctx, getInvoiceWriteOff, id)
	var i InvoiceWriteOff
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleasedWorkerID,
		&i.WriteOffType,
		&i.WriteOffLocationID,
		&i.DeliveryCode,
		&i.DateOfInvoice,
		&i.Confirmation,
		&i.DateOfConfirmation,
		&i.Notes,
	)
	return i, err
}

const listInvoiceWriteOffMaterialsForEdit = `-- name: ListInvoiceWriteOffMaterialsForEdit :many
SELECT
    materials.id                                                  AS material_id,
    COALESCE(materials.name, '')::text                            AS material_name,
    COALESCE(materials.unit, '')::text                            AS unit,
    COALESCE(invoice_materials.amount, 0)::numeric                AS amount,
    material_costs.id                                             AS material_cost_id,
    COALESCE(material_costs.cost_m19, 0)::numeric                 AS material_cost,
    COALESCE(invoice_materials.notes, '')::text                   AS notes,
    COALESCE(materials.has_serial_number, false)::boolean         AS has_serial_number,
    COALESCE(material_locations.amount, 0)::numeric               AS location_amount
FROM invoice_materials
INNER JOIN material_costs ON invoice_materials.material_cost_id = material_costs.id
INNER JOIN materials ON material_costs.material_id = materials.id
INNER JOIN material_locations ON material_locations.material_cost_id = invoice_materials.material_cost_id
WHERE
    invoice_materials.invoice_type = 'writeoff'
    AND invoice_materials.invoice_id = $1
    AND material_locations.location_type = $2
    AND material_locations.location_id = $3
ORDER BY materials.id
`

type ListInvoiceWriteOffMaterialsForEditParams struct {
	InvoiceID    pgtype.Int8 `json:"invoice_id"`
	LocationType pgtype.Text `json:"location_type"`
	LocationID   pgtype.Int8 `json:"location_id"`
}

type ListInvoiceWriteOffMaterialsForEditRow struct {
	MaterialID      int64          `json:"material_id"`
	MaterialName    string         `json:"material_name"`
	Unit            string         `json:"unit"`
	Amount          pgtype.Numeric `json:"amount"`
	MaterialCostID  int64          `json:"material_cost_id"`
	MaterialCost    pgtype.Numeric `json:"material_cost"`
	Notes           string         `json:"notes"`
	HasSerialNumber bool           `json:"has_serial_number"`
	LocationAmount  pgtype.Numeric `json:"location_amount"`
}

func (q *Queries) ListInvoiceWriteOffMaterialsForEdit(ctx context.Context, arg ListInvoiceWriteOffMaterialsForEditParams) ([]ListInvoiceWriteOffMaterialsForEditRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceWriteOffMaterialsForEdit, arg.InvoiceID, arg.LocationType, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceWriteOffMaterialsForEditRow{}
	for rows.Next() {
		var i ListInvoiceWriteOffMaterialsForEditRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialName,
			&i.Unit,
			&i.Amount,
			&i.MaterialCostID,
			&i.MaterialCost,
			&i.Notes,
			&i.HasSerialNumber,
			&i.LocationAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceWriteOffReportData = `-- name: ListInvoiceWriteOffReportData :many
SELECT
    invoice_write_offs.id                                       AS id,
    COALESCE(invoice_write_offs.delivery_code, '')::text        AS delivery_code,
    COALESCE(released.name, '')::text                           AS released_worker_name,
    invoice_write_offs.date_of_invoice                          AS date_of_invoice
FROM invoice_write_offs
INNER JOIN workers AS released ON released.id = invoice_write_offs.released_worker_id
WHERE
    invoice_write_offs.project_id = $1
    AND invoice_write_offs.write_off_type = $2
    AND COALESCE(invoice_write_offs.confirmation, false) = true
    AND (NULLIF($3::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR $3 <= invoice_write_offs.date_of_invoice)
    AND (NULLIF($4::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR invoice_write_offs.date_of_invoice <= $4)
ORDER BY invoice_write_offs.id DESC
`

type ListInvoiceWriteOffReportDataParams struct {
	ProjectID    pgtype.Int8        `json:"project_id"`
	WriteOffType pgtype.Text        `json:"write_off_type"`
	Column3      pgtype.Timestamptz `json:"column_3"`
	Column4      pgtype.Timestamptz `json:"column_4"`
}

type ListInvoiceWriteOffReportDataRow struct {
	ID                 int64              `json:"id"`
	DeliveryCode       string             `json:"delivery_code"`
	ReleasedWorkerName string             `json:"released_worker_name"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
}

func (q *Queries) ListInvoiceWriteOffReportData(ctx context.Context, arg ListInvoiceWriteOffReportDataParams) ([]ListInvoiceWriteOffReportDataRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceWriteOffReportData,
		arg.ProjectID,
		arg.WriteOffType,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceWriteOffReportDataRow{}
	for rows.Next() {
		var i ListInvoiceWriteOffReportDataRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryCode,
			&i.ReleasedWorkerName,
			&i.DateOfInvoice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceWriteOffs = `-- name: ListInvoiceWriteOffs :many
SELECT id, project_id, released_worker_id, write_off_type, write_off_location_id,
       delivery_code, date_of_invoice, confirmation, date_of_confirmation, notes
FROM invoice_write_offs
ORDER BY id DESC
`

func (q *Queries) ListInvoiceWriteOffs(ctx context.Context) ([]InvoiceWriteOff, error) {
	rows, err := q.db.Query(ctx, listInvoiceWriteOffs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceWriteOff{}
	for rows.Next() {
		var i InvoiceWriteOff
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ReleasedWorkerID,
			&i.WriteOffType,
			&i.WriteOffLocationID,
			&i.DeliveryCode,
			&i.DateOfInvoice,
			&i.Confirmation,
			&i.DateOfConfirmation,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceWriteOffsPaginated = `-- name: ListInvoiceWriteOffsPaginated :many
SELECT
    invoice_write_offs.id                                       AS id,
    COALESCE(invoice_write_offs.write_off_type, '')::text       AS write_off_type,
    COALESCE(invoice_write_offs.write_off_location_id, 0)::bigint AS write_off_location_id,
    invoice_write_offs.released_worker_id                       AS released_worker_id,
    COALESCE(workers.name, '')::text                            AS released_worker_name,
    COALESCE(invoice_write_offs.delivery_code, '')::text        AS delivery_code,
    invoice_write_offs.date_of_invoice                          AS date_of_invoice,
    COALESCE(invoice_write_offs.confirmation, false)::boolean   AS confirmation,
    invoice_write_offs.date_of_confirmation                     AS date_of_confirmation
FROM invoice_write_offs
INNER JOIN workers ON workers.id = invoice_write_offs.released_worker_id
WHERE
    invoice_write_offs.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR invoice_write_offs.write_off_type = $2)
ORDER BY invoice_write_offs.id DESC
LIMIT $3 OFFSET $4
`

type ListInvoiceWriteOffsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListInvoiceWriteOffsPaginatedRow struct {
	ID                 int64              `json:"id"`
	WriteOffType       string             `json:"write_off_type"`
	WriteOffLocationID int64              `json:"write_off_location_id"`
	ReleasedWorkerID   pgtype.Int8        `json:"released_worker_id"`
	ReleasedWorkerName string             `json:"released_worker_name"`
	DeliveryCode       string             `json:"delivery_code"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmation       bool               `json:"confirmation"`
	DateOfConfirmation pgtype.Timestamptz `json:"date_of_confirmation"`
}

func (q *Queries) ListInvoiceWriteOffsPaginated(ctx context.Context, arg ListInvoiceWriteOffsPaginatedParams) ([]ListInvoiceWriteOffsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceWriteOffsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceWriteOffsPaginatedRow{}
	for rows.Next() {
		var i ListInvoiceWriteOffsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.WriteOffType,
			&i.WriteOffLocationID,
			&i.ReleasedWorkerID,
			&i.ReleasedWorkerName,
			&i.DeliveryCode,
			&i.DateOfInvoice,
			&i.Confirmation,
			&i.DateOfConfirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialLocationsByLocationType = `-- name: ListMaterialLocationsByLocationType :many
SELECT id, project_id, material_cost_id, location_id, location_type, amount
FROM material_locations
WHERE location_type = $1
`

// Used by invoice_writeoff Confirmation: gets all material_locations rows
// for a given polymorphic location_type (e.g. 'writeoff-warehouse',
// 'loss-team', etc — these are the writeoff sentinel location types).
func (q *Queries) ListMaterialLocationsByLocationType(ctx context.Context, locationType pgtype.Text) ([]MaterialLocation, error) {
	rows, err := q.db.Query(ctx, listMaterialLocationsByLocationType, locationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialLocation{}
	for rows.Next() {
		var i MaterialLocation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MaterialCostID,
			&i.LocationID,
			&i.LocationType,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceWriteOff = `-- name: UpdateInvoiceWriteOff :one
UPDATE invoice_write_offs
SET project_id = $2, released_worker_id = $3, write_off_type = $4,
    write_off_location_id = $5, delivery_code = $6, date_of_invoice = $7,
    confirmation = $8, date_of_confirmation = $9, notes = $10
WHERE id = $1
RETURNING id, project_id, released_worker_id, write_off_type, write_off_location_id,
          delivery_code, date_of_invoice, confirmation, date_of_confirmation, notes
`

type UpdateInvoiceWriteOffParams struct {
	ID                 int64              `json:"id"`
	ProjectID          pgtype.Int8        `json:"project_id"`
	ReleasedWorkerID   pgtype.Int8        `json:"released_worker_id"`
	WriteOffType       pgtype.Text        `json:"write_off_type"`
	WriteOffLocationID pgtype.Int8        `json:"write_off_location_id"`
	DeliveryCode       pgtype.Text        `json:"delivery_code"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmation       pgtype.Bool        `json:"confirmation"`
	DateOfConfirmation pgtype.Timestamptz `json:"date_of_confirmation"`
	Notes              pgtype.Text        `json:"notes"`
}

func (q *Queries) UpdateInvoiceWriteOff(ctx context.Context, arg UpdateInvoiceWriteOffParams) (InvoiceWriteOff, error) {
	row := q.db.QueryRow(ctx, updateInvoiceWriteOff,
		arg.ID,
		arg.ProjectID,
		arg.ReleasedWorkerID,
		arg.WriteOffType,
		arg.WriteOffLocationID,
		arg.DeliveryCode,
		arg.DateOfInvoice,
		arg.Confirmation,
		arg.DateOfConfirmation,
		arg.Notes,
	)
	var i InvoiceWriteOff
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleasedWorkerID,
		&i.WriteOffType,
		&i.WriteOffLocationID,
		&i.DeliveryCode,
		&i.DateOfInvoice,
		&i.Confirmation,
		&i.DateOfConfirmation,
		&i.Notes,
	)
	return i, err
}

const updateInvoiceWriteOffConfirmation = `-- name: UpdateInvoiceWriteOffConfirmation :exec
UPDATE invoice_write_offs
SET confirmation = $2, date_of_confirmation = $3
WHERE id = $1
`

type UpdateInvoiceWriteOffConfirmationParams struct {
	ID                 int64              `json:"id"`
	Confirmation       pgtype.Bool        `json:"confirmation"`
	DateOfConfirmation pgtype.Timestamptz `json:"date_of_confirmation"`
}

func (q *Queries) UpdateInvoiceWriteOffConfirmation(ctx context.Context, arg UpdateInvoiceWriteOffConfirmationParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceWriteOffConfirmation, arg.ID, arg.Confirmation, arg.DateOfConfirmation)
	return err
}
