// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_output_out_of_project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmInvoiceOutputOutOfProject = `-- name: ConfirmInvoiceOutputOutOfProject :exec
UPDATE invoice_output_out_of_projects
SET confirmation = true
WHERE id = $1
`

func (q *Queries) ConfirmInvoiceOutputOutOfProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, confirmInvoiceOutputOutOfProject, id)
	return err
}

const countInvoiceOutputOutOfProjects = `-- name: CountInvoiceOutputOutOfProjects :one
SELECT COUNT(*)::bigint
FROM invoice_output_out_of_projects
WHERE
    project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR name_of_project = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR released_worker_id = $3)
`

type CountInvoiceOutputOutOfProjectsParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
}

func (q *Queries) CountInvoiceOutputOutOfProjects(ctx context.Context, arg CountInvoiceOutputOutOfProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceOutputOutOfProjects, arg.ProjectID, arg.Column2, arg.Column3)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvoiceOutputOutOfProject = `-- name: CreateInvoiceOutputOutOfProject :one
INSERT INTO invoice_output_out_of_projects (
    project_id, delivery_code, released_worker_id, name_of_project,
    date_of_invoice, notes, confirmation
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, delivery_code, released_worker_id, name_of_project,
          date_of_invoice, notes, confirmation
`

type CreateInvoiceOutputOutOfProjectParams struct {
	ProjectID        pgtype.Int8        `json:"project_id"`
	DeliveryCode     pgtype.Text        `json:"delivery_code"`
	ReleasedWorkerID pgtype.Int8        `json:"released_worker_id"`
	NameOfProject    pgtype.Text        `json:"name_of_project"`
	DateOfInvoice    pgtype.Timestamptz `json:"date_of_invoice"`
	Notes            pgtype.Text        `json:"notes"`
	Confirmation     pgtype.Bool        `json:"confirmation"`
}

func (q *Queries) CreateInvoiceOutputOutOfProject(ctx context.Context, arg CreateInvoiceOutputOutOfProjectParams) (InvoiceOutputOutOfProject, error) {
	row := q.db.QueryRow(ctx, createInvoiceOutputOutOfProject,
		arg.ProjectID,
		arg.DeliveryCode,
		arg.ReleasedWorkerID,
		arg.NameOfProject,
		arg.DateOfInvoice,
		arg.Notes,
		arg.Confirmation,
	)
	var i InvoiceOutputOutOfProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeliveryCode,
		&i.ReleasedWorkerID,
		&i.NameOfProject,
		&i.DateOfInvoice,
		&i.Notes,
		&i.Confirmation,
	)
	return i, err
}

const deleteInvoiceOutputOutOfProject = `-- name: DeleteInvoiceOutputOutOfProject :exec
DELETE FROM invoice_output_out_of_projects WHERE id = $1
`

func (q *Queries) DeleteInvoiceOutputOutOfProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceOutputOutOfProject, id)
	return err
}

const getInvoiceOutputOutOfProject = `-- name: GetInvoiceOutputOutOfProject :one
SELECT id, project_id, delivery_code, released_worker_id, name_of_project,
       date_of_invoice, notes, confirmation
FROM invoice_output_out_of_projects
WHERE id = $1
`

func (q *Queries) GetInvoiceOutputOutOfProject(ctx context.Context, id int64) (InvoiceOutputOutOfProject, error) {
	row := q.db.QueryRow(ctx, getInvoiceOutputOutOfProject, id)
	var i InvoiceOutputOutOfProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeliveryCode,
		&i.ReleasedWorkerID,
		&i.NameOfProject,
		&i.DateOfInvoice,
		&i.Notes,
		&i.Confirmation,
	)
	return i, err
}

const getInvoiceOutputOutOfProjectByDeliveryCode = `-- name: GetInvoiceOutputOutOfProjectByDeliveryCode :one
SELECT id, project_id, delivery_code, released_worker_id, name_of_project,
       date_of_invoice, notes, confirmation
FROM invoice_output_out_of_projects
WHERE delivery_code = $1
LIMIT 1
`

func (q *Queries) GetInvoiceOutputOutOfProjectByDeliveryCode(ctx context.Context, deliveryCode pgtype.Text) (InvoiceOutputOutOfProject, error) {
	row := q.db.QueryRow(ctx, getInvoiceOutputOutOfProjectByDeliveryCode, deliveryCode)
	var i InvoiceOutputOutOfProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeliveryCode,
		&i.ReleasedWorkerID,
		&i.NameOfProject,
		&i.DateOfInvoice,
		&i.Notes,
		&i.Confirmation,
	)
	return i, err
}

const listInvoiceOutputOutOfProjectMaterialsForEdit = `-- name: ListInvoiceOutputOutOfProjectMaterialsForEdit :many
SELECT
    materials.id                                                  AS material_id,
    COALESCE(materials.name, '')::text                            AS material_name,
    COALESCE(materials.unit, '')::text                            AS material_unit,
    COALESCE(material_locations.amount, 0)::numeric               AS warehouse_amount,
    COALESCE(invoice_materials.amount, 0)::numeric                AS amount,
    COALESCE(invoice_materials.notes, '')::text                   AS notes,
    COALESCE(materials.has_serial_number, false)::boolean         AS has_serial_number
FROM invoice_materials
INNER JOIN material_costs ON material_costs.id = invoice_materials.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
INNER JOIN material_locations ON material_locations.material_cost_id = invoice_materials.material_cost_id
WHERE
    material_locations.location_type = 'warehouse'
    AND invoice_materials.invoice_type = 'output-out-of-project'
    AND invoice_materials.invoice_id = $1
ORDER BY materials.id
`

type ListInvoiceOutputOutOfProjectMaterialsForEditRow struct {
	MaterialID      int64          `json:"material_id"`
	MaterialName    string         `json:"material_name"`
	MaterialUnit    string         `json:"material_unit"`
	WarehouseAmount pgtype.Numeric `json:"warehouse_amount"`
	Amount          pgtype.Numeric `json:"amount"`
	Notes           string         `json:"notes"`
	HasSerialNumber bool           `json:"has_serial_number"`
}

func (q *Queries) ListInvoiceOutputOutOfProjectMaterialsForEdit(ctx context.Context, invoiceID pgtype.Int8) ([]ListInvoiceOutputOutOfProjectMaterialsForEditRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputOutOfProjectMaterialsForEdit, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputOutOfProjectMaterialsForEditRow{}
	for rows.Next() {
		var i ListInvoiceOutputOutOfProjectMaterialsForEditRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialName,
			&i.MaterialUnit,
			&i.WarehouseAmount,
			&i.Amount,
			&i.Notes,
			&i.HasSerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputOutOfProjectReportData = `-- name: ListInvoiceOutputOutOfProjectReportData :many
SELECT
    invoice_output_out_of_projects.id                              AS id,
    COALESCE(invoice_output_out_of_projects.name_of_project, '')::text  AS name_of_project,
    COALESCE(invoice_output_out_of_projects.delivery_code, '')::text    AS delivery_code,
    COALESCE(workers.name, '')::text                               AS released_worker_name,
    invoice_output_out_of_projects.date_of_invoice                 AS date_of_invoice
FROM invoice_output_out_of_projects
INNER JOIN workers ON invoice_output_out_of_projects.released_worker_id = workers.id
WHERE
    invoice_output_out_of_projects.project_id = $1
    AND COALESCE(invoice_output_out_of_projects.confirmation, false) = true
    AND (NULLIF($2::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR $2 <= invoice_output_out_of_projects.date_of_invoice)
    AND (NULLIF($3::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR invoice_output_out_of_projects.date_of_invoice <= $3)
ORDER BY invoice_output_out_of_projects.id DESC
`

type ListInvoiceOutputOutOfProjectReportDataParams struct {
	ProjectID pgtype.Int8        `json:"project_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
	Column3   pgtype.Timestamptz `json:"column_3"`
}

type ListInvoiceOutputOutOfProjectReportDataRow struct {
	ID                 int64              `json:"id"`
	NameOfProject      string             `json:"name_of_project"`
	DeliveryCode       string             `json:"delivery_code"`
	ReleasedWorkerName string             `json:"released_worker_name"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
}

func (q *Queries) ListInvoiceOutputOutOfProjectReportData(ctx context.Context, arg ListInvoiceOutputOutOfProjectReportDataParams) ([]ListInvoiceOutputOutOfProjectReportDataRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputOutOfProjectReportData, arg.ProjectID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputOutOfProjectReportDataRow{}
	for rows.Next() {
		var i ListInvoiceOutputOutOfProjectReportDataRow
		if err := rows.Scan(
			&i.ID,
			&i.NameOfProject,
			&i.DeliveryCode,
			&i.ReleasedWorkerName,
			&i.DateOfInvoice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputOutOfProjectUniqueNameOfProjects = `-- name: ListInvoiceOutputOutOfProjectUniqueNameOfProjects :many
SELECT DISTINCT(COALESCE(invoice_output_out_of_projects.name_of_project, '')::text)
FROM invoice_output_out_of_projects
WHERE invoice_output_out_of_projects.project_id = $1
`

func (q *Queries) ListInvoiceOutputOutOfProjectUniqueNameOfProjects(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputOutOfProjectUniqueNameOfProjects, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputOutOfProjectsPaginated = `-- name: ListInvoiceOutputOutOfProjectsPaginated :many
SELECT
    invoice_output_out_of_projects.id                              AS id,
    COALESCE(invoice_output_out_of_projects.name_of_project, '')::text  AS name_of_project,
    COALESCE(invoice_output_out_of_projects.delivery_code, '')::text    AS delivery_code,
    COALESCE(workers.name, '')::text                               AS released_worker_name,
    invoice_output_out_of_projects.date_of_invoice                 AS date_of_invoice,
    COALESCE(invoice_output_out_of_projects.confirmation, false)::boolean AS confirmation
FROM invoice_output_out_of_projects
INNER JOIN workers ON invoice_output_out_of_projects.released_worker_id = workers.id
WHERE
    invoice_output_out_of_projects.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR name_of_project = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR released_worker_id = $3)
ORDER BY invoice_output_out_of_projects.id DESC
LIMIT $4 OFFSET $5
`

type ListInvoiceOutputOutOfProjectsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListInvoiceOutputOutOfProjectsPaginatedRow struct {
	ID                 int64              `json:"id"`
	NameOfProject      string             `json:"name_of_project"`
	DeliveryCode       string             `json:"delivery_code"`
	ReleasedWorkerName string             `json:"released_worker_name"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmation       bool               `json:"confirmation"`
}

func (q *Queries) ListInvoiceOutputOutOfProjectsPaginated(ctx context.Context, arg ListInvoiceOutputOutOfProjectsPaginatedParams) ([]ListInvoiceOutputOutOfProjectsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputOutOfProjectsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceOutputOutOfProjectsPaginatedRow{}
	for rows.Next() {
		var i ListInvoiceOutputOutOfProjectsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.NameOfProject,
			&i.DeliveryCode,
			&i.ReleasedWorkerName,
			&i.DateOfInvoice,
			&i.Confirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceOutputOutOfProject = `-- name: UpdateInvoiceOutputOutOfProject :one
UPDATE invoice_output_out_of_projects
SET project_id = $2, delivery_code = $3, released_worker_id = $4,
    name_of_project = $5, date_of_invoice = $6, notes = $7, confirmation = $8
WHERE id = $1
RETURNING id, project_id, delivery_code, released_worker_id, name_of_project,
          date_of_invoice, notes, confirmation
`

type UpdateInvoiceOutputOutOfProjectParams struct {
	ID               int64              `json:"id"`
	ProjectID        pgtype.Int8        `json:"project_id"`
	DeliveryCode     pgtype.Text        `json:"delivery_code"`
	ReleasedWorkerID pgtype.Int8        `json:"released_worker_id"`
	NameOfProject    pgtype.Text        `json:"name_of_project"`
	DateOfInvoice    pgtype.Timestamptz `json:"date_of_invoice"`
	Notes            pgtype.Text        `json:"notes"`
	Confirmation     pgtype.Bool        `json:"confirmation"`
}

func (q *Queries) UpdateInvoiceOutputOutOfProject(ctx context.Context, arg UpdateInvoiceOutputOutOfProjectParams) (InvoiceOutputOutOfProject, error) {
	row := q.db.QueryRow(ctx, updateInvoiceOutputOutOfProject,
		arg.ID,
		arg.ProjectID,
		arg.DeliveryCode,
		arg.ReleasedWorkerID,
		arg.NameOfProject,
		arg.DateOfInvoice,
		arg.Notes,
		arg.Confirmation,
	)
	var i InvoiceOutputOutOfProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DeliveryCode,
		&i.ReleasedWorkerID,
		&i.NameOfProject,
		&i.DateOfInvoice,
		&i.Notes,
		&i.Confirmation,
	)
	return i, err
}
