// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_return.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmInvoiceReturn = `-- name: ConfirmInvoiceReturn :exec
UPDATE invoice_returns
SET confirmation = true
WHERE id = $1
`

func (q *Queries) ConfirmInvoiceReturn(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, confirmInvoiceReturn, id)
	return err
}

const confirmSerialNumberLocationsByReturnInvoice = `-- name: ConfirmSerialNumberLocationsByReturnInvoice :exec
UPDATE serial_number_locations
SET location_type = 'team', location_id = $1::bigint
WHERE serial_number_locations.serial_number_id IN (
    SELECT serial_number_movements.serial_number_id
    FROM serial_number_movements
    WHERE
        serial_number_movements.invoice_type = 'return'
        AND serial_number_movements.invoice_id = $2::bigint
)
`

type ConfirmSerialNumberLocationsByReturnInvoiceParams struct {
	AcceptorID int64 `json:"acceptor_id"`
	InvoiceID  int64 `json:"invoice_id"`
}

// After invoice_return confirmation, serial_number_locations rows for the
// invoice's serial numbers are flipped to the team acceptor.
func (q *Queries) ConfirmSerialNumberLocationsByReturnInvoice(ctx context.Context, arg ConfirmSerialNumberLocationsByReturnInvoiceParams) error {
	_, err := q.db.Exec(ctx, confirmSerialNumberLocationsByReturnInvoice, arg.AcceptorID, arg.InvoiceID)
	return err
}

const countInvoiceReturnsBasedOnType = `-- name: CountInvoiceReturnsBasedOnType :one
SELECT COUNT(*)::bigint
FROM invoice_returns
WHERE project_id = $1 AND returner_type = $2
`

type CountInvoiceReturnsBasedOnTypeParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	ReturnerType pgtype.Text `json:"returner_type"`
}

func (q *Queries) CountInvoiceReturnsBasedOnType(ctx context.Context, arg CountInvoiceReturnsBasedOnTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceReturnsBasedOnType, arg.ProjectID, arg.ReturnerType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoiceReturnsByProject = `-- name: CountInvoiceReturnsByProject :one
SELECT COUNT(*)::bigint FROM invoice_returns WHERE project_id = $1
`

func (q *Queries) CountInvoiceReturnsByProject(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceReturnsByProject, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvoiceReturn = `-- name: CreateInvoiceReturn :one
INSERT INTO invoice_returns (
    project_id, district_id, returner_type, returner_id,
    acceptor_type, acceptor_id, accepted_by_worker_id, date_of_invoice,
    notes, delivery_code, confirmation
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, project_id, district_id, returner_type, returner_id,
          acceptor_type, acceptor_id, accepted_by_worker_id, date_of_invoice,
          notes, delivery_code, confirmation
`

type CreateInvoiceReturnParams struct {
	ProjectID          pgtype.Int8        `json:"project_id"`
	DistrictID         pgtype.Int8        `json:"district_id"`
	ReturnerType       pgtype.Text        `json:"returner_type"`
	ReturnerID         pgtype.Int8        `json:"returner_id"`
	AcceptorType       pgtype.Text        `json:"acceptor_type"`
	AcceptorID         pgtype.Int8        `json:"acceptor_id"`
	AcceptedByWorkerID pgtype.Int8        `json:"accepted_by_worker_id"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
	Notes              pgtype.Text        `json:"notes"`
	DeliveryCode       pgtype.Text        `json:"delivery_code"`
	Confirmation       pgtype.Bool        `json:"confirmation"`
}

func (q *Queries) CreateInvoiceReturn(ctx context.Context, arg CreateInvoiceReturnParams) (InvoiceReturn, error) {
	row := q.db.QueryRow(ctx, createInvoiceReturn,
		arg.ProjectID,
		arg.DistrictID,
		arg.ReturnerType,
		arg.ReturnerID,
		arg.AcceptorType,
		arg.AcceptorID,
		arg.AcceptedByWorkerID,
		arg.DateOfInvoice,
		arg.Notes,
		arg.DeliveryCode,
		arg.Confirmation,
	)
	var i InvoiceReturn
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DistrictID,
		&i.ReturnerType,
		&i.ReturnerID,
		&i.AcceptorType,
		&i.AcceptorID,
		&i.AcceptedByWorkerID,
		&i.DateOfInvoice,
		&i.Notes,
		&i.DeliveryCode,
		&i.Confirmation,
	)
	return i, err
}

const createMaterialDefect = `-- name: CreateMaterialDefect :one
INSERT INTO material_defects (amount, material_location_id)
VALUES ($1, $2)
RETURNING id, amount, material_location_id
`

type CreateMaterialDefectParams struct {
	Amount             pgtype.Numeric `json:"amount"`
	MaterialLocationID pgtype.Int8    `json:"material_location_id"`
}

func (q *Queries) CreateMaterialDefect(ctx context.Context, arg CreateMaterialDefectParams) (MaterialDefect, error) {
	row := q.db.QueryRow(ctx, createMaterialDefect, arg.Amount, arg.MaterialLocationID)
	var i MaterialDefect
	err := row.Scan(&i.ID, &i.Amount, &i.MaterialLocationID)
	return i, err
}

const deleteInvoiceReturn = `-- name: DeleteInvoiceReturn :exec
DELETE FROM invoice_returns WHERE id = $1
`

func (q *Queries) DeleteInvoiceReturn(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceReturn, id)
	return err
}

const getInvoiceReturn = `-- name: GetInvoiceReturn :one
SELECT id, project_id, district_id, returner_type, returner_id,
       acceptor_type, acceptor_id, accepted_by_worker_id, date_of_invoice,
       notes, delivery_code, confirmation
FROM invoice_returns
WHERE id = $1
`

func (q *Queries) GetInvoiceReturn(ctx context.Context, id int64) (InvoiceReturn, error) {
	row := q.db.QueryRow(ctx, getInvoiceReturn, id)
	var i InvoiceReturn
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DistrictID,
		&i.ReturnerType,
		&i.ReturnerID,
		&i.AcceptorType,
		&i.AcceptorID,
		&i.AcceptedByWorkerID,
		&i.DateOfInvoice,
		&i.Notes,
		&i.DeliveryCode,
		&i.Confirmation,
	)
	return i, err
}

const getInvoiceReturnByDeliveryCode = `-- name: GetInvoiceReturnByDeliveryCode :one
SELECT id, project_id, district_id, returner_type, returner_id,
       acceptor_type, acceptor_id, accepted_by_worker_id, date_of_invoice,
       notes, delivery_code, confirmation
FROM invoice_returns
WHERE delivery_code = $1
  AND project_id = $2
LIMIT 1
`

type GetInvoiceReturnByDeliveryCodeParams struct {
	DeliveryCode pgtype.Text `json:"delivery_code"`
	ProjectID    pgtype.Int8 `json:"project_id"`
}

func (q *Queries) GetInvoiceReturnByDeliveryCode(ctx context.Context, arg GetInvoiceReturnByDeliveryCodeParams) (InvoiceReturn, error) {
	row := q.db.QueryRow(ctx, getInvoiceReturnByDeliveryCode, arg.DeliveryCode, arg.ProjectID)
	var i InvoiceReturn
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DistrictID,
		&i.ReturnerType,
		&i.ReturnerID,
		&i.AcceptorType,
		&i.AcceptorID,
		&i.AcceptedByWorkerID,
		&i.DateOfInvoice,
		&i.Notes,
		&i.DeliveryCode,
		&i.Confirmation,
	)
	return i, err
}

const getMaterialDefectByMaterialLocationID = `-- name: GetMaterialDefectByMaterialLocationID :one
SELECT id, amount, material_location_id
FROM material_defects
WHERE material_location_id = $1
LIMIT 1
`

func (q *Queries) GetMaterialDefectByMaterialLocationID(ctx context.Context, materialLocationID pgtype.Int8) (MaterialDefect, error) {
	row := q.db.QueryRow(ctx, getMaterialDefectByMaterialLocationID, materialLocationID)
	var i MaterialDefect
	err := row.Scan(&i.ID, &i.Amount, &i.MaterialLocationID)
	return i, err
}

const listInvoiceReturnMaterialsForEdit = `-- name: ListInvoiceReturnMaterialsForEdit :many
SELECT
    materials.id                                            AS material_id,
    COALESCE(materials.name, '')::text                      AS material_name,
    COALESCE(materials.unit, '')::text                      AS unit,
    COALESCE(invoice_materials.amount, 0)::numeric          AS amount,
    COALESCE(invoice_materials.notes, '')::text             AS notes,
    COALESCE(materials.has_serial_number, false)::boolean   AS has_serial_number,
    COALESCE(invoice_materials.is_defected, false)::boolean AS is_defective,
    COALESCE(material_locations.amount, 0)::numeric         AS holder_amount
FROM invoice_materials
INNER JOIN material_costs ON invoice_materials.material_cost_id = material_costs.id
INNER JOIN materials ON material_costs.material_id = materials.id
INNER JOIN material_locations ON material_locations.material_cost_id = invoice_materials.material_cost_id
WHERE
    invoice_materials.invoice_type = 'return'
    AND invoice_materials.invoice_id = $1
    AND material_locations.location_type = $2
    AND material_locations.location_id = $3
    AND invoice_materials.project_id = $4
ORDER BY materials.id
`

type ListInvoiceReturnMaterialsForEditParams struct {
	InvoiceID    pgtype.Int8 `json:"invoice_id"`
	LocationType pgtype.Text `json:"location_type"`
	LocationID   pgtype.Int8 `json:"location_id"`
	ProjectID    pgtype.Int8 `json:"project_id"`
}

type ListInvoiceReturnMaterialsForEditRow struct {
	MaterialID      int64          `json:"material_id"`
	MaterialName    string         `json:"material_name"`
	Unit            string         `json:"unit"`
	Amount          pgtype.Numeric `json:"amount"`
	Notes           string         `json:"notes"`
	HasSerialNumber bool           `json:"has_serial_number"`
	IsDefective     bool           `json:"is_defective"`
	HolderAmount    pgtype.Numeric `json:"holder_amount"`
}

func (q *Queries) ListInvoiceReturnMaterialsForEdit(ctx context.Context, arg ListInvoiceReturnMaterialsForEditParams) ([]ListInvoiceReturnMaterialsForEditRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceReturnMaterialsForEdit,
		arg.InvoiceID,
		arg.LocationType,
		arg.LocationID,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceReturnMaterialsForEditRow{}
	for rows.Next() {
		var i ListInvoiceReturnMaterialsForEditRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialName,
			&i.Unit,
			&i.Amount,
			&i.Notes,
			&i.HasSerialNumber,
			&i.IsDefective,
			&i.HolderAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceReturnReportData = `-- name: ListInvoiceReturnReportData :many
SELECT id, project_id, district_id, returner_type, returner_id,
       acceptor_type, acceptor_id, accepted_by_worker_id, date_of_invoice,
       notes, delivery_code, confirmation
FROM invoice_returns
WHERE
    project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR delivery_code = $2)
    AND (NULLIF($3::text, '') IS NULL OR returner_type = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR returner_id = $4)
    AND (NULLIF($5::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR $5 <= date_of_invoice)
    AND (NULLIF($6::timestamptz, '0001-01-01 00:00:00 UTC') IS NULL OR date_of_invoice <= $6)
ORDER BY id DESC
`

type ListInvoiceReturnReportDataParams struct {
	ProjectID pgtype.Int8        `json:"project_id"`
	Column2   string             `json:"column_2"`
	Column3   string             `json:"column_3"`
	Column4   int64              `json:"column_4"`
	Column5   pgtype.Timestamptz `json:"column_5"`
	Column6   pgtype.Timestamptz `json:"column_6"`
}

func (q *Queries) ListInvoiceReturnReportData(ctx context.Context, arg ListInvoiceReturnReportDataParams) ([]InvoiceReturn, error) {
	rows, err := q.db.Query(ctx, listInvoiceReturnReportData,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceReturn{}
	for rows.Next() {
		var i InvoiceReturn
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DistrictID,
			&i.ReturnerType,
			&i.ReturnerID,
			&i.AcceptorType,
			&i.AcceptorID,
			&i.AcceptedByWorkerID,
			&i.DateOfInvoice,
			&i.Notes,
			&i.DeliveryCode,
			&i.Confirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceReturnUniqueCodes = `-- name: ListInvoiceReturnUniqueCodes :many
SELECT DISTINCT(COALESCE(delivery_code, '')::text)
FROM invoice_returns
WHERE project_id = $1
`

func (q *Queries) ListInvoiceReturnUniqueCodes(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listInvoiceReturnUniqueCodes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceReturnUniqueObjects = `-- name: ListInvoiceReturnUniqueObjects :many
SELECT DISTINCT(COALESCE(returner_id, 0)::bigint)
FROM invoice_returns
WHERE returner_type = 'objects' AND project_id = $1 AND returner_id IS NOT NULL
`

func (q *Queries) ListInvoiceReturnUniqueObjects(ctx context.Context, projectID pgtype.Int8) ([]int64, error) {
	rows, err := q.db.Query(ctx, listInvoiceReturnUniqueObjects, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var column_1 int64
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceReturnUniqueTeams = `-- name: ListInvoiceReturnUniqueTeams :many
SELECT DISTINCT(COALESCE(returner_id, 0)::bigint)
FROM invoice_returns
WHERE returner_type = 'teams' AND project_id = $1 AND returner_id IS NOT NULL
`

func (q *Queries) ListInvoiceReturnUniqueTeams(ctx context.Context, projectID pgtype.Int8) ([]int64, error) {
	rows, err := q.db.Query(ctx, listInvoiceReturnUniqueTeams, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var column_1 int64
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceReturns = `-- name: ListInvoiceReturns :many
SELECT id, project_id, district_id, returner_type, returner_id,
       acceptor_type, acceptor_id, accepted_by_worker_id, date_of_invoice,
       notes, delivery_code, confirmation
FROM invoice_returns
ORDER BY id DESC
`

func (q *Queries) ListInvoiceReturns(ctx context.Context) ([]InvoiceReturn, error) {
	rows, err := q.db.Query(ctx, listInvoiceReturns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceReturn{}
	for rows.Next() {
		var i InvoiceReturn
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DistrictID,
			&i.ReturnerType,
			&i.ReturnerID,
			&i.AcceptorType,
			&i.AcceptorID,
			&i.AcceptedByWorkerID,
			&i.DateOfInvoice,
			&i.Notes,
			&i.DeliveryCode,
			&i.Confirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceReturnsPaginatedObject = `-- name: ListInvoiceReturnsPaginatedObject :many
SELECT
    invoice_returns.id                                  AS id,
    COALESCE(invoice_returns.delivery_code, '')::text   AS delivery_code,
    COALESCE(districts.name, '')::text                  AS district_name,
    COALESCE(objects.name, '')::text                    AS object_name,
    COALESCE(objects.type, '')::text                    AS object_type,
    COALESCE(workers.name, '')::text                    AS object_supervisor_name,
    COALESCE(teams.number, '')::text                    AS team_number,
    COALESCE(leader.name, '')::text                     AS team_leader_name,
    COALESCE(acceptor_worker.name, '')::text            AS acceptor_name,
    invoice_returns.date_of_invoice                     AS date_of_invoice,
    COALESCE(invoice_returns.confirmation, false)::boolean AS confirmation
FROM invoice_returns
INNER JOIN districts ON districts.id = invoice_returns.district_id
INNER JOIN objects ON objects.id = invoice_returns.returner_id
INNER JOIN object_supervisors ON objects.id = object_supervisors.object_id
INNER JOIN workers ON workers.id = object_supervisors.supervisor_worker_id
INNER JOIN teams ON teams.id = invoice_returns.acceptor_id
INNER JOIN team_leaders ON team_leaders.team_id = teams.id
INNER JOIN workers AS leader ON leader.id = team_leaders.leader_worker_id
INNER JOIN workers AS acceptor_worker ON acceptor_worker.id = invoice_returns.accepted_by_worker_id
WHERE
    invoice_returns.project_id = $1
    AND invoice_returns.returner_type = 'object'
ORDER BY invoice_returns.id DESC
LIMIT $2 OFFSET $3
`

type ListInvoiceReturnsPaginatedObjectParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListInvoiceReturnsPaginatedObjectRow struct {
	ID                   int64              `json:"id"`
	DeliveryCode         string             `json:"delivery_code"`
	DistrictName         string             `json:"district_name"`
	ObjectName           string             `json:"object_name"`
	ObjectType           string             `json:"object_type"`
	ObjectSupervisorName string             `json:"object_supervisor_name"`
	TeamNumber           string             `json:"team_number"`
	TeamLeaderName       string             `json:"team_leader_name"`
	AcceptorName         string             `json:"acceptor_name"`
	DateOfInvoice        pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmation         bool               `json:"confirmation"`
}

func (q *Queries) ListInvoiceReturnsPaginatedObject(ctx context.Context, arg ListInvoiceReturnsPaginatedObjectParams) ([]ListInvoiceReturnsPaginatedObjectRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceReturnsPaginatedObject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceReturnsPaginatedObjectRow{}
	for rows.Next() {
		var i ListInvoiceReturnsPaginatedObjectRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryCode,
			&i.DistrictName,
			&i.ObjectName,
			&i.ObjectType,
			&i.ObjectSupervisorName,
			&i.TeamNumber,
			&i.TeamLeaderName,
			&i.AcceptorName,
			&i.DateOfInvoice,
			&i.Confirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceReturnsPaginatedTeam = `-- name: ListInvoiceReturnsPaginatedTeam :many
SELECT
    invoice_returns.id                                  AS id,
    COALESCE(invoice_returns.delivery_code, '')::text   AS delivery_code,
    COALESCE(districts.name, '')::text                  AS district_name,
    COALESCE(teams.number, '')::text                    AS team_number,
    COALESCE(workers.name, '')::text                    AS team_leader_name,
    COALESCE(acceptor_worker.name, '')::text            AS acceptor_name,
    invoice_returns.date_of_invoice                     AS date_of_invoice,
    COALESCE(invoice_returns.confirmation, false)::boolean AS confirmation
FROM invoice_returns
INNER JOIN districts ON districts.id = invoice_returns.district_id
INNER JOIN teams ON teams.id = invoice_returns.returner_id
INNER JOIN team_leaders ON team_leaders.team_id = teams.id
INNER JOIN workers ON workers.id = team_leaders.leader_worker_id
INNER JOIN workers AS acceptor_worker ON acceptor_worker.id = invoice_returns.accepted_by_worker_id
WHERE
    invoice_returns.project_id = $1
    AND invoice_returns.returner_type = 'team'
ORDER BY invoice_returns.id DESC
LIMIT $2 OFFSET $3
`

type ListInvoiceReturnsPaginatedTeamParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListInvoiceReturnsPaginatedTeamRow struct {
	ID             int64              `json:"id"`
	DeliveryCode   string             `json:"delivery_code"`
	DistrictName   string             `json:"district_name"`
	TeamNumber     string             `json:"team_number"`
	TeamLeaderName string             `json:"team_leader_name"`
	AcceptorName   string             `json:"acceptor_name"`
	DateOfInvoice  pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmation   bool               `json:"confirmation"`
}

func (q *Queries) ListInvoiceReturnsPaginatedTeam(ctx context.Context, arg ListInvoiceReturnsPaginatedTeamParams) ([]ListInvoiceReturnsPaginatedTeamRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceReturnsPaginatedTeam, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceReturnsPaginatedTeamRow{}
	for rows.Next() {
		var i ListInvoiceReturnsPaginatedTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryCode,
			&i.DistrictName,
			&i.TeamNumber,
			&i.TeamLeaderName,
			&i.AcceptorName,
			&i.DateOfInvoice,
			&i.Confirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialAmountReverseSortedByCostM19InLocation = `-- name: ListMaterialAmountReverseSortedByCostM19InLocation :many
SELECT
    materials.id                                            AS material_id,
    material_costs.id                                       AS material_cost_id,
    COALESCE(material_costs.cost_m19, 0)::numeric           AS material_cost_m19,
    COALESCE(material_locations.amount, 0)::numeric         AS material_amount
FROM material_locations
INNER JOIN material_costs ON material_costs.id = material_locations.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    material_locations.project_id = $1
    AND material_locations.location_type = $2
    AND material_locations.location_id = $3
    AND materials.id = $4
    AND material_locations.amount > 0
ORDER BY material_costs.cost_m19
`

type ListMaterialAmountReverseSortedByCostM19InLocationParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	LocationType pgtype.Text `json:"location_type"`
	LocationID   pgtype.Int8 `json:"location_id"`
	ID           int64       `json:"id"`
}

type ListMaterialAmountReverseSortedByCostM19InLocationRow struct {
	MaterialID      int64          `json:"material_id"`
	MaterialCostID  int64          `json:"material_cost_id"`
	MaterialCostM19 pgtype.Numeric `json:"material_cost_m19"`
	MaterialAmount  pgtype.Numeric `json:"material_amount"`
}

// The Asc-by-cost variant used by invoice_return Create/Update (returner
// gives back the lowest-cost material first).
func (q *Queries) ListMaterialAmountReverseSortedByCostM19InLocation(ctx context.Context, arg ListMaterialAmountReverseSortedByCostM19InLocationParams) ([]ListMaterialAmountReverseSortedByCostM19InLocationRow, error) {
	rows, err := q.db.Query(ctx, listMaterialAmountReverseSortedByCostM19InLocation,
		arg.ProjectID,
		arg.LocationType,
		arg.LocationID,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialAmountReverseSortedByCostM19InLocationRow{}
	for rows.Next() {
		var i ListMaterialAmountReverseSortedByCostM19InLocationRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialCostID,
			&i.MaterialCostM19,
			&i.MaterialAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceReturn = `-- name: UpdateInvoiceReturn :one
UPDATE invoice_returns
SET project_id = $2, district_id = $3, returner_type = $4, returner_id = $5,
    acceptor_type = $6, acceptor_id = $7, accepted_by_worker_id = $8,
    date_of_invoice = $9, notes = $10, delivery_code = $11, confirmation = $12
WHERE id = $1
RETURNING id, project_id, district_id, returner_type, returner_id,
          acceptor_type, acceptor_id, accepted_by_worker_id, date_of_invoice,
          notes, delivery_code, confirmation
`

type UpdateInvoiceReturnParams struct {
	ID                 int64              `json:"id"`
	ProjectID          pgtype.Int8        `json:"project_id"`
	DistrictID         pgtype.Int8        `json:"district_id"`
	ReturnerType       pgtype.Text        `json:"returner_type"`
	ReturnerID         pgtype.Int8        `json:"returner_id"`
	AcceptorType       pgtype.Text        `json:"acceptor_type"`
	AcceptorID         pgtype.Int8        `json:"acceptor_id"`
	AcceptedByWorkerID pgtype.Int8        `json:"accepted_by_worker_id"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
	Notes              pgtype.Text        `json:"notes"`
	DeliveryCode       pgtype.Text        `json:"delivery_code"`
	Confirmation       pgtype.Bool        `json:"confirmation"`
}

func (q *Queries) UpdateInvoiceReturn(ctx context.Context, arg UpdateInvoiceReturnParams) (InvoiceReturn, error) {
	row := q.db.QueryRow(ctx, updateInvoiceReturn,
		arg.ID,
		arg.ProjectID,
		arg.DistrictID,
		arg.ReturnerType,
		arg.ReturnerID,
		arg.AcceptorType,
		arg.AcceptorID,
		arg.AcceptedByWorkerID,
		arg.DateOfInvoice,
		arg.Notes,
		arg.DeliveryCode,
		arg.Confirmation,
	)
	var i InvoiceReturn
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DistrictID,
		&i.ReturnerType,
		&i.ReturnerID,
		&i.AcceptorType,
		&i.AcceptorID,
		&i.AcceptedByWorkerID,
		&i.DateOfInvoice,
		&i.Notes,
		&i.DeliveryCode,
		&i.Confirmation,
	)
	return i, err
}

const upsertMaterialDefectByID = `-- name: UpsertMaterialDefectByID :exec
UPDATE material_defects
SET amount = $1::numeric,
    material_location_id = $2::bigint
WHERE id = $3
`

type UpsertMaterialDefectByIDParams struct {
	Amount             pgtype.Numeric `json:"amount"`
	MaterialLocationID int64          `json:"material_location_id"`
	ID                 int64          `json:"id"`
}

func (q *Queries) UpsertMaterialDefectByID(ctx context.Context, arg UpsertMaterialDefectByIDParams) error {
	_, err := q.db.Exec(ctx, upsertMaterialDefectByID, arg.Amount, arg.MaterialLocationID, arg.ID)
	return err
}
