// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_object.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoiceObjectsByProject = `-- name: CountInvoiceObjectsByProject :one
SELECT COUNT(*)::bigint FROM invoice_objects WHERE project_id = $1
`

func (q *Queries) CountInvoiceObjectsByProject(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceObjectsByProject, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvoiceObject = `-- name: CreateInvoiceObject :one
INSERT INTO invoice_objects (
    district_id, delivery_code, project_id, supervisor_worker_id,
    object_id, team_id, date_of_invoice, confirmed_by_operator,
    date_of_correction
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, district_id, delivery_code, project_id, supervisor_worker_id,
          object_id, team_id, date_of_invoice, confirmed_by_operator,
          date_of_correction
`

type CreateInvoiceObjectParams struct {
	DistrictID          pgtype.Int8        `json:"district_id"`
	DeliveryCode        pgtype.Text        `json:"delivery_code"`
	ProjectID           pgtype.Int8        `json:"project_id"`
	SupervisorWorkerID  pgtype.Int8        `json:"supervisor_worker_id"`
	ObjectID            pgtype.Int8        `json:"object_id"`
	TeamID              pgtype.Int8        `json:"team_id"`
	DateOfInvoice       pgtype.Timestamptz `json:"date_of_invoice"`
	ConfirmedByOperator pgtype.Bool        `json:"confirmed_by_operator"`
	DateOfCorrection    pgtype.Timestamptz `json:"date_of_correction"`
}

func (q *Queries) CreateInvoiceObject(ctx context.Context, arg CreateInvoiceObjectParams) (InvoiceObject, error) {
	row := q.db.QueryRow(ctx, createInvoiceObject,
		arg.DistrictID,
		arg.DeliveryCode,
		arg.ProjectID,
		arg.SupervisorWorkerID,
		arg.ObjectID,
		arg.TeamID,
		arg.DateOfInvoice,
		arg.ConfirmedByOperator,
		arg.DateOfCorrection,
	)
	var i InvoiceObject
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.DeliveryCode,
		&i.ProjectID,
		&i.SupervisorWorkerID,
		&i.ObjectID,
		&i.TeamID,
		&i.DateOfInvoice,
		&i.ConfirmedByOperator,
		&i.DateOfCorrection,
	)
	return i, err
}

type CreateInvoiceOperationsBatchParams struct {
	ProjectID   pgtype.Int8    `json:"project_id"`
	OperationID pgtype.Int8    `json:"operation_id"`
	InvoiceID   pgtype.Int8    `json:"invoice_id"`
	InvoiceType pgtype.Text    `json:"invoice_type"`
	Amount      pgtype.Numeric `json:"amount"`
	Notes       pgtype.Text    `json:"notes"`
}

const deleteInvoiceObject = `-- name: DeleteInvoiceObject :exec
DELETE FROM invoice_objects WHERE id = $1
`

func (q *Queries) DeleteInvoiceObject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvoiceObject, id)
	return err
}

const getInvoiceObject = `-- name: GetInvoiceObject :one
SELECT id, district_id, delivery_code, project_id, supervisor_worker_id,
       object_id, team_id, date_of_invoice, confirmed_by_operator,
       date_of_correction
FROM invoice_objects
WHERE id = $1
`

func (q *Queries) GetInvoiceObject(ctx context.Context, id int64) (InvoiceObject, error) {
	row := q.db.QueryRow(ctx, getInvoiceObject, id)
	var i InvoiceObject
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.DeliveryCode,
		&i.ProjectID,
		&i.SupervisorWorkerID,
		&i.ObjectID,
		&i.TeamID,
		&i.DateOfInvoice,
		&i.ConfirmedByOperator,
		&i.DateOfCorrection,
	)
	return i, err
}

const getInvoiceObjectDescriptiveDataByID = `-- name: GetInvoiceObjectDescriptiveDataByID :one
SELECT
    invoice_objects.id                                          AS id,
    COALESCE(workers.name, '')::text                            AS supervisor_name,
    invoice_objects.district_id                                 AS district_id,
    COALESCE(districts.name, '')::text                          AS district_name,
    COALESCE(objects.name, '')::text                            AS object_name,
    COALESCE(objects.type, '')::text                            AS object_type,
    COALESCE(teams.number, '')::text                            AS team_number,
    invoice_objects.date_of_invoice                             AS date_of_invoice,
    COALESCE(invoice_objects.delivery_code, '')::text           AS delivery_code,
    COALESCE(invoice_objects.confirmed_by_operator, false)::boolean AS confirmed_by_operator
FROM invoice_objects
INNER JOIN workers ON workers.id = invoice_objects.supervisor_worker_id
LEFT JOIN districts ON districts.id = invoice_objects.district_id
INNER JOIN objects ON objects.id = invoice_objects.object_id
INNER JOIN teams ON teams.id = invoice_objects.team_id
WHERE invoice_objects.id = $1
  AND invoice_objects.project_id = $2
`

type GetInvoiceObjectDescriptiveDataByIDParams struct {
	ID        int64       `json:"id"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

type GetInvoiceObjectDescriptiveDataByIDRow struct {
	ID                  int64              `json:"id"`
	SupervisorName      string             `json:"supervisor_name"`
	DistrictID          pgtype.Int8        `json:"district_id"`
	DistrictName        string             `json:"district_name"`
	ObjectName          string             `json:"object_name"`
	ObjectType          string             `json:"object_type"`
	TeamNumber          string             `json:"team_number"`
	DateOfInvoice       pgtype.Timestamptz `json:"date_of_invoice"`
	DeliveryCode        string             `json:"delivery_code"`
	ConfirmedByOperator bool               `json:"confirmed_by_operator"`
}

func (q *Queries) GetInvoiceObjectDescriptiveDataByID(ctx context.Context, arg GetInvoiceObjectDescriptiveDataByIDParams) (GetInvoiceObjectDescriptiveDataByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceObjectDescriptiveDataByID, arg.ID, arg.ProjectID)
	var i GetInvoiceObjectDescriptiveDataByIDRow
	err := row.Scan(
		&i.ID,
		&i.SupervisorName,
		&i.DistrictID,
		&i.DistrictName,
		&i.ObjectName,
		&i.ObjectType,
		&i.TeamNumber,
		&i.DateOfInvoice,
		&i.DeliveryCode,
		&i.ConfirmedByOperator,
	)
	return i, err
}

const listInvoiceObjectOperationsBasedOnMaterialsInTeam = `-- name: ListInvoiceObjectOperationsBasedOnMaterialsInTeam :many
SELECT
    operations.id                                                AS id,
    operations.project_id                                        AS project_id,
    COALESCE(operations.name, '')::text                          AS name,
    COALESCE(operations.code, '')::text                          AS code,
    operations.cost_prime                                        AS cost_prime,
    operations.cost_with_customer                                AS cost_with_customer
FROM operations
INNER JOIN operation_materials ON operation_materials.operation_id = operations.id
WHERE operation_materials.material_id IN (
    SELECT materials.id
    FROM material_locations
    INNER JOIN material_costs ON material_locations.material_cost_id = material_costs.id
    INNER JOIN materials ON material_costs.material_id = materials.id
    WHERE
        material_locations.location_type = 'team'
        AND material_locations.location_id = $1
)
`

type ListInvoiceObjectOperationsBasedOnMaterialsInTeamRow struct {
	ID               int64          `json:"id"`
	ProjectID        pgtype.Int8    `json:"project_id"`
	Name             string         `json:"name"`
	Code             string         `json:"code"`
	CostPrime        pgtype.Numeric `json:"cost_prime"`
	CostWithCustomer pgtype.Numeric `json:"cost_with_customer"`
}

func (q *Queries) ListInvoiceObjectOperationsBasedOnMaterialsInTeam(ctx context.Context, locationID pgtype.Int8) ([]ListInvoiceObjectOperationsBasedOnMaterialsInTeamRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceObjectOperationsBasedOnMaterialsInTeam, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceObjectOperationsBasedOnMaterialsInTeamRow{}
	for rows.Next() {
		var i ListInvoiceObjectOperationsBasedOnMaterialsInTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Code,
			&i.CostPrime,
			&i.CostWithCustomer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceObjectTeamsByObjectID = `-- name: ListInvoiceObjectTeamsByObjectID :many
SELECT
    teams.id                                AS id,
    teams.project_id                        AS project_id,
    COALESCE(teams.number, '')::text        AS number,
    COALESCE(teams.mobile_number, '')::text AS mobile_number,
    COALESCE(teams.company, '')::text       AS company
FROM object_teams
INNER JOIN teams ON teams.id = object_teams.team_id
WHERE object_teams.object_id = $1
`

type ListInvoiceObjectTeamsByObjectIDRow struct {
	ID           int64       `json:"id"`
	ProjectID    pgtype.Int8 `json:"project_id"`
	Number       string      `json:"number"`
	MobileNumber string      `json:"mobile_number"`
	Company      string      `json:"company"`
}

func (q *Queries) ListInvoiceObjectTeamsByObjectID(ctx context.Context, objectID pgtype.Int8) ([]ListInvoiceObjectTeamsByObjectIDRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceObjectTeamsByObjectID, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceObjectTeamsByObjectIDRow{}
	for rows.Next() {
		var i ListInvoiceObjectTeamsByObjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.MobileNumber,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceObjectsForCorrection = `-- name: ListInvoiceObjectsForCorrection :many
SELECT
    invoice_objects.id                                          AS id,
    COALESCE(workers.name, '')::text                            AS supervisor_name,
    invoice_objects.district_id                                 AS district_id,
    COALESCE(districts.name, '')::text                          AS district_name,
    COALESCE(objects.name, '')::text                            AS object_name,
    teams.id                                                    AS team_id,
    COALESCE(teams.number, '')::text                            AS team_number,
    invoice_objects.date_of_invoice                             AS date_of_invoice,
    COALESCE(invoice_objects.delivery_code, '')::text           AS delivery_code,
    COALESCE(invoice_objects.confirmed_by_operator, false)::boolean AS confirmed_by_operator
FROM invoice_objects
INNER JOIN workers ON workers.id = invoice_objects.supervisor_worker_id
LEFT JOIN districts ON districts.id = invoice_objects.district_id
INNER JOIN objects ON objects.id = invoice_objects.object_id
INNER JOIN teams ON teams.id = invoice_objects.team_id
WHERE
    invoice_objects.project_id = $1
    AND COALESCE(invoice_objects.confirmed_by_operator, false) = false
`

type ListInvoiceObjectsForCorrectionRow struct {
	ID                  int64              `json:"id"`
	SupervisorName      string             `json:"supervisor_name"`
	DistrictID          pgtype.Int8        `json:"district_id"`
	DistrictName        string             `json:"district_name"`
	ObjectName          string             `json:"object_name"`
	TeamID              int64              `json:"team_id"`
	TeamNumber          string             `json:"team_number"`
	DateOfInvoice       pgtype.Timestamptz `json:"date_of_invoice"`
	DeliveryCode        string             `json:"delivery_code"`
	ConfirmedByOperator bool               `json:"confirmed_by_operator"`
}

func (q *Queries) ListInvoiceObjectsForCorrection(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceObjectsForCorrectionRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceObjectsForCorrection, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceObjectsForCorrectionRow{}
	for rows.Next() {
		var i ListInvoiceObjectsForCorrectionRow
		if err := rows.Scan(
			&i.ID,
			&i.SupervisorName,
			&i.DistrictID,
			&i.DistrictName,
			&i.ObjectName,
			&i.TeamID,
			&i.TeamNumber,
			&i.DateOfInvoice,
			&i.DeliveryCode,
			&i.ConfirmedByOperator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceObjectsPaginated = `-- name: ListInvoiceObjectsPaginated :many
SELECT
    invoice_objects.id                                          AS id,
    COALESCE(workers.name, '')::text                            AS supervisor_name,
    invoice_objects.district_id                                 AS district_id,
    COALESCE(districts.name, '')::text                          AS district_name,
    COALESCE(objects.name, '')::text                            AS object_name,
    COALESCE(objects.type, '')::text                            AS object_type,
    COALESCE(teams.number, '')::text                            AS team_number,
    invoice_objects.date_of_invoice                             AS date_of_invoice,
    COALESCE(invoice_objects.delivery_code, '')::text           AS delivery_code,
    COALESCE(invoice_objects.confirmed_by_operator, false)::boolean AS confirmed_by_operator
FROM invoice_objects
INNER JOIN workers ON workers.id = invoice_objects.supervisor_worker_id
LEFT JOIN districts ON districts.id = invoice_objects.district_id
INNER JOIN objects ON objects.id = invoice_objects.object_id
INNER JOIN teams ON teams.id = invoice_objects.team_id
WHERE invoice_objects.project_id = $1
ORDER BY invoice_objects.id DESC
LIMIT $2 OFFSET $3
`

type ListInvoiceObjectsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListInvoiceObjectsPaginatedRow struct {
	ID                  int64              `json:"id"`
	SupervisorName      string             `json:"supervisor_name"`
	DistrictID          pgtype.Int8        `json:"district_id"`
	DistrictName        string             `json:"district_name"`
	ObjectName          string             `json:"object_name"`
	ObjectType          string             `json:"object_type"`
	TeamNumber          string             `json:"team_number"`
	DateOfInvoice       pgtype.Timestamptz `json:"date_of_invoice"`
	DeliveryCode        string             `json:"delivery_code"`
	ConfirmedByOperator bool               `json:"confirmed_by_operator"`
}

func (q *Queries) ListInvoiceObjectsPaginated(ctx context.Context, arg ListInvoiceObjectsPaginatedParams) ([]ListInvoiceObjectsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceObjectsPaginated, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceObjectsPaginatedRow{}
	for rows.Next() {
		var i ListInvoiceObjectsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.SupervisorName,
			&i.DistrictID,
			&i.DistrictName,
			&i.ObjectName,
			&i.ObjectType,
			&i.TeamNumber,
			&i.DateOfInvoice,
			&i.DeliveryCode,
			&i.ConfirmedByOperator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
