// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kl04kv_object.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countKL04KVObjectsFiltered = `-- name: CountKL04KVObjectsFiltered :one
SELECT COUNT(*)::bigint
FROM (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN kl04_kv_objects ON kl04_kv_objects.id = objects.object_detailed_id
    FULL JOIN object_teams ON object_teams.object_id = objects.id
    FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
    FULL JOIN tp_nourashes_objects ON tp_nourashes_objects.target_id = objects.id
    WHERE
        objects.type = 'kl04kv_objects'
        AND objects.project_id = $1
        AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
        AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
        AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
        AND (NULLIF($5::bigint, 0) IS NULL OR tp_nourashes_objects.tp_object_id = $5)
) sub
`

type CountKL04KVObjectsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Column5   int64       `json:"column_5"`
}

func (q *Queries) CountKL04KVObjectsFiltered(ctx context.Context, arg CountKL04KVObjectsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKL04KVObjectsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createKL04KVObjectDetail = `-- name: CreateKL04KVObjectDetail :one
INSERT INTO kl04_kv_objects (length, nourashes)
VALUES ($1, $2)
RETURNING id, length, nourashes
`

type CreateKL04KVObjectDetailParams struct {
	Length    pgtype.Numeric `json:"length"`
	Nourashes pgtype.Text    `json:"nourashes"`
}

func (q *Queries) CreateKL04KVObjectDetail(ctx context.Context, arg CreateKL04KVObjectDetailParams) (Kl04KvObject, error) {
	row := q.db.QueryRow(ctx, createKL04KVObjectDetail, arg.Length, arg.Nourashes)
	var i Kl04KvObject
	err := row.Scan(&i.ID, &i.Length, &i.Nourashes)
	return i, err
}

const deleteKL04KVObjectDetail = `-- name: DeleteKL04KVObjectDetail :exec
DELETE FROM kl04_kv_objects WHERE id = $1
`

func (q *Queries) DeleteKL04KVObjectDetail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteKL04KVObjectDetail, id)
	return err
}

const deleteKL04KVObjectSupervisorsCascade = `-- name: DeleteKL04KVObjectSupervisorsCascade :exec
DELETE FROM object_supervisors
WHERE object_supervisors.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN kl04_kv_objects ON kl04_kv_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND kl04_kv_objects.id = $2
        AND objects.type = 'kl04kv_objects'
)
`

type DeleteKL04KVObjectSupervisorsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteKL04KVObjectSupervisorsCascade(ctx context.Context, arg DeleteKL04KVObjectSupervisorsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteKL04KVObjectSupervisorsCascade, arg.ProjectID, arg.ID)
	return err
}

const deleteKL04KVObjectTPNourashesCascade = `-- name: DeleteKL04KVObjectTPNourashesCascade :exec
DELETE FROM tp_nourashes_objects
WHERE tp_nourashes_objects.target_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN kl04_kv_objects ON kl04_kv_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND kl04_kv_objects.id = $2
        AND objects.type = 'kl04kv_objects'
)
`

type DeleteKL04KVObjectTPNourashesCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteKL04KVObjectTPNourashesCascade(ctx context.Context, arg DeleteKL04KVObjectTPNourashesCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteKL04KVObjectTPNourashesCascade, arg.ProjectID, arg.ID)
	return err
}

const deleteKL04KVObjectTeamsCascade = `-- name: DeleteKL04KVObjectTeamsCascade :exec
DELETE FROM object_teams
WHERE object_teams.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN kl04_kv_objects ON kl04_kv_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND kl04_kv_objects.id = $2
        AND objects.type = 'kl04kv_objects'
)
`

type DeleteKL04KVObjectTeamsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteKL04KVObjectTeamsCascade(ctx context.Context, arg DeleteKL04KVObjectTeamsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteKL04KVObjectTeamsCascade, arg.ProjectID, arg.ID)
	return err
}

const deleteObjectByKL04KVDetailedID = `-- name: DeleteObjectByKL04KVDetailedID :exec
DELETE FROM objects
WHERE object_detailed_id = $1 AND type = 'kl04kv_objects'
`

func (q *Queries) DeleteObjectByKL04KVDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteObjectByKL04KVDetailedID, objectDetailedID)
	return err
}

const getKL04KVObjectDetail = `-- name: GetKL04KVObjectDetail :one
SELECT id, length, nourashes
FROM kl04_kv_objects
WHERE id = $1
`

func (q *Queries) GetKL04KVObjectDetail(ctx context.Context, id int64) (Kl04KvObject, error) {
	row := q.db.QueryRow(ctx, getKL04KVObjectDetail, id)
	var i Kl04KvObject
	err := row.Scan(&i.ID, &i.Length, &i.Nourashes)
	return i, err
}

const listKL04KVObjectNamesForSearch = `-- name: ListKL04KVObjectNamesForSearch :many
SELECT
    COALESCE(objects.name, '')::text AS label,
    COALESCE(objects.name, '')::text AS value
FROM objects
INNER JOIN kl04_kv_objects ON kl04_kv_objects.id = objects.object_detailed_id
WHERE
    objects.project_id = $1
    AND objects.type = 'kl04kv_objects'
`

type ListKL04KVObjectNamesForSearchRow struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

func (q *Queries) ListKL04KVObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListKL04KVObjectNamesForSearchRow, error) {
	rows, err := q.db.Query(ctx, listKL04KVObjectNamesForSearch, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKL04KVObjectNamesForSearchRow{}
	for rows.Next() {
		var i ListKL04KVObjectNamesForSearchRow
		if err := rows.Scan(&i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKL04KVObjectsPaginated = `-- name: ListKL04KVObjectsPaginated :many
SELECT DISTINCT
    objects.id                                   AS object_id,
    kl04_kv_objects.id                           AS object_detailed_id,
    COALESCE(objects.name, '')::text             AS name,
    COALESCE(objects.status, '')::text           AS status,
    kl04_kv_objects.length                       AS length,
    COALESCE(kl04_kv_objects.nourashes, '')::text AS nourashes
FROM objects
INNER JOIN kl04_kv_objects ON kl04_kv_objects.id = objects.object_detailed_id
FULL JOIN object_teams ON object_teams.object_id = objects.id
FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
FULL JOIN tp_nourashes_objects ON tp_nourashes_objects.target_id = objects.id
WHERE
    objects.type = 'kl04kv_objects'
    AND objects.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
    AND (NULLIF($5::bigint, 0) IS NULL OR tp_nourashes_objects.tp_object_id = $5)
ORDER BY kl04_kv_objects.id DESC
LIMIT $6 OFFSET $7
`

type ListKL04KVObjectsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Column5   int64       `json:"column_5"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListKL04KVObjectsPaginatedRow struct {
	ObjectID         int64          `json:"object_id"`
	ObjectDetailedID int64          `json:"object_detailed_id"`
	Name             string         `json:"name"`
	Status           string         `json:"status"`
	Length           pgtype.Numeric `json:"length"`
	Nourashes        string         `json:"nourashes"`
}

func (q *Queries) ListKL04KVObjectsPaginated(ctx context.Context, arg ListKL04KVObjectsPaginatedParams) ([]ListKL04KVObjectsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listKL04KVObjectsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKL04KVObjectsPaginatedRow{}
	for rows.Next() {
		var i ListKL04KVObjectsPaginatedRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.ObjectDetailedID,
			&i.Name,
			&i.Status,
			&i.Length,
			&i.Nourashes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKL04KVObjectDetail = `-- name: UpdateKL04KVObjectDetail :exec
UPDATE kl04_kv_objects
SET length = $2, nourashes = $3
WHERE id = $1
`

type UpdateKL04KVObjectDetailParams struct {
	ID        int64          `json:"id"`
	Length    pgtype.Numeric `json:"length"`
	Nourashes pgtype.Text    `json:"nourashes"`
}

func (q *Queries) UpdateKL04KVObjectDetail(ctx context.Context, arg UpdateKL04KVObjectDetailParams) error {
	_, err := q.db.Exec(ctx, updateKL04KVObjectDetail, arg.ID, arg.Length, arg.Nourashes)
	return err
}
