// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: main_report.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const invoiceMaterialDataForProgressReport = `-- name: InvoiceMaterialDataForProgressReport :many
SELECT
    materials.id                            AS material_id,
    COALESCE(invoice_materials.amount, 0)::float8 AS amount,
    COALESCE(invoice_materials.invoice_type, '')::text AS invoice_type,
    material_costs.cost_with_customer       AS cost_with_customer
FROM materials
INNER JOIN material_costs ON material_costs.material_id = materials.id
RIGHT JOIN invoice_materials ON invoice_materials.material_cost_id = material_costs.id
WHERE
    materials.project_id = $1
    AND materials.show_planned_amount_in_report = true
    AND (invoice_materials.invoice_type = 'input' OR invoice_materials.invoice_type = 'object-correction')
ORDER BY materials.id
`

type InvoiceMaterialDataForProgressReportRow struct {
	MaterialID       int64          `json:"material_id"`
	Amount           float64        `json:"amount"`
	InvoiceType      string         `json:"invoice_type"`
	CostWithCustomer pgtype.Numeric `json:"cost_with_customer"`
}

func (q *Queries) InvoiceMaterialDataForProgressReport(ctx context.Context, projectID pgtype.Int8) ([]InvoiceMaterialDataForProgressReportRow, error) {
	rows, err := q.db.Query(ctx, invoiceMaterialDataForProgressReport, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceMaterialDataForProgressReportRow{}
	for rows.Next() {
		var i InvoiceMaterialDataForProgressReportRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.Amount,
			&i.InvoiceType,
			&i.CostWithCustomer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invoiceOperationDataForProgressReport = `-- name: InvoiceOperationDataForProgressReport :many
SELECT
    operations.id                                                AS id,
    COALESCE(operations.code, '')::text                          AS code,
    COALESCE(operations.name, '')::text                          AS name,
    operations.cost_with_customer                                AS cost_with_customer,
    COALESCE(operations.planned_amount_for_project, 0)::float8   AS planned_amount_for_project,
    COALESCE(invoice_operations.amount, 0)::float8               AS amount_in_invoice
FROM invoice_objects
INNER JOIN invoice_operations ON invoice_operations.invoice_id = invoice_objects.id
INNER JOIN operations ON operations.id = invoice_operations.operation_id
WHERE
    invoice_objects.confirmed_by_operator = true
    AND invoice_operations.invoice_type = 'object-correction'
    AND operations.project_id = $1
    AND operations.show_planned_amount_in_report = true
ORDER BY operations.id
`

type InvoiceOperationDataForProgressReportRow struct {
	ID                      int64          `json:"id"`
	Code                    string         `json:"code"`
	Name                    string         `json:"name"`
	CostWithCustomer        pgtype.Numeric `json:"cost_with_customer"`
	PlannedAmountForProject float64        `json:"planned_amount_for_project"`
	AmountInInvoice         float64        `json:"amount_in_invoice"`
}

func (q *Queries) InvoiceOperationDataForProgressReport(ctx context.Context, projectID pgtype.Int8) ([]InvoiceOperationDataForProgressReportRow, error) {
	rows, err := q.db.Query(ctx, invoiceOperationDataForProgressReport, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceOperationDataForProgressReportRow{}
	for rows.Next() {
		var i InvoiceOperationDataForProgressReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CostWithCustomer,
			&i.PlannedAmountForProject,
			&i.AmountInInvoice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invoiceOperationDataForProgressReportInGivenDate = `-- name: InvoiceOperationDataForProgressReportInGivenDate :many
SELECT
    COALESCE(operations.code, '')::text                          AS code,
    COALESCE(operations.name, '')::text                          AS name,
    operations.cost_with_customer                                AS cost_with_customer,
    COALESCE(operations.planned_amount_for_project, 0)::float8   AS amount_planned_for_project,
    COALESCE(project_progress_operations.installed, 0)::float8   AS amount_installed
FROM project_progress_operations
INNER JOIN operations ON project_progress_operations.operation_id = operations.id
WHERE
    project_progress_operations.project_id = $1
    AND $2::timestamptz < project_progress_operations.date
    AND project_progress_operations.date < $3::timestamptz
`

type InvoiceOperationDataForProgressReportInGivenDateParams struct {
	ProjectID pgtype.Int8        `json:"project_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
	Column3   pgtype.Timestamptz `json:"column_3"`
}

type InvoiceOperationDataForProgressReportInGivenDateRow struct {
	Code                    string         `json:"code"`
	Name                    string         `json:"name"`
	CostWithCustomer        pgtype.Numeric `json:"cost_with_customer"`
	AmountPlannedForProject float64        `json:"amount_planned_for_project"`
	AmountInstalled         float64        `json:"amount_installed"`
}

func (q *Queries) InvoiceOperationDataForProgressReportInGivenDate(ctx context.Context, arg InvoiceOperationDataForProgressReportInGivenDateParams) ([]InvoiceOperationDataForProgressReportInGivenDateRow, error) {
	rows, err := q.db.Query(ctx, invoiceOperationDataForProgressReportInGivenDate, arg.ProjectID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceOperationDataForProgressReportInGivenDateRow{}
	for rows.Next() {
		var i InvoiceOperationDataForProgressReportInGivenDateRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.CostWithCustomer,
			&i.AmountPlannedForProject,
			&i.AmountInstalled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialDataForProgressReportInProject = `-- name: MaterialDataForProgressReportInProject :many
SELECT
    materials.id                                                       AS id,
    COALESCE(materials.code, '')::text                                 AS code,
    COALESCE(materials.name, '')::text                                 AS name,
    COALESCE(materials.unit, '')::text                                 AS unit,
    COALESCE(materials.planned_amount_for_project, 0)::float8          AS planned_amount_for_project,
    COALESCE(material_locations.amount, 0)::float8                     AS location_amount,
    COALESCE(material_locations.location_type, '')::text               AS location_type
FROM material_locations
INNER JOIN material_costs ON material_locations.material_cost_id = material_costs.id
INNER JOIN materials ON material_costs.material_id = materials.id
WHERE
    materials.project_id = $1
    AND materials.show_planned_amount_in_report = true
ORDER BY materials.id
`

type MaterialDataForProgressReportInProjectRow struct {
	ID                      int64   `json:"id"`
	Code                    string  `json:"code"`
	Name                    string  `json:"name"`
	Unit                    string  `json:"unit"`
	PlannedAmountForProject float64 `json:"planned_amount_for_project"`
	LocationAmount          float64 `json:"location_amount"`
	LocationType            string  `json:"location_type"`
}

func (q *Queries) MaterialDataForProgressReportInProject(ctx context.Context, projectID pgtype.Int8) ([]MaterialDataForProgressReportInProjectRow, error) {
	rows, err := q.db.Query(ctx, materialDataForProgressReportInProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialDataForProgressReportInProjectRow{}
	for rows.Next() {
		var i MaterialDataForProgressReportInProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.PlannedAmountForProject,
			&i.LocationAmount,
			&i.LocationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialDataForProgressReportInProjectInGivenDate = `-- name: MaterialDataForProgressReportInProjectInGivenDate :many
SELECT
    materials.id                                                                          AS id,
    COALESCE(materials.code, '')::text                                                    AS code,
    COALESCE(materials.name, '')::text                                                    AS name,
    COALESCE(materials.unit, '')::text                                                    AS unit,
    COALESCE(materials.planned_amount_for_project, 0)::float8                             AS amount_planned_for_project,
    COALESCE(project_progress_materials.received, 0)::float8                              AS amount_received,
    COALESCE(project_progress_materials.installed, 0)::float8                             AS amount_installed,
    COALESCE(project_progress_materials.amount_in_warehouse, 0)::float8                   AS amount_in_warehouse,
    COALESCE(project_progress_materials.amount_in_teams, 0)::float8                       AS amount_in_teams,
    COALESCE(project_progress_materials.amount_in_objects, 0)::float8                     AS amount_in_objects,
    COALESCE(project_progress_materials.amount_write_off, 0)::float8                      AS amount_write_off,
    material_costs.cost_with_customer                                                     AS cost_with_customer
FROM project_progress_materials
INNER JOIN material_costs ON material_costs.id = project_progress_materials.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    project_progress_materials.project_id = $1
    AND $2::timestamptz < project_progress_materials.date
    AND project_progress_materials.date < $3::timestamptz
ORDER BY materials.id
`

type MaterialDataForProgressReportInProjectInGivenDateParams struct {
	ProjectID pgtype.Int8        `json:"project_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
	Column3   pgtype.Timestamptz `json:"column_3"`
}

type MaterialDataForProgressReportInProjectInGivenDateRow struct {
	ID                      int64          `json:"id"`
	Code                    string         `json:"code"`
	Name                    string         `json:"name"`
	Unit                    string         `json:"unit"`
	AmountPlannedForProject float64        `json:"amount_planned_for_project"`
	AmountReceived          float64        `json:"amount_received"`
	AmountInstalled         float64        `json:"amount_installed"`
	AmountInWarehouse       float64        `json:"amount_in_warehouse"`
	AmountInTeams           float64        `json:"amount_in_teams"`
	AmountInObjects         float64        `json:"amount_in_objects"`
	AmountWriteOff          float64        `json:"amount_write_off"`
	CostWithCustomer        pgtype.Numeric `json:"cost_with_customer"`
}

func (q *Queries) MaterialDataForProgressReportInProjectInGivenDate(ctx context.Context, arg MaterialDataForProgressReportInProjectInGivenDateParams) ([]MaterialDataForProgressReportInProjectInGivenDateRow, error) {
	rows, err := q.db.Query(ctx, materialDataForProgressReportInProjectInGivenDate, arg.ProjectID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialDataForProgressReportInProjectInGivenDateRow{}
	for rows.Next() {
		var i MaterialDataForProgressReportInProjectInGivenDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.AmountPlannedForProject,
			&i.AmountReceived,
			&i.AmountInstalled,
			&i.AmountInWarehouse,
			&i.AmountInTeams,
			&i.AmountInObjects,
			&i.AmountWriteOff,
			&i.CostWithCustomer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialDataForRemainingMaterialAnalysis = `-- name: MaterialDataForRemainingMaterialAnalysis :many
SELECT
    materials.id                                                       AS id,
    COALESCE(materials.code, '')::text                                 AS code,
    COALESCE(materials.name, '')::text                                 AS name,
    COALESCE(materials.unit, '')::text                                 AS unit,
    COALESCE(materials.planned_amount_for_project, 0)::float8          AS planned_amount_for_project,
    COALESCE(material_locations.amount, 0)::float8                     AS location_amount,
    COALESCE(material_locations.location_type, '')::text               AS location_type
FROM material_locations
INNER JOIN material_costs ON material_locations.material_cost_id = material_costs.id
INNER JOIN materials ON material_costs.material_id = materials.id
WHERE
    materials.project_id = $1
    AND materials.show_planned_amount_in_report = true
    AND (material_locations.location_type = 'warehouse' OR material_locations.location_type = 'team')
ORDER BY materials.id
`

type MaterialDataForRemainingMaterialAnalysisRow struct {
	ID                      int64   `json:"id"`
	Code                    string  `json:"code"`
	Name                    string  `json:"name"`
	Unit                    string  `json:"unit"`
	PlannedAmountForProject float64 `json:"planned_amount_for_project"`
	LocationAmount          float64 `json:"location_amount"`
	LocationType            string  `json:"location_type"`
}

func (q *Queries) MaterialDataForRemainingMaterialAnalysis(ctx context.Context, projectID pgtype.Int8) ([]MaterialDataForRemainingMaterialAnalysisRow, error) {
	rows, err := q.db.Query(ctx, materialDataForRemainingMaterialAnalysis, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialDataForRemainingMaterialAnalysisRow{}
	for rows.Next() {
		var i MaterialDataForRemainingMaterialAnalysisRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.PlannedAmountForProject,
			&i.LocationAmount,
			&i.LocationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialsInstalledOnObjectForRemainingMaterialAnalysis = `-- name: MaterialsInstalledOnObjectForRemainingMaterialAnalysis :many
SELECT
    materials.id                                                AS id,
    COALESCE(invoice_materials.amount, 0)::float8               AS amount,
    invoice_objects.date_of_correction                          AS date_of_correction
FROM invoice_objects
INNER JOIN invoice_materials ON invoice_objects.id = invoice_materials.invoice_id
INNER JOIN material_costs ON invoice_materials.material_cost_id = material_costs.id
INNER JOIN materials ON material_costs.material_id = materials.id
WHERE
    materials.project_id = $1
    AND materials.show_planned_amount_in_report = true
    AND invoice_objects.confirmed_by_operator = true
    AND invoice_materials.invoice_type = 'object-correction'
ORDER BY materials.id
`

type MaterialsInstalledOnObjectForRemainingMaterialAnalysisRow struct {
	ID               int64              `json:"id"`
	Amount           float64            `json:"amount"`
	DateOfCorrection pgtype.Timestamptz `json:"date_of_correction"`
}

func (q *Queries) MaterialsInstalledOnObjectForRemainingMaterialAnalysis(ctx context.Context, projectID pgtype.Int8) ([]MaterialsInstalledOnObjectForRemainingMaterialAnalysisRow, error) {
	rows, err := q.db.Query(ctx, materialsInstalledOnObjectForRemainingMaterialAnalysis, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialsInstalledOnObjectForRemainingMaterialAnalysisRow{}
	for rows.Next() {
		var i MaterialsInstalledOnObjectForRemainingMaterialAnalysisRow
		if err := rows.Scan(&i.ID, &i.Amount, &i.DateOfCorrection); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
