// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMaterialsFiltered = `-- name: CountMaterialsFiltered :one
SELECT COUNT(*)::bigint
FROM materials
WHERE
    project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR category = $2)
    AND (NULLIF($3::text, '') IS NULL OR code = $3)
    AND (NULLIF($4::text, '') IS NULL OR name = $4)
    AND (NULLIF($5::text, '') IS NULL OR unit = $5)
`

type CountMaterialsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   string      `json:"column_3"`
	Column4   string      `json:"column_4"`
	Column5   string      `json:"column_5"`
}

func (q *Queries) CountMaterialsFiltered(ctx context.Context, arg CountMaterialsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMaterialsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (category, code, name, unit, notes, has_serial_number, article,
                       project_id, planned_amount_for_project, show_planned_amount_in_report)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, category, code, name, unit, notes, has_serial_number, article,
          project_id, planned_amount_for_project, show_planned_amount_in_report
`

type CreateMaterialParams struct {
	Category                  pgtype.Text    `json:"category"`
	Code                      pgtype.Text    `json:"code"`
	Name                      pgtype.Text    `json:"name"`
	Unit                      pgtype.Text    `json:"unit"`
	Notes                     pgtype.Text    `json:"notes"`
	HasSerialNumber           pgtype.Bool    `json:"has_serial_number"`
	Article                   pgtype.Text    `json:"article"`
	ProjectID                 pgtype.Int8    `json:"project_id"`
	PlannedAmountForProject   pgtype.Numeric `json:"planned_amount_for_project"`
	ShowPlannedAmountInReport pgtype.Bool    `json:"show_planned_amount_in_report"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.Category,
		arg.Code,
		arg.Name,
		arg.Unit,
		arg.Notes,
		arg.HasSerialNumber,
		arg.Article,
		arg.ProjectID,
		arg.PlannedAmountForProject,
		arg.ShowPlannedAmountInReport,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Code,
		&i.Name,
		&i.Unit,
		&i.Notes,
		&i.HasSerialNumber,
		&i.Article,
		&i.ProjectID,
		&i.PlannedAmountForProject,
		&i.ShowPlannedAmountInReport,
	)
	return i, err
}

type CreateMaterialsBatchParams struct {
	Category                  pgtype.Text    `json:"category"`
	Code                      pgtype.Text    `json:"code"`
	Name                      pgtype.Text    `json:"name"`
	Unit                      pgtype.Text    `json:"unit"`
	Notes                     pgtype.Text    `json:"notes"`
	HasSerialNumber           pgtype.Bool    `json:"has_serial_number"`
	Article                   pgtype.Text    `json:"article"`
	ProjectID                 pgtype.Int8    `json:"project_id"`
	PlannedAmountForProject   pgtype.Numeric `json:"planned_amount_for_project"`
	ShowPlannedAmountInReport pgtype.Bool    `json:"show_planned_amount_in_report"`
}

const deleteMaterial = `-- name: DeleteMaterial :exec
DELETE FROM materials WHERE id = $1
`

func (q *Queries) DeleteMaterial(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMaterial, id)
	return err
}

const getMaterial = `-- name: GetMaterial :one
SELECT id, category, code, name, unit, notes, has_serial_number, article,
       project_id, planned_amount_for_project, show_planned_amount_in_report
FROM materials
WHERE id = $1
`

func (q *Queries) GetMaterial(ctx context.Context, id int64) (Material, error) {
	row := q.db.QueryRow(ctx, getMaterial, id)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Code,
		&i.Name,
		&i.Unit,
		&i.Notes,
		&i.HasSerialNumber,
		&i.Article,
		&i.ProjectID,
		&i.PlannedAmountForProject,
		&i.ShowPlannedAmountInReport,
	)
	return i, err
}

const getMaterialByMaterialCostID = `-- name: GetMaterialByMaterialCostID :one
SELECT id, category, code, name, unit, notes, has_serial_number, article,
       project_id, planned_amount_for_project, show_planned_amount_in_report
FROM materials
WHERE materials.id IN (
    SELECT material_costs.material_id FROM material_costs WHERE material_costs.id = $1
)
LIMIT 1
`

func (q *Queries) GetMaterialByMaterialCostID(ctx context.Context, id int64) (Material, error) {
	row := q.db.QueryRow(ctx, getMaterialByMaterialCostID, id)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Code,
		&i.Name,
		&i.Unit,
		&i.Notes,
		&i.HasSerialNumber,
		&i.Article,
		&i.ProjectID,
		&i.PlannedAmountForProject,
		&i.ShowPlannedAmountInReport,
	)
	return i, err
}

const getMaterialByProjectAndName = `-- name: GetMaterialByProjectAndName :one
SELECT id, category, code, name, unit, notes, has_serial_number, article,
       project_id, planned_amount_for_project, show_planned_amount_in_report
FROM materials
WHERE name = $2 AND project_id = $1
LIMIT 1
`

type GetMaterialByProjectAndNameParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Name      pgtype.Text `json:"name"`
}

func (q *Queries) GetMaterialByProjectAndName(ctx context.Context, arg GetMaterialByProjectAndNameParams) (Material, error) {
	row := q.db.QueryRow(ctx, getMaterialByProjectAndName, arg.ProjectID, arg.Name)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Code,
		&i.Name,
		&i.Unit,
		&i.Notes,
		&i.HasSerialNumber,
		&i.Article,
		&i.ProjectID,
		&i.PlannedAmountForProject,
		&i.ShowPlannedAmountInReport,
	)
	return i, err
}

const listMaterialsByProject = `-- name: ListMaterialsByProject :many
SELECT id, category, code, name, unit, notes, has_serial_number, article,
       project_id, planned_amount_for_project, show_planned_amount_in_report
FROM materials
WHERE project_id = $1
ORDER BY id DESC
`

func (q *Queries) ListMaterialsByProject(ctx context.Context, projectID pgtype.Int8) ([]Material, error) {
	rows, err := q.db.Query(ctx, listMaterialsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.Notes,
			&i.HasSerialNumber,
			&i.Article,
			&i.ProjectID,
			&i.PlannedAmountForProject,
			&i.ShowPlannedAmountInReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsByProjectPaginated = `-- name: ListMaterialsByProjectPaginated :many
SELECT id, category, code, name, unit, notes, has_serial_number, article,
       project_id, planned_amount_for_project, show_planned_amount_in_report
FROM materials
WHERE project_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListMaterialsByProjectPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListMaterialsByProjectPaginated(ctx context.Context, arg ListMaterialsByProjectPaginatedParams) ([]Material, error) {
	rows, err := q.db.Query(ctx, listMaterialsByProjectPaginated, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.Notes,
			&i.HasSerialNumber,
			&i.Article,
			&i.ProjectID,
			&i.PlannedAmountForProject,
			&i.ShowPlannedAmountInReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsPaginatedFiltered = `-- name: ListMaterialsPaginatedFiltered :many
SELECT id, category, code, name, unit, notes, has_serial_number, article,
       project_id, planned_amount_for_project, show_planned_amount_in_report
FROM materials
WHERE
    project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR category = $2)
    AND (NULLIF($3::text, '') IS NULL OR code = $3)
    AND (NULLIF($4::text, '') IS NULL OR name = $4)
    AND (NULLIF($5::text, '') IS NULL OR unit = $5)
ORDER BY id DESC
LIMIT $6 OFFSET $7
`

type ListMaterialsPaginatedFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   string      `json:"column_3"`
	Column4   string      `json:"column_4"`
	Column5   string      `json:"column_5"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListMaterialsPaginatedFiltered(ctx context.Context, arg ListMaterialsPaginatedFilteredParams) ([]Material, error) {
	rows, err := q.db.Query(ctx, listMaterialsPaginatedFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.Notes,
			&i.HasSerialNumber,
			&i.Article,
			&i.ProjectID,
			&i.PlannedAmountForProject,
			&i.ShowPlannedAmountInReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaterial = `-- name: UpdateMaterial :one
UPDATE materials
SET category = $2, code = $3, name = $4, unit = $5, notes = $6,
    has_serial_number = $7, article = $8, project_id = $9,
    planned_amount_for_project = $10, show_planned_amount_in_report = $11
WHERE id = $1
RETURNING id, category, code, name, unit, notes, has_serial_number, article,
          project_id, planned_amount_for_project, show_planned_amount_in_report
`

type UpdateMaterialParams struct {
	ID                        int64          `json:"id"`
	Category                  pgtype.Text    `json:"category"`
	Code                      pgtype.Text    `json:"code"`
	Name                      pgtype.Text    `json:"name"`
	Unit                      pgtype.Text    `json:"unit"`
	Notes                     pgtype.Text    `json:"notes"`
	HasSerialNumber           pgtype.Bool    `json:"has_serial_number"`
	Article                   pgtype.Text    `json:"article"`
	ProjectID                 pgtype.Int8    `json:"project_id"`
	PlannedAmountForProject   pgtype.Numeric `json:"planned_amount_for_project"`
	ShowPlannedAmountInReport pgtype.Bool    `json:"show_planned_amount_in_report"`
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, updateMaterial,
		arg.ID,
		arg.Category,
		arg.Code,
		arg.Name,
		arg.Unit,
		arg.Notes,
		arg.HasSerialNumber,
		arg.Article,
		arg.ProjectID,
		arg.PlannedAmountForProject,
		arg.ShowPlannedAmountInReport,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Code,
		&i.Name,
		&i.Unit,
		&i.Notes,
		&i.HasSerialNumber,
		&i.Article,
		&i.ProjectID,
		&i.PlannedAmountForProject,
		&i.ShowPlannedAmountInReport,
	)
	return i, err
}
