// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material_cost.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMaterialCostsFiltered = `-- name: CountMaterialCostsFiltered :one
SELECT COUNT(*)::bigint
FROM material_costs
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    materials.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR materials.name = $2)
`

type CountMaterialCostsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
}

func (q *Queries) CountMaterialCostsFiltered(ctx context.Context, arg CountMaterialCostsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMaterialCostsFiltered, arg.ProjectID, arg.Column2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMaterialCost = `-- name: CreateMaterialCost :one
INSERT INTO material_costs (material_id, cost_prime, cost_m19, cost_with_customer)
VALUES ($1, $2, $3, $4)
RETURNING id, material_id, cost_prime, cost_m19, cost_with_customer
`

type CreateMaterialCostParams struct {
	MaterialID       pgtype.Int8    `json:"material_id"`
	CostPrime        pgtype.Numeric `json:"cost_prime"`
	CostM19          pgtype.Numeric `json:"cost_m19"`
	CostWithCustomer pgtype.Numeric `json:"cost_with_customer"`
}

func (q *Queries) CreateMaterialCost(ctx context.Context, arg CreateMaterialCostParams) (MaterialCost, error) {
	row := q.db.QueryRow(ctx, createMaterialCost,
		arg.MaterialID,
		arg.CostPrime,
		arg.CostM19,
		arg.CostWithCustomer,
	)
	var i MaterialCost
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.CostPrime,
		&i.CostM19,
		&i.CostWithCustomer,
	)
	return i, err
}

type CreateMaterialCostsBatchParams struct {
	MaterialID       pgtype.Int8    `json:"material_id"`
	CostPrime        pgtype.Numeric `json:"cost_prime"`
	CostM19          pgtype.Numeric `json:"cost_m19"`
	CostWithCustomer pgtype.Numeric `json:"cost_with_customer"`
}

const deleteMaterialCost = `-- name: DeleteMaterialCost :exec
DELETE FROM material_costs WHERE id = $1
`

func (q *Queries) DeleteMaterialCost(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMaterialCost, id)
	return err
}

const getMaterialCost = `-- name: GetMaterialCost :one
SELECT id, material_id, cost_prime, cost_m19, cost_with_customer
FROM material_costs
WHERE id = $1
`

func (q *Queries) GetMaterialCost(ctx context.Context, id int64) (MaterialCost, error) {
	row := q.db.QueryRow(ctx, getMaterialCost, id)
	var i MaterialCost
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.CostPrime,
		&i.CostM19,
		&i.CostWithCustomer,
	)
	return i, err
}

const getMaterialCostByCostM19AndMaterialID = `-- name: GetMaterialCostByCostM19AndMaterialID :one
SELECT id, material_id, cost_prime, cost_m19, cost_with_customer
FROM material_costs
WHERE material_id = $1 AND cost_m19 = $2
LIMIT 1
`

type GetMaterialCostByCostM19AndMaterialIDParams struct {
	MaterialID pgtype.Int8    `json:"material_id"`
	CostM19    pgtype.Numeric `json:"cost_m19"`
}

func (q *Queries) GetMaterialCostByCostM19AndMaterialID(ctx context.Context, arg GetMaterialCostByCostM19AndMaterialIDParams) (MaterialCost, error) {
	row := q.db.QueryRow(ctx, getMaterialCostByCostM19AndMaterialID, arg.MaterialID, arg.CostM19)
	var i MaterialCost
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.CostPrime,
		&i.CostM19,
		&i.CostWithCustomer,
	)
	return i, err
}

const listMaterialCosts = `-- name: ListMaterialCosts :many
SELECT id, material_id, cost_prime, cost_m19, cost_with_customer
FROM material_costs
ORDER BY id DESC
`

func (q *Queries) ListMaterialCosts(ctx context.Context) ([]MaterialCost, error) {
	rows, err := q.db.Query(ctx, listMaterialCosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialCost{}
	for rows.Next() {
		var i MaterialCost
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.CostPrime,
			&i.CostM19,
			&i.CostWithCustomer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialCostsByMaterialID = `-- name: ListMaterialCostsByMaterialID :many
SELECT id, material_id, cost_prime, cost_m19, cost_with_customer
FROM material_costs
WHERE material_id = $1
`

func (q *Queries) ListMaterialCostsByMaterialID(ctx context.Context, materialID pgtype.Int8) ([]MaterialCost, error) {
	rows, err := q.db.Query(ctx, listMaterialCostsByMaterialID, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialCost{}
	for rows.Next() {
		var i MaterialCost
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.CostPrime,
			&i.CostM19,
			&i.CostWithCustomer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialCostsByMaterialIDSorted = `-- name: ListMaterialCostsByMaterialIDSorted :many
SELECT id, material_id, cost_prime, cost_m19, cost_with_customer
FROM material_costs
WHERE material_id = $1
ORDER BY cost_m19 DESC
`

func (q *Queries) ListMaterialCostsByMaterialIDSorted(ctx context.Context, materialID pgtype.Int8) ([]MaterialCost, error) {
	rows, err := q.db.Query(ctx, listMaterialCostsByMaterialIDSorted, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialCost{}
	for rows.Next() {
		var i MaterialCost
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.CostPrime,
			&i.CostM19,
			&i.CostWithCustomer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialCostsViewByProject = `-- name: ListMaterialCostsViewByProject :many
SELECT
    material_costs.id                       AS id,
    material_costs.cost_prime               AS cost_prime,
    material_costs.cost_m19                 AS cost_m19,
    material_costs.cost_with_customer       AS cost_with_customer,
    COALESCE(materials.name, '')::text      AS material_name
FROM material_costs
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE materials.project_id = $1
ORDER BY material_costs.id DESC
LIMIT $2 OFFSET $3
`

type ListMaterialCostsViewByProjectParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListMaterialCostsViewByProjectRow struct {
	ID               int64          `json:"id"`
	CostPrime        pgtype.Numeric `json:"cost_prime"`
	CostM19          pgtype.Numeric `json:"cost_m19"`
	CostWithCustomer pgtype.Numeric `json:"cost_with_customer"`
	MaterialName     string         `json:"material_name"`
}

func (q *Queries) ListMaterialCostsViewByProject(ctx context.Context, arg ListMaterialCostsViewByProjectParams) ([]ListMaterialCostsViewByProjectRow, error) {
	rows, err := q.db.Query(ctx, listMaterialCostsViewByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialCostsViewByProjectRow{}
	for rows.Next() {
		var i ListMaterialCostsViewByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.CostPrime,
			&i.CostM19,
			&i.CostWithCustomer,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialCostsViewFiltered = `-- name: ListMaterialCostsViewFiltered :many
SELECT
    material_costs.id                       AS id,
    material_costs.cost_prime               AS cost_prime,
    material_costs.cost_m19                 AS cost_m19,
    material_costs.cost_with_customer       AS cost_with_customer,
    COALESCE(materials.name, '')::text      AS material_name
FROM material_costs
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    materials.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR materials.name = $2)
ORDER BY material_costs.id DESC
LIMIT $3 OFFSET $4
`

type ListMaterialCostsViewFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListMaterialCostsViewFilteredRow struct {
	ID               int64          `json:"id"`
	CostPrime        pgtype.Numeric `json:"cost_prime"`
	CostM19          pgtype.Numeric `json:"cost_m19"`
	CostWithCustomer pgtype.Numeric `json:"cost_with_customer"`
	MaterialName     string         `json:"material_name"`
}

func (q *Queries) ListMaterialCostsViewFiltered(ctx context.Context, arg ListMaterialCostsViewFilteredParams) ([]ListMaterialCostsViewFilteredRow, error) {
	rows, err := q.db.Query(ctx, listMaterialCostsViewFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialCostsViewFilteredRow{}
	for rows.Next() {
		var i ListMaterialCostsViewFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.CostPrime,
			&i.CostM19,
			&i.CostWithCustomer,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaterialCost = `-- name: UpdateMaterialCost :one
UPDATE material_costs
SET material_id = $2, cost_prime = $3, cost_m19 = $4, cost_with_customer = $5
WHERE id = $1
RETURNING id, material_id, cost_prime, cost_m19, cost_with_customer
`

type UpdateMaterialCostParams struct {
	ID               int64          `json:"id"`
	MaterialID       pgtype.Int8    `json:"material_id"`
	CostPrime        pgtype.Numeric `json:"cost_prime"`
	CostM19          pgtype.Numeric `json:"cost_m19"`
	CostWithCustomer pgtype.Numeric `json:"cost_with_customer"`
}

func (q *Queries) UpdateMaterialCost(ctx context.Context, arg UpdateMaterialCostParams) (MaterialCost, error) {
	row := q.db.QueryRow(ctx, updateMaterialCost,
		arg.ID,
		arg.MaterialID,
		arg.CostPrime,
		arg.CostM19,
		arg.CostWithCustomer,
	)
	var i MaterialCost
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.CostPrime,
		&i.CostM19,
		&i.CostWithCustomer,
	)
	return i, err
}
