// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: material_location.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMaterialLocations = `-- name: CountMaterialLocations :one
SELECT COUNT(*)::bigint FROM material_locations
`

func (q *Queries) CountMaterialLocations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMaterialLocations)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMaterialLocation = `-- name: CreateMaterialLocation :one
INSERT INTO material_locations (project_id, material_cost_id, location_id, location_type, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, material_cost_id, location_id, location_type, amount
`

type CreateMaterialLocationParams struct {
	ProjectID      pgtype.Int8    `json:"project_id"`
	MaterialCostID pgtype.Int8    `json:"material_cost_id"`
	LocationID     pgtype.Int8    `json:"location_id"`
	LocationType   pgtype.Text    `json:"location_type"`
	Amount         pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateMaterialLocation(ctx context.Context, arg CreateMaterialLocationParams) (MaterialLocation, error) {
	row := q.db.QueryRow(ctx, createMaterialLocation,
		arg.ProjectID,
		arg.MaterialCostID,
		arg.LocationID,
		arg.LocationType,
		arg.Amount,
	)
	var i MaterialLocation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MaterialCostID,
		&i.LocationID,
		&i.LocationType,
		&i.Amount,
	)
	return i, err
}

const deleteMaterialLocation = `-- name: DeleteMaterialLocation :exec
DELETE FROM material_locations WHERE id = $1
`

func (q *Queries) DeleteMaterialLocation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMaterialLocation, id)
	return err
}

const getMaterialLocation = `-- name: GetMaterialLocation :one
SELECT id, project_id, material_cost_id, location_id, location_type, amount
FROM material_locations
WHERE id = $1
`

func (q *Queries) GetMaterialLocation(ctx context.Context, id int64) (MaterialLocation, error) {
	row := q.db.QueryRow(ctx, getMaterialLocation, id)
	var i MaterialLocation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MaterialCostID,
		&i.LocationID,
		&i.LocationType,
		&i.Amount,
	)
	return i, err
}

const getTotalAmountInLocation = `-- name: GetTotalAmountInLocation :one
SELECT COALESCE(SUM(material_locations.amount), 0)::numeric AS total_amount
FROM materials
INNER JOIN material_costs ON material_costs.material_id = materials.id
INNER JOIN material_locations ON material_locations.material_cost_id = material_costs.id
WHERE
    materials.project_id = $1
    AND materials.id = $2
    AND material_locations.location_type = $3
    AND COALESCE(material_locations.location_id, 0) = $4
    AND material_locations.amount > 0
`

type GetTotalAmountInLocationParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	ID           int64       `json:"id"`
	LocationType pgtype.Text `json:"location_type"`
	LocationID   pgtype.Int8 `json:"location_id"`
}

// Used by invoice_return.GetMaterialAmountByMaterialID — sums material_locations.amount
// across all material_costs of the given material in the given location, where amount > 0.
func (q *Queries) GetTotalAmountInLocation(ctx context.Context, arg GetTotalAmountInLocationParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalAmountInLocation,
		arg.ProjectID,
		arg.ID,
		arg.LocationType,
		arg.LocationID,
	)
	var total_amount pgtype.Numeric
	err := row.Scan(&total_amount)
	return total_amount, err
}

const getUniqueMaterialTotalAmount = `-- name: GetUniqueMaterialTotalAmount :one
SELECT COALESCE(material_locations.amount, 0)::numeric AS amount
FROM material_locations
WHERE
    material_locations.project_id = $1
    AND material_locations.location_type = $2
    AND COALESCE(material_locations.location_id, 0) = $3
    AND material_locations.material_cost_id = $4
LIMIT 1
`

type GetUniqueMaterialTotalAmountParams struct {
	ProjectID      pgtype.Int8 `json:"project_id"`
	LocationType   pgtype.Text `json:"location_type"`
	LocationID     pgtype.Int8 `json:"location_id"`
	MaterialCostID pgtype.Int8 `json:"material_cost_id"`
}

func (q *Queries) GetUniqueMaterialTotalAmount(ctx context.Context, arg GetUniqueMaterialTotalAmountParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getUniqueMaterialTotalAmount,
		arg.ProjectID,
		arg.LocationType,
		arg.LocationID,
		arg.MaterialCostID,
	)
	var amount pgtype.Numeric
	err := row.Scan(&amount)
	return amount, err
}

const listBalanceReportData = `-- name: ListBalanceReportData :many
SELECT
    COALESCE(material_locations.location_id, 0)::bigint    AS location_id,
    materials.id                                           AS material_id,
    COALESCE(materials.code, '')::text                     AS material_code,
    COALESCE(materials.name, '')::text                     AS material_name,
    COALESCE(materials.unit, '')::text                     AS material_unit,
    COALESCE(material_locations.amount, 0)::numeric        AS total_amount,
    COALESCE(material_defects.amount, 0)::numeric          AS defect_amount,
    COALESCE(material_costs.cost_m19, 0)::numeric          AS material_cost_m19,
    (COALESCE(material_locations.amount, 0) * COALESCE(material_costs.cost_m19, 0))::numeric AS total_cost,
    (COALESCE(material_defects.amount, 0)  * COALESCE(material_costs.cost_m19, 0))::numeric AS total_defect_cost
FROM material_locations
INNER JOIN material_costs ON material_costs.id = material_locations.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
LEFT JOIN material_defects ON material_defects.material_location_id = material_locations.id
WHERE
    material_locations.project_id = $1
    AND material_locations.location_type = $2
    AND (NULLIF($3::bigint, 0) IS NULL OR material_locations.location_id = $3)
    AND material_locations.amount <> 0
ORDER BY material_locations.id
`

type ListBalanceReportDataParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	LocationType pgtype.Text `json:"location_type"`
	Column3      int64       `json:"column_3"`
}

type ListBalanceReportDataRow struct {
	LocationID      int64          `json:"location_id"`
	MaterialID      int64          `json:"material_id"`
	MaterialCode    string         `json:"material_code"`
	MaterialName    string         `json:"material_name"`
	MaterialUnit    string         `json:"material_unit"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	DefectAmount    pgtype.Numeric `json:"defect_amount"`
	MaterialCostM19 pgtype.Numeric `json:"material_cost_m19"`
	TotalCost       pgtype.Numeric `json:"total_cost"`
	TotalDefectCost pgtype.Numeric `json:"total_defect_cost"`
}

func (q *Queries) ListBalanceReportData(ctx context.Context, arg ListBalanceReportDataParams) ([]ListBalanceReportDataRow, error) {
	rows, err := q.db.Query(ctx, listBalanceReportData, arg.ProjectID, arg.LocationType, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalanceReportDataRow{}
	for rows.Next() {
		var i ListBalanceReportDataRow
		if err := rows.Scan(
			&i.LocationID,
			&i.MaterialID,
			&i.MaterialCode,
			&i.MaterialName,
			&i.MaterialUnit,
			&i.TotalAmount,
			&i.DefectAmount,
			&i.MaterialCostM19,
			&i.TotalCost,
			&i.TotalDefectCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialLocations = `-- name: ListMaterialLocations :many
SELECT id, project_id, material_cost_id, location_id, location_type, amount
FROM material_locations
ORDER BY id DESC
`

func (q *Queries) ListMaterialLocations(ctx context.Context) ([]MaterialLocation, error) {
	rows, err := q.db.Query(ctx, listMaterialLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialLocation{}
	for rows.Next() {
		var i MaterialLocation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MaterialCostID,
			&i.LocationID,
			&i.LocationType,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialLocationsForInvoiceConfirmation = `-- name: ListMaterialLocationsForInvoiceConfirmation :many
SELECT id, project_id, material_cost_id, location_id, location_type, amount
FROM material_locations
WHERE
    material_locations.location_type = $1
    AND COALESCE(material_locations.location_id, 0) = $2
    AND material_locations.material_cost_id IN (
        SELECT invoice_materials.material_cost_id
        FROM invoice_materials
        WHERE
            invoice_materials.invoice_type = $3
            AND invoice_materials.invoice_id = $4
    )
`

type ListMaterialLocationsForInvoiceConfirmationParams struct {
	LocationType pgtype.Text `json:"location_type"`
	LocationID   pgtype.Int8 `json:"location_id"`
	InvoiceType  pgtype.Text `json:"invoice_type"`
	InvoiceID    pgtype.Int8 `json:"invoice_id"`
}

// The GORM-era materialLocationRepo.GetMaterialsInLocationBasedOnInvoiceID
// query: rows in a (location_type, location_id) location whose material_cost_id
// matches one of the invoice's invoice_materials rows.
func (q *Queries) ListMaterialLocationsForInvoiceConfirmation(ctx context.Context, arg ListMaterialLocationsForInvoiceConfirmationParams) ([]MaterialLocation, error) {
	rows, err := q.db.Query(ctx, listMaterialLocationsForInvoiceConfirmation,
		arg.LocationType,
		arg.LocationID,
		arg.InvoiceType,
		arg.InvoiceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialLocation{}
	for rows.Next() {
		var i MaterialLocation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MaterialCostID,
			&i.LocationID,
			&i.LocationType,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialLocationsLive = `-- name: ListMaterialLocationsLive :many
SELECT
    materials.id                                            AS material_id,
    COALESCE(materials.name, '')::text                      AS material_name,
    COALESCE(materials.unit, '')::text                      AS material_unit,
    material_costs.id                                       AS material_cost_id,
    COALESCE(material_costs.cost_m19, 0)::numeric           AS material_cost_m19,
    COALESCE(material_locations.location_type, '')::text    AS location_type,
    COALESCE(material_locations.location_id, 0)::bigint     AS location_id,
    COALESCE(material_locations.amount, 0)::numeric         AS amount
FROM material_locations
INNER JOIN material_costs ON material_costs.id = material_locations.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    material_locations.location_type = $1
    AND material_locations.project_id = $2
    AND (NULLIF($3::bigint, 0) IS NULL OR material_locations.location_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR materials.id = $4)
`

type ListMaterialLocationsLiveParams struct {
	LocationType pgtype.Text `json:"location_type"`
	ProjectID    pgtype.Int8 `json:"project_id"`
	Column3      int64       `json:"column_3"`
	Column4      int64       `json:"column_4"`
}

type ListMaterialLocationsLiveRow struct {
	MaterialID      int64          `json:"material_id"`
	MaterialName    string         `json:"material_name"`
	MaterialUnit    string         `json:"material_unit"`
	MaterialCostID  int64          `json:"material_cost_id"`
	MaterialCostM19 pgtype.Numeric `json:"material_cost_m19"`
	LocationType    string         `json:"location_type"`
	LocationID      int64          `json:"location_id"`
	Amount          pgtype.Numeric `json:"amount"`
}

func (q *Queries) ListMaterialLocationsLive(ctx context.Context, arg ListMaterialLocationsLiveParams) ([]ListMaterialLocationsLiveRow, error) {
	rows, err := q.db.Query(ctx, listMaterialLocationsLive,
		arg.LocationType,
		arg.ProjectID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterialLocationsLiveRow{}
	for rows.Next() {
		var i ListMaterialLocationsLiveRow
		if err := rows.Scan(
			&i.MaterialID,
			&i.MaterialName,
			&i.MaterialUnit,
			&i.MaterialCostID,
			&i.MaterialCostM19,
			&i.LocationType,
			&i.LocationID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialLocationsPaginated = `-- name: ListMaterialLocationsPaginated :many
SELECT id, project_id, material_cost_id, location_id, location_type, amount
FROM material_locations
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListMaterialLocationsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMaterialLocationsPaginated(ctx context.Context, arg ListMaterialLocationsPaginatedParams) ([]MaterialLocation, error) {
	rows, err := q.db.Query(ctx, listMaterialLocationsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialLocation{}
	for rows.Next() {
		var i MaterialLocation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MaterialCostID,
			&i.LocationID,
			&i.LocationType,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialLocationsPaginatedFiltered = `-- name: ListMaterialLocationsPaginatedFiltered :many
SELECT id, project_id, material_cost_id, location_id, location_type, amount
FROM material_locations
WHERE
    (NULLIF($1::bigint, 0) IS NULL OR material_cost_id = $1)
    AND (NULLIF($2::bigint, 0) IS NULL OR location_id = $2)
    AND (NULLIF($3::text, '') IS NULL OR location_type = $3)
    AND (NULLIF($4::numeric, 0) IS NULL OR amount = $4)
ORDER BY id DESC
LIMIT $5 OFFSET $6
`

type ListMaterialLocationsPaginatedFilteredParams struct {
	Column1 int64          `json:"column_1"`
	Column2 int64          `json:"column_2"`
	Column3 string         `json:"column_3"`
	Column4 pgtype.Numeric `json:"column_4"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

// Fixed during phase 6 from the GORM-era SQL that targeted the wrong
// table (`SELECT * FROM materials`). This query now correctly hits
// material_locations.
func (q *Queries) ListMaterialLocationsPaginatedFiltered(ctx context.Context, arg ListMaterialLocationsPaginatedFilteredParams) ([]MaterialLocation, error) {
	rows, err := q.db.Query(ctx, listMaterialLocationsPaginatedFiltered,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialLocation{}
	for rows.Next() {
		var i MaterialLocation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MaterialCostID,
			&i.LocationID,
			&i.LocationType,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueMaterialCostsFromLocation = `-- name: ListUniqueMaterialCostsFromLocation :many
SELECT DISTINCT
    material_costs.id, material_costs.material_id,
    material_costs.cost_prime, material_costs.cost_m19, material_costs.cost_with_customer
FROM material_locations
INNER JOIN material_costs ON material_costs.id = material_locations.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    material_locations.project_id = $1
    AND material_locations.location_type = $2
    AND COALESCE(material_locations.location_id, 0) = $3
    AND materials.id = $4
`

type ListUniqueMaterialCostsFromLocationParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	LocationType pgtype.Text `json:"location_type"`
	LocationID   pgtype.Int8 `json:"location_id"`
	ID           int64       `json:"id"`
}

func (q *Queries) ListUniqueMaterialCostsFromLocation(ctx context.Context, arg ListUniqueMaterialCostsFromLocationParams) ([]MaterialCost, error) {
	rows, err := q.db.Query(ctx, listUniqueMaterialCostsFromLocation,
		arg.ProjectID,
		arg.LocationType,
		arg.LocationID,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaterialCost{}
	for rows.Next() {
		var i MaterialCost
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.CostPrime,
			&i.CostM19,
			&i.CostWithCustomer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueMaterialsFromLocation = `-- name: ListUniqueMaterialsFromLocation :many
SELECT DISTINCT
    materials.id, materials.category, materials.code, materials.name,
    materials.unit, materials.notes, materials.has_serial_number,
    materials.article, materials.project_id,
    materials.planned_amount_for_project, materials.show_planned_amount_in_report
FROM material_locations
INNER JOIN material_costs ON material_costs.id = material_locations.material_cost_id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    material_locations.project_id = $1
    AND COALESCE(material_locations.location_id, 0) = $2
    AND material_locations.location_type = $3
    AND material_locations.amount > 0
ORDER BY materials.id
`

type ListUniqueMaterialsFromLocationParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	LocationID   pgtype.Int8 `json:"location_id"`
	LocationType pgtype.Text `json:"location_type"`
}

// COALESCE on location_id: legacy warehouse rows can land with location_id IS NULL
// while canonical writes use 0. Normalize so NULL is treated as 0 — matches the
// semantics of ListBalanceReportData. Without this, materials sitting at
// (warehouse, NULL) appear in balance reports but are unselectable in the picker.
func (q *Queries) ListUniqueMaterialsFromLocation(ctx context.Context, arg ListUniqueMaterialsFromLocationParams) ([]Material, error) {
	rows, err := q.db.Query(ctx, listUniqueMaterialsFromLocation, arg.ProjectID, arg.LocationID, arg.LocationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Material{}
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Code,
			&i.Name,
			&i.Unit,
			&i.Notes,
			&i.HasSerialNumber,
			&i.Article,
			&i.ProjectID,
			&i.PlannedAmountForProject,
			&i.ShowPlannedAmountInReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueObjectsForSelectFromMaterialLocations = `-- name: ListUniqueObjectsForSelectFromMaterialLocations :many
SELECT
    objects.id                       AS id,
    COALESCE(objects.name, '')::text AS object_name,
    COALESCE(objects.type, '')::text AS object_type
FROM objects
WHERE objects.id IN (
    SELECT DISTINCT location_id
    FROM material_locations
    WHERE
        location_type = 'object'
        AND amount > 0
        AND material_locations.project_id = $1
        AND location_id IS NOT NULL
)
`

type ListUniqueObjectsForSelectFromMaterialLocationsRow struct {
	ID         int64  `json:"id"`
	ObjectName string `json:"object_name"`
	ObjectType string `json:"object_type"`
}

func (q *Queries) ListUniqueObjectsForSelectFromMaterialLocations(ctx context.Context, projectID pgtype.Int8) ([]ListUniqueObjectsForSelectFromMaterialLocationsRow, error) {
	rows, err := q.db.Query(ctx, listUniqueObjectsForSelectFromMaterialLocations, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUniqueObjectsForSelectFromMaterialLocationsRow{}
	for rows.Next() {
		var i ListUniqueObjectsForSelectFromMaterialLocationsRow
		if err := rows.Scan(&i.ID, &i.ObjectName, &i.ObjectType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueTeamsForSelectFromMaterialLocations = `-- name: ListUniqueTeamsForSelectFromMaterialLocations :many
SELECT
    teams.id                          AS id,
    COALESCE(teams.number, '')::text  AS team_number,
    COALESCE(workers.name, '')::text  AS team_leader_name
FROM teams
INNER JOIN team_leaders ON team_leaders.team_id = teams.id
INNER JOIN workers ON team_leaders.leader_worker_id = workers.id
WHERE teams.id IN (
    SELECT DISTINCT location_id
    FROM material_locations
    WHERE
        location_type = 'team'
        AND amount > 0
        AND material_locations.project_id = $1
        AND location_id IS NOT NULL
)
`

type ListUniqueTeamsForSelectFromMaterialLocationsRow struct {
	ID             int64  `json:"id"`
	TeamNumber     string `json:"team_number"`
	TeamLeaderName string `json:"team_leader_name"`
}

func (q *Queries) ListUniqueTeamsForSelectFromMaterialLocations(ctx context.Context, projectID pgtype.Int8) ([]ListUniqueTeamsForSelectFromMaterialLocationsRow, error) {
	rows, err := q.db.Query(ctx, listUniqueTeamsForSelectFromMaterialLocations, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUniqueTeamsForSelectFromMaterialLocationsRow{}
	for rows.Next() {
		var i ListUniqueTeamsForSelectFromMaterialLocationsRow
		if err := rows.Scan(&i.ID, &i.TeamNumber, &i.TeamLeaderName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaterialLocation = `-- name: UpdateMaterialLocation :exec
UPDATE material_locations
SET project_id = $2, material_cost_id = $3, location_id = $4, location_type = $5, amount = $6
WHERE id = $1
`

type UpdateMaterialLocationParams struct {
	ID             int64          `json:"id"`
	ProjectID      pgtype.Int8    `json:"project_id"`
	MaterialCostID pgtype.Int8    `json:"material_cost_id"`
	LocationID     pgtype.Int8    `json:"location_id"`
	LocationType   pgtype.Text    `json:"location_type"`
	Amount         pgtype.Numeric `json:"amount"`
}

func (q *Queries) UpdateMaterialLocation(ctx context.Context, arg UpdateMaterialLocationParams) error {
	_, err := q.db.Exec(ctx, updateMaterialLocation,
		arg.ID,
		arg.ProjectID,
		arg.MaterialCostID,
		arg.LocationID,
		arg.LocationType,
		arg.Amount,
	)
	return err
}
