// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auction struct {
	ID   int64       `json:"id"`
	Name pgtype.Text `json:"name"`
}

type AuctionItem struct {
	ID               int64          `json:"id"`
	AuctionPackageID pgtype.Int8    `json:"auction_package_id"`
	Name             pgtype.Text    `json:"name"`
	Description      pgtype.Text    `json:"description"`
	Unit             pgtype.Text    `json:"unit"`
	Quantity         pgtype.Numeric `json:"quantity"`
	Note             pgtype.Text    `json:"note"`
}

type AuctionPackage struct {
	ID        int64       `json:"id"`
	AuctionID pgtype.Int8 `json:"auction_id"`
	Name      pgtype.Text `json:"name"`
}

type AuctionParticipantPrice struct {
	ID            int64       `json:"id"`
	AuctionItemID pgtype.Int8 `json:"auction_item_id"`
	UserID        pgtype.Int8 `json:"user_id"`
	UnitPrice     pgtype.Text `json:"unit_price"`
	Comments      pgtype.Text `json:"comments"`
}

type District struct {
	ID        int64       `json:"id"`
	Name      pgtype.Text `json:"name"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

type InvoiceCount struct {
	ID          int64       `json:"id"`
	ProjectID   pgtype.Int8 `json:"project_id"`
	InvoiceType pgtype.Text `json:"invoice_type"`
	Count       pgtype.Int8 `json:"count"`
}

type InvoiceInput struct {
	ID                       int64              `json:"id"`
	ProjectID                pgtype.Int8        `json:"project_id"`
	WarehouseManagerWorkerID pgtype.Int8        `json:"warehouse_manager_worker_id"`
	ReleasedWorkerID         pgtype.Int8        `json:"released_worker_id"`
	DeliveryCode             pgtype.Text        `json:"delivery_code"`
	Notes                    pgtype.Text        `json:"notes"`
	DateOfInvoice            pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmed                pgtype.Bool        `json:"confirmed"`
}

type InvoiceMaterial struct {
	ID             int64          `json:"id"`
	ProjectID      pgtype.Int8    `json:"project_id"`
	MaterialCostID pgtype.Int8    `json:"material_cost_id"`
	InvoiceID      pgtype.Int8    `json:"invoice_id"`
	InvoiceType    pgtype.Text    `json:"invoice_type"`
	IsDefected     pgtype.Bool    `json:"is_defected"`
	Amount         pgtype.Numeric `json:"amount"`
	Notes          pgtype.Text    `json:"notes"`
}

type InvoiceObject struct {
	ID                  int64              `json:"id"`
	DistrictID          pgtype.Int8        `json:"district_id"`
	DeliveryCode        pgtype.Text        `json:"delivery_code"`
	ProjectID           pgtype.Int8        `json:"project_id"`
	SupervisorWorkerID  pgtype.Int8        `json:"supervisor_worker_id"`
	ObjectID            pgtype.Int8        `json:"object_id"`
	TeamID              pgtype.Int8        `json:"team_id"`
	DateOfInvoice       pgtype.Timestamptz `json:"date_of_invoice"`
	ConfirmedByOperator pgtype.Bool        `json:"confirmed_by_operator"`
	DateOfCorrection    pgtype.Timestamptz `json:"date_of_correction"`
}

type InvoiceObjectOperator struct {
	ID               int64       `json:"id"`
	OperatorWorkerID pgtype.Int8 `json:"operator_worker_id"`
	InvoiceObjectID  pgtype.Int8 `json:"invoice_object_id"`
}

type InvoiceOperation struct {
	ID          int64          `json:"id"`
	ProjectID   pgtype.Int8    `json:"project_id"`
	OperationID pgtype.Int8    `json:"operation_id"`
	InvoiceID   pgtype.Int8    `json:"invoice_id"`
	InvoiceType pgtype.Text    `json:"invoice_type"`
	Amount      pgtype.Numeric `json:"amount"`
	Notes       pgtype.Text    `json:"notes"`
}

type InvoiceOutput struct {
	ID                       int64              `json:"id"`
	DistrictID               pgtype.Int8        `json:"district_id"`
	ProjectID                pgtype.Int8        `json:"project_id"`
	WarehouseManagerWorkerID pgtype.Int8        `json:"warehouse_manager_worker_id"`
	ReleasedWorkerID         pgtype.Int8        `json:"released_worker_id"`
	RecipientWorkerID        pgtype.Int8        `json:"recipient_worker_id"`
	TeamID                   pgtype.Int8        `json:"team_id"`
	DeliveryCode             pgtype.Text        `json:"delivery_code"`
	DateOfInvoice            pgtype.Timestamptz `json:"date_of_invoice"`
	Notes                    pgtype.Text        `json:"notes"`
	Confirmation             pgtype.Bool        `json:"confirmation"`
}

type InvoiceOutputOutOfProject struct {
	ID               int64              `json:"id"`
	ProjectID        pgtype.Int8        `json:"project_id"`
	DeliveryCode     pgtype.Text        `json:"delivery_code"`
	ReleasedWorkerID pgtype.Int8        `json:"released_worker_id"`
	NameOfProject    pgtype.Text        `json:"name_of_project"`
	DateOfInvoice    pgtype.Timestamptz `json:"date_of_invoice"`
	Notes            pgtype.Text        `json:"notes"`
	Confirmation     pgtype.Bool        `json:"confirmation"`
}

type InvoiceReturn struct {
	ID                 int64              `json:"id"`
	ProjectID          pgtype.Int8        `json:"project_id"`
	DistrictID         pgtype.Int8        `json:"district_id"`
	ReturnerType       pgtype.Text        `json:"returner_type"`
	ReturnerID         pgtype.Int8        `json:"returner_id"`
	AcceptorType       pgtype.Text        `json:"acceptor_type"`
	AcceptorID         pgtype.Int8        `json:"acceptor_id"`
	AcceptedByWorkerID pgtype.Int8        `json:"accepted_by_worker_id"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
	Notes              pgtype.Text        `json:"notes"`
	DeliveryCode       pgtype.Text        `json:"delivery_code"`
	Confirmation       pgtype.Bool        `json:"confirmation"`
}

type InvoiceWriteOff struct {
	ID                 int64              `json:"id"`
	ProjectID          pgtype.Int8        `json:"project_id"`
	ReleasedWorkerID   pgtype.Int8        `json:"released_worker_id"`
	WriteOffType       pgtype.Text        `json:"write_off_type"`
	WriteOffLocationID pgtype.Int8        `json:"write_off_location_id"`
	DeliveryCode       pgtype.Text        `json:"delivery_code"`
	DateOfInvoice      pgtype.Timestamptz `json:"date_of_invoice"`
	Confirmation       pgtype.Bool        `json:"confirmation"`
	DateOfConfirmation pgtype.Timestamptz `json:"date_of_confirmation"`
	Notes              pgtype.Text        `json:"notes"`
}

type Kl04KvObject struct {
	ID        int64          `json:"id"`
	Length    pgtype.Numeric `json:"length"`
	Nourashes pgtype.Text    `json:"nourashes"`
}

type Material struct {
	ID                        int64          `json:"id"`
	Category                  pgtype.Text    `json:"category"`
	Code                      pgtype.Text    `json:"code"`
	Name                      pgtype.Text    `json:"name"`
	Unit                      pgtype.Text    `json:"unit"`
	Notes                     pgtype.Text    `json:"notes"`
	HasSerialNumber           pgtype.Bool    `json:"has_serial_number"`
	Article                   pgtype.Text    `json:"article"`
	ProjectID                 pgtype.Int8    `json:"project_id"`
	PlannedAmountForProject   pgtype.Numeric `json:"planned_amount_for_project"`
	ShowPlannedAmountInReport pgtype.Bool    `json:"show_planned_amount_in_report"`
}

type MaterialCost struct {
	ID               int64          `json:"id"`
	MaterialID       pgtype.Int8    `json:"material_id"`
	CostPrime        pgtype.Numeric `json:"cost_prime"`
	CostM19          pgtype.Numeric `json:"cost_m19"`
	CostWithCustomer pgtype.Numeric `json:"cost_with_customer"`
}

type MaterialDefect struct {
	ID                 int64          `json:"id"`
	Amount             pgtype.Numeric `json:"amount"`
	MaterialLocationID pgtype.Int8    `json:"material_location_id"`
}

type MaterialLocation struct {
	ID             int64          `json:"id"`
	ProjectID      pgtype.Int8    `json:"project_id"`
	MaterialCostID pgtype.Int8    `json:"material_cost_id"`
	LocationID     pgtype.Int8    `json:"location_id"`
	LocationType   pgtype.Text    `json:"location_type"`
	Amount         pgtype.Numeric `json:"amount"`
}

type MjdObject struct {
	ID              int64       `json:"id"`
	Model           pgtype.Text `json:"model"`
	AmountStores    pgtype.Int8 `json:"amount_stores"`
	AmountEntrances pgtype.Int8 `json:"amount_entrances"`
	HasBasement     pgtype.Bool `json:"has_basement"`
}

type Object struct {
	ID               int64       `json:"id"`
	ObjectDetailedID pgtype.Int8 `json:"object_detailed_id"`
	Type             pgtype.Text `json:"type"`
	Name             pgtype.Text `json:"name"`
	Status           pgtype.Text `json:"status"`
	ProjectID        pgtype.Int8 `json:"project_id"`
}

type ObjectSupervisor struct {
	ID                 int64       `json:"id"`
	SupervisorWorkerID pgtype.Int8 `json:"supervisor_worker_id"`
	ObjectID           pgtype.Int8 `json:"object_id"`
}

type ObjectTeam struct {
	ID       int64       `json:"id"`
	TeamID   pgtype.Int8 `json:"team_id"`
	ObjectID pgtype.Int8 `json:"object_id"`
}

type Operation struct {
	ID                        int64          `json:"id"`
	ProjectID                 pgtype.Int8    `json:"project_id"`
	Name                      pgtype.Text    `json:"name"`
	Code                      pgtype.Text    `json:"code"`
	CostPrime                 pgtype.Numeric `json:"cost_prime"`
	CostWithCustomer          pgtype.Numeric `json:"cost_with_customer"`
	PlannedAmountForProject   pgtype.Numeric `json:"planned_amount_for_project"`
	ShowPlannedAmountInReport pgtype.Bool    `json:"show_planned_amount_in_report"`
}

type OperationMaterial struct {
	ID          int64       `json:"id"`
	OperationID pgtype.Int8 `json:"operation_id"`
	MaterialID  pgtype.Int8 `json:"material_id"`
}

type OperatorErrorFound struct {
	ID                 int64          `json:"id"`
	InvoiceMaterialsID pgtype.Int8    `json:"invoice_materials_id"`
	MaterialCostID     pgtype.Int8    `json:"material_cost_id"`
	Amount             pgtype.Numeric `json:"amount"`
	Notes              pgtype.Text    `json:"notes"`
}

type Permission struct {
	ID         int64       `json:"id"`
	RoleID     pgtype.Int8 `json:"role_id"`
	ResourceID pgtype.Int8 `json:"resource_id"`
	R          pgtype.Bool `json:"r"`
	W          pgtype.Bool `json:"w"`
	U          pgtype.Bool `json:"u"`
	D          pgtype.Bool `json:"d"`
}

type PermissionAction struct {
	Code      string `json:"code"`
	DisplayRu string `json:"display_ru"`
}

type Project struct {
	ID                   int64              `json:"id"`
	Name                 pgtype.Text        `json:"name"`
	Client               pgtype.Text        `json:"client"`
	Budget               pgtype.Numeric     `json:"budget"`
	BudgetCurrency       pgtype.Text        `json:"budget_currency"`
	Description          pgtype.Text        `json:"description"`
	SignedDateOfContract pgtype.Timestamptz `json:"signed_date_of_contract"`
	DateStart            pgtype.Timestamptz `json:"date_start"`
	DateEnd              pgtype.Timestamptz `json:"date_end"`
	ProjectManager       pgtype.Text        `json:"project_manager"`
}

type ProjectProgressMaterial struct {
	ID                int64              `json:"id"`
	ProjectID         pgtype.Int8        `json:"project_id"`
	MaterialCostID    pgtype.Int8        `json:"material_cost_id"`
	Received          pgtype.Numeric     `json:"received"`
	Installed         pgtype.Numeric     `json:"installed"`
	AmountInWarehouse pgtype.Numeric     `json:"amount_in_warehouse"`
	AmountInTeams     pgtype.Numeric     `json:"amount_in_teams"`
	AmountInObjects   pgtype.Numeric     `json:"amount_in_objects"`
	AmountWriteOff    pgtype.Numeric     `json:"amount_write_off"`
	Date              pgtype.Timestamptz `json:"date"`
}

type ProjectProgressOperation struct {
	ID          int64              `json:"id"`
	ProjectID   pgtype.Int8        `json:"project_id"`
	OperationID pgtype.Int8        `json:"operation_id"`
	Installed   pgtype.Numeric     `json:"installed"`
	Date        pgtype.Timestamptz `json:"date"`
}

type Resource struct {
	ID       int64       `json:"id"`
	Category pgtype.Text `json:"category"`
	Name     pgtype.Text `json:"name"`
	Url      pgtype.Text `json:"url"`
}

type ResourceType struct {
	Code      string      `json:"code"`
	Category  string      `json:"category"`
	DisplayRu string      `json:"display_ru"`
	DisplayEn pgtype.Text `json:"display_en"`
}

type Role struct {
	ID          int64       `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Code        string      `json:"code"`
}

type RoleGrant struct {
	RoleID           int64  `json:"role_id"`
	ResourceTypeCode string `json:"resource_type_code"`
	ActionCode       string `json:"action_code"`
}

type SIpObject struct {
	ID            int64       `json:"id"`
	AmountFeeders pgtype.Int8 `json:"amount_feeders"`
}

type SerialNumber struct {
	ID             int64       `json:"id"`
	ProjectID      pgtype.Int8 `json:"project_id"`
	MaterialCostID pgtype.Int8 `json:"material_cost_id"`
	Code           pgtype.Text `json:"code"`
}

type SerialNumberLocation struct {
	ID             int64       `json:"id"`
	SerialNumberID pgtype.Int8 `json:"serial_number_id"`
	ProjectID      pgtype.Int8 `json:"project_id"`
	LocationID     pgtype.Int8 `json:"location_id"`
	LocationType   pgtype.Text `json:"location_type"`
}

type SerialNumberMovement struct {
	ID             int64       `json:"id"`
	SerialNumberID pgtype.Int8 `json:"serial_number_id"`
	ProjectID      pgtype.Int8 `json:"project_id"`
	InvoiceID      pgtype.Int8 `json:"invoice_id"`
	InvoiceType    pgtype.Text `json:"invoice_type"`
	IsDefected     pgtype.Bool `json:"is_defected"`
	Confirmation   pgtype.Bool `json:"confirmation"`
}

type StvtObject struct {
	ID            int64       `json:"id"`
	VoltageClass  pgtype.Text `json:"voltage_class"`
	TtCoefficient pgtype.Text `json:"tt_coefficient"`
}

type SubstationCellNourashesSubstationObject struct {
	ID                     int64       `json:"id"`
	SubstationObjectID     pgtype.Int8 `json:"substation_object_id"`
	SubstationCellObjectID pgtype.Int8 `json:"substation_cell_object_id"`
}

type SubstationCellObject struct {
	ID int64 `json:"id"`
}

type SubstationObject struct {
	ID                   int64       `json:"id"`
	VoltageClass         pgtype.Text `json:"voltage_class"`
	NumberOfTransformers pgtype.Int8 `json:"number_of_transformers"`
}

type Team struct {
	ID           int64       `json:"id"`
	ProjectID    pgtype.Int8 `json:"project_id"`
	Number       pgtype.Text `json:"number"`
	MobileNumber pgtype.Text `json:"mobile_number"`
	Company      pgtype.Text `json:"company"`
}

type TeamLeader struct {
	ID             int64       `json:"id"`
	TeamID         pgtype.Int8 `json:"team_id"`
	LeaderWorkerID pgtype.Int8 `json:"leader_worker_id"`
}

type TpNourashesObject struct {
	ID         int64       `json:"id"`
	TpObjectID pgtype.Int8 `json:"tp_object_id"`
	TargetID   pgtype.Int8 `json:"target_id"`
	TargetType pgtype.Text `json:"target_type"`
}

type TpObject struct {
	ID           int64       `json:"id"`
	Model        pgtype.Text `json:"model"`
	VoltageClass pgtype.Text `json:"voltage_class"`
}

type User struct {
	ID       int64       `json:"id"`
	WorkerID pgtype.Int8 `json:"worker_id"`
	Username pgtype.Text `json:"username"`
	Password pgtype.Text `json:"password"`
	RoleID   pgtype.Int8 `json:"role_id"`
}

type UserAction struct {
	ID                  int64              `json:"id"`
	ActionUrl           pgtype.Text        `json:"action_url"`
	ActionType          pgtype.Text        `json:"action_type"`
	ActionID            pgtype.Int8        `json:"action_id"`
	ActionStatus        pgtype.Bool        `json:"action_status"`
	ActionStatusMessage pgtype.Text        `json:"action_status_message"`
	UserID              pgtype.Int8        `json:"user_id"`
	ProjectID           pgtype.Int8        `json:"project_id"`
	DateOfAction        pgtype.Timestamptz `json:"date_of_action"`
	HttpMethod          pgtype.Text        `json:"http_method"`
	RequestIp           pgtype.Text        `json:"request_ip"`
}

type UserInProject struct {
	ID        int64       `json:"id"`
	ProjectID pgtype.Int8 `json:"project_id"`
	UserID    pgtype.Int8 `json:"user_id"`
}

type UserRole struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	RoleID    int64              `json:"role_id"`
	ProjectID pgtype.Int8        `json:"project_id"`
	GrantedBy pgtype.Int8        `json:"granted_by"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
}

type Worker struct {
	ID                int64       `json:"id"`
	ProjectID         pgtype.Int8 `json:"project_id"`
	Name              pgtype.Text `json:"name"`
	CompanyWorkerID   pgtype.Text `json:"company_worker_id"`
	JobTitleInCompany pgtype.Text `json:"job_title_in_company"`
	JobTitleInProject pgtype.Text `json:"job_title_in_project"`
	MobileNumber      pgtype.Text `json:"mobile_number"`
}

type WorkerAttendance struct {
	ID        int64              `json:"id"`
	ProjectID pgtype.Int8        `json:"project_id"`
	WorkerID  pgtype.Int8        `json:"worker_id"`
	Start     pgtype.Timestamptz `json:"start"`
	End       pgtype.Timestamptz `json:"end"`
}
