// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: object_supervisor.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateObjectSupervisorsBatchParams struct {
	SupervisorWorkerID pgtype.Int8 `json:"supervisor_worker_id"`
	ObjectID           pgtype.Int8 `json:"object_id"`
}

const deleteObjectSupervisorsByObjectID = `-- name: DeleteObjectSupervisorsByObjectID :exec
DELETE FROM object_supervisors WHERE object_id = $1
`

func (q *Queries) DeleteObjectSupervisorsByObjectID(ctx context.Context, objectID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteObjectSupervisorsByObjectID, objectID)
	return err
}

const listObjectSupervisorsByObjectID = `-- name: ListObjectSupervisorsByObjectID :many
SELECT id, supervisor_worker_id, object_id
FROM object_supervisors
WHERE object_id = $1
`

func (q *Queries) ListObjectSupervisorsByObjectID(ctx context.Context, objectID pgtype.Int8) ([]ObjectSupervisor, error) {
	rows, err := q.db.Query(ctx, listObjectSupervisorsByObjectID, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObjectSupervisor{}
	for rows.Next() {
		var i ObjectSupervisor
		if err := rows.Scan(&i.ID, &i.SupervisorWorkerID, &i.ObjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectSupervisorsByWorkerID = `-- name: ListObjectSupervisorsByWorkerID :many
SELECT id, supervisor_worker_id, object_id
FROM object_supervisors
WHERE supervisor_worker_id = $1
`

func (q *Queries) ListObjectSupervisorsByWorkerID(ctx context.Context, supervisorWorkerID pgtype.Int8) ([]ObjectSupervisor, error) {
	rows, err := q.db.Query(ctx, listObjectSupervisorsByWorkerID, supervisorWorkerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObjectSupervisor{}
	for rows.Next() {
		var i ObjectSupervisor
		if err := rows.Scan(&i.ID, &i.SupervisorWorkerID, &i.ObjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupervisorAndObjectNamesByObjectID = `-- name: ListSupervisorAndObjectNamesByObjectID :many
SELECT
    COALESCE(objects.name, '')::text     AS object_name,
    COALESCE(objects.type, '')::text     AS object_type,
    COALESCE(workers.name, '')::text     AS supervisor_name
FROM object_supervisors
RIGHT JOIN objects ON objects.id = object_supervisors.object_id
LEFT JOIN workers ON workers.id = object_supervisors.supervisor_worker_id
WHERE objects.project_id = $1 AND objects.id = $2
`

type ListSupervisorAndObjectNamesByObjectIDParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

type ListSupervisorAndObjectNamesByObjectIDRow struct {
	ObjectName     string `json:"object_name"`
	ObjectType     string `json:"object_type"`
	SupervisorName string `json:"supervisor_name"`
}

func (q *Queries) ListSupervisorAndObjectNamesByObjectID(ctx context.Context, arg ListSupervisorAndObjectNamesByObjectIDParams) ([]ListSupervisorAndObjectNamesByObjectIDRow, error) {
	rows, err := q.db.Query(ctx, listSupervisorAndObjectNamesByObjectID, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSupervisorAndObjectNamesByObjectIDRow{}
	for rows.Next() {
		var i ListSupervisorAndObjectNamesByObjectIDRow
		if err := rows.Scan(&i.ObjectName, &i.ObjectType, &i.SupervisorName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupervisorNamesByObjectID = `-- name: ListSupervisorNamesByObjectID :many
SELECT COALESCE(workers.name, '')::text AS supervisor_name
FROM object_supervisors
INNER JOIN objects ON objects.id = object_supervisors.object_id
INNER JOIN workers ON workers.id = object_supervisors.supervisor_worker_id
WHERE objects.id = $1
`

func (q *Queries) ListSupervisorNamesByObjectID(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listSupervisorNamesByObjectID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var supervisor_name string
		if err := rows.Scan(&supervisor_name); err != nil {
			return nil, err
		}
		items = append(items, supervisor_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
