// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: object_team.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createObjectTeam = `-- name: CreateObjectTeam :exec
INSERT INTO object_teams (object_id, team_id) VALUES ($1, $2)
`

type CreateObjectTeamParams struct {
	ObjectID pgtype.Int8 `json:"object_id"`
	TeamID   pgtype.Int8 `json:"team_id"`
}

func (q *Queries) CreateObjectTeam(ctx context.Context, arg CreateObjectTeamParams) error {
	_, err := q.db.Exec(ctx, createObjectTeam, arg.ObjectID, arg.TeamID)
	return err
}

type CreateObjectTeamsBatchParams struct {
	ObjectID pgtype.Int8 `json:"object_id"`
	TeamID   pgtype.Int8 `json:"team_id"`
}

const deleteObjectTeamsByObjectID = `-- name: DeleteObjectTeamsByObjectID :exec
DELETE FROM object_teams WHERE object_id = $1
`

func (q *Queries) DeleteObjectTeamsByObjectID(ctx context.Context, objectID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteObjectTeamsByObjectID, objectID)
	return err
}

const listTeamNumbersByObjectID = `-- name: ListTeamNumbersByObjectID :many
SELECT COALESCE(teams.number, '')::text AS team_number
FROM object_teams
INNER JOIN objects ON objects.id = object_teams.object_id
INNER JOIN teams ON teams.id = object_teams.team_id
WHERE objects.id = $1
`

func (q *Queries) ListTeamNumbersByObjectID(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listTeamNumbersByObjectID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var team_number string
		if err := rows.Scan(&team_number); err != nil {
			return nil, err
		}
		items = append(items, team_number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForSelectByObjectID = `-- name: ListTeamsForSelectByObjectID :many
SELECT
    teams.id                            AS id,
    COALESCE(teams.number, '')::text    AS team_number,
    COALESCE(workers.name, '')::text    AS team_leader_name
FROM object_teams
INNER JOIN teams ON teams.id = object_teams.team_id
INNER JOIN team_leaders ON team_leaders.team_id = object_teams.team_id
INNER JOIN workers ON workers.id = team_leaders.leader_worker_id
WHERE object_teams.object_id = $1
`

type ListTeamsForSelectByObjectIDRow struct {
	ID             int64  `json:"id"`
	TeamNumber     string `json:"team_number"`
	TeamLeaderName string `json:"team_leader_name"`
}

func (q *Queries) ListTeamsForSelectByObjectID(ctx context.Context, objectID pgtype.Int8) ([]ListTeamsForSelectByObjectIDRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForSelectByObjectID, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForSelectByObjectIDRow{}
	for rows.Next() {
		var i ListTeamsForSelectByObjectIDRow
		if err := rows.Scan(&i.ID, &i.TeamNumber, &i.TeamLeaderName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
