// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOperationsFiltered = `-- name: CountOperationsFiltered :one
SELECT COUNT(*)::bigint
FROM operations
FULL JOIN operation_materials ON operation_materials.operation_id = operations.id
FULL JOIN materials ON operation_materials.material_id = materials.id
WHERE
    operations.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR operations.name = $2)
    AND (NULLIF($3::text, '') IS NULL OR operations.code = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR materials.id = $4)
`

type CountOperationsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   string      `json:"column_3"`
	Column4   int64       `json:"column_4"`
}

func (q *Queries) CountOperationsFiltered(ctx context.Context, arg CountOperationsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOperationsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (project_id, name, code, cost_prime, cost_with_customer,
                        planned_amount_for_project, show_planned_amount_in_report)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, code, cost_prime, cost_with_customer,
          planned_amount_for_project, show_planned_amount_in_report
`

type CreateOperationParams struct {
	ProjectID                 pgtype.Int8    `json:"project_id"`
	Name                      pgtype.Text    `json:"name"`
	Code                      pgtype.Text    `json:"code"`
	CostPrime                 pgtype.Numeric `json:"cost_prime"`
	CostWithCustomer          pgtype.Numeric `json:"cost_with_customer"`
	PlannedAmountForProject   pgtype.Numeric `json:"planned_amount_for_project"`
	ShowPlannedAmountInReport pgtype.Bool    `json:"show_planned_amount_in_report"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.ProjectID,
		arg.Name,
		arg.Code,
		arg.CostPrime,
		arg.CostWithCustomer,
		arg.PlannedAmountForProject,
		arg.ShowPlannedAmountInReport,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Code,
		&i.CostPrime,
		&i.CostWithCustomer,
		&i.PlannedAmountForProject,
		&i.ShowPlannedAmountInReport,
	)
	return i, err
}

const deleteOperation = `-- name: DeleteOperation :exec
DELETE FROM operations WHERE id = $1
`

func (q *Queries) DeleteOperation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOperation, id)
	return err
}

const getOperation = `-- name: GetOperation :one
SELECT id, project_id, name, code, cost_prime, cost_with_customer,
       planned_amount_for_project, show_planned_amount_in_report
FROM operations
WHERE id = $1
`

func (q *Queries) GetOperation(ctx context.Context, id int64) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Code,
		&i.CostPrime,
		&i.CostWithCustomer,
		&i.PlannedAmountForProject,
		&i.ShowPlannedAmountInReport,
	)
	return i, err
}

const getOperationByName = `-- name: GetOperationByName :one
SELECT id, project_id, name, code, cost_prime, cost_with_customer,
       planned_amount_for_project, show_planned_amount_in_report
FROM operations
WHERE name = $1 AND project_id = $2
LIMIT 1
`

type GetOperationByNameParams struct {
	Name      pgtype.Text `json:"name"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) GetOperationByName(ctx context.Context, arg GetOperationByNameParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByName, arg.Name, arg.ProjectID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Code,
		&i.CostPrime,
		&i.CostWithCustomer,
		&i.PlannedAmountForProject,
		&i.ShowPlannedAmountInReport,
	)
	return i, err
}

const listOperationsByProject = `-- name: ListOperationsByProject :many
SELECT
    operations.id                                                              AS id,
    COALESCE(operations.name, '')::text                                        AS name,
    COALESCE(operations.code, '')::text                                        AS code,
    operations.cost_prime                                                      AS cost_prime,
    operations.cost_with_customer                                              AS cost_with_customer,
    COALESCE(materials.id, 0)::bigint                                          AS material_id,
    COALESCE(materials.name, '')::text                                         AS material_name
FROM operations
FULL JOIN operation_materials ON operation_materials.operation_id = operations.id
FULL JOIN materials ON operation_materials.material_id = materials.id
WHERE operations.project_id = $1
`

type ListOperationsByProjectRow struct {
	ID               pgtype.Int8    `json:"id"`
	Name             string         `json:"name"`
	Code             string         `json:"code"`
	CostPrime        pgtype.Numeric `json:"cost_prime"`
	CostWithCustomer pgtype.Numeric `json:"cost_with_customer"`
	MaterialID       int64          `json:"material_id"`
	MaterialName     string         `json:"material_name"`
}

func (q *Queries) ListOperationsByProject(ctx context.Context, projectID pgtype.Int8) ([]ListOperationsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listOperationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationsByProjectRow{}
	for rows.Next() {
		var i ListOperationsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CostPrime,
			&i.CostWithCustomer,
			&i.MaterialID,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationsPaginated = `-- name: ListOperationsPaginated :many
SELECT
    operations.id                                                              AS id,
    COALESCE(operations.name, '')::text                                        AS name,
    COALESCE(operations.code, '')::text                                        AS code,
    operations.cost_prime                                                      AS cost_prime,
    operations.cost_with_customer                                              AS cost_with_customer,
    COALESCE(operations.planned_amount_for_project, 0)::float8                 AS planned_amount_for_project,
    COALESCE(operations.show_planned_amount_in_report, false)::boolean         AS show_planned_amount_in_report,
    COALESCE(materials.id, 0)::bigint                                          AS material_id,
    COALESCE(materials.name, '')::text                                         AS material_name
FROM operations
FULL JOIN operation_materials ON operation_materials.operation_id = operations.id
FULL JOIN materials ON operation_materials.material_id = materials.id
WHERE
    operations.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR operations.name = $2)
    AND (NULLIF($3::text, '') IS NULL OR operations.code = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR materials.id = $4)
ORDER BY operations.id DESC
LIMIT $5 OFFSET $6
`

type ListOperationsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   string      `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListOperationsPaginatedRow struct {
	ID                        pgtype.Int8    `json:"id"`
	Name                      string         `json:"name"`
	Code                      string         `json:"code"`
	CostPrime                 pgtype.Numeric `json:"cost_prime"`
	CostWithCustomer          pgtype.Numeric `json:"cost_with_customer"`
	PlannedAmountForProject   float64        `json:"planned_amount_for_project"`
	ShowPlannedAmountInReport bool           `json:"show_planned_amount_in_report"`
	MaterialID                int64          `json:"material_id"`
	MaterialName              string         `json:"material_name"`
}

func (q *Queries) ListOperationsPaginated(ctx context.Context, arg ListOperationsPaginatedParams) ([]ListOperationsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listOperationsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationsPaginatedRow{}
	for rows.Next() {
		var i ListOperationsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CostPrime,
			&i.CostWithCustomer,
			&i.PlannedAmountForProject,
			&i.ShowPlannedAmountInReport,
			&i.MaterialID,
			&i.MaterialName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationsWithoutMaterials = `-- name: ListOperationsWithoutMaterials :many
SELECT id, project_id, name, code, cost_prime, cost_with_customer,
       planned_amount_for_project, show_planned_amount_in_report
FROM operations
WHERE
    operations.project_id = $1
    AND operations.id NOT IN (SELECT operation_materials.operation_id FROM operation_materials)
`

func (q *Queries) ListOperationsWithoutMaterials(ctx context.Context, projectID pgtype.Int8) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperationsWithoutMaterials, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Code,
			&i.CostPrime,
			&i.CostWithCustomer,
			&i.PlannedAmountForProject,
			&i.ShowPlannedAmountInReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOperation = `-- name: UpdateOperation :exec
UPDATE operations
SET project_id = $2, name = $3, code = $4, cost_prime = $5, cost_with_customer = $6,
    planned_amount_for_project = $7, show_planned_amount_in_report = $8
WHERE id = $1
`

type UpdateOperationParams struct {
	ID                        int64          `json:"id"`
	ProjectID                 pgtype.Int8    `json:"project_id"`
	Name                      pgtype.Text    `json:"name"`
	Code                      pgtype.Text    `json:"code"`
	CostPrime                 pgtype.Numeric `json:"cost_prime"`
	CostWithCustomer          pgtype.Numeric `json:"cost_with_customer"`
	PlannedAmountForProject   pgtype.Numeric `json:"planned_amount_for_project"`
	ShowPlannedAmountInReport pgtype.Bool    `json:"show_planned_amount_in_report"`
}

func (q *Queries) UpdateOperation(ctx context.Context, arg UpdateOperationParams) error {
	_, err := q.db.Exec(ctx, updateOperation,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Code,
		arg.CostPrime,
		arg.CostWithCustomer,
		arg.PlannedAmountForProject,
		arg.ShowPlannedAmountInReport,
	)
	return err
}
