// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation_material.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperationMaterial = `-- name: CreateOperationMaterial :exec
INSERT INTO operation_materials (operation_id, material_id) VALUES ($1, $2)
`

type CreateOperationMaterialParams struct {
	OperationID pgtype.Int8 `json:"operation_id"`
	MaterialID  pgtype.Int8 `json:"material_id"`
}

func (q *Queries) CreateOperationMaterial(ctx context.Context, arg CreateOperationMaterialParams) error {
	_, err := q.db.Exec(ctx, createOperationMaterial, arg.OperationID, arg.MaterialID)
	return err
}

const deleteOperationMaterialsByOperationID = `-- name: DeleteOperationMaterialsByOperationID :exec
DELETE FROM operation_materials WHERE operation_id = $1
`

func (q *Queries) DeleteOperationMaterialsByOperationID(ctx context.Context, operationID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteOperationMaterialsByOperationID, operationID)
	return err
}

const getOperationMaterialByOperationID = `-- name: GetOperationMaterialByOperationID :one
SELECT id, operation_id, material_id
FROM operation_materials
WHERE operation_id = $1
LIMIT 1
`

func (q *Queries) GetOperationMaterialByOperationID(ctx context.Context, operationID pgtype.Int8) (OperationMaterial, error) {
	row := q.db.QueryRow(ctx, getOperationMaterialByOperationID, operationID)
	var i OperationMaterial
	err := row.Scan(&i.ID, &i.OperationID, &i.MaterialID)
	return i, err
}
