// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (role_id, resource_id, r, w, u, d)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, role_id, resource_id, r, w, u, d
`

type CreatePermissionParams struct {
	RoleID     pgtype.Int8 `json:"role_id"`
	ResourceID pgtype.Int8 `json:"resource_id"`
	R          pgtype.Bool `json:"r"`
	W          pgtype.Bool `json:"w"`
	U          pgtype.Bool `json:"u"`
	D          pgtype.Bool `json:"d"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.RoleID,
		arg.ResourceID,
		arg.R,
		arg.W,
		arg.U,
		arg.D,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ResourceID,
		&i.R,
		&i.W,
		&i.U,
		&i.D,
	)
	return i, err
}

type CreatePermissionsBatchParams struct {
	RoleID     pgtype.Int8 `json:"role_id"`
	ResourceID pgtype.Int8 `json:"resource_id"`
	R          pgtype.Bool `json:"r"`
	W          pgtype.Bool `json:"w"`
	U          pgtype.Bool `json:"u"`
	D          pgtype.Bool `json:"d"`
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermissionByResourceURL = `-- name: GetPermissionByResourceURL :one
SELECT permissions.id, permissions.role_id, permissions.resource_id,
       permissions.r, permissions.w, permissions.u, permissions.d
FROM permissions
INNER JOIN roles ON roles.id = permissions.role_id
INNER JOIN resources ON resources.id = permissions.resource_id
WHERE permissions.role_id = $1 AND resources.url = $2
`

type GetPermissionByResourceURLParams struct {
	RoleID pgtype.Int8 `json:"role_id"`
	Url    pgtype.Text `json:"url"`
}

func (q *Queries) GetPermissionByResourceURL(ctx context.Context, arg GetPermissionByResourceURLParams) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByResourceURL, arg.RoleID, arg.Url)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ResourceID,
		&i.R,
		&i.W,
		&i.U,
		&i.D,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, role_id, resource_id, r, w, u, d
FROM permissions
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ResourceID,
			&i.R,
			&i.W,
			&i.U,
			&i.D,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByRoleID = `-- name: ListPermissionsByRoleID :many
SELECT id, role_id, resource_id, r, w, u, d
FROM permissions
WHERE role_id = $1 AND (r OR w OR u OR d)
`

func (q *Queries) ListPermissionsByRoleID(ctx context.Context, roleID pgtype.Int8) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.ResourceID,
			&i.R,
			&i.W,
			&i.U,
			&i.D,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionsByRoleName = `-- name: ListUserPermissionsByRoleName :many
SELECT
    resources.name AS resource_name,
    resources.url  AS resource_url,
    permissions.r,
    permissions.w,
    permissions.u,
    permissions.d
FROM permissions
INNER JOIN roles ON roles.id = permissions.role_id
INNER JOIN resources ON resources.id = permissions.resource_id
WHERE roles.name = $1
`

type ListUserPermissionsByRoleNameRow struct {
	ResourceName pgtype.Text `json:"resource_name"`
	ResourceUrl  pgtype.Text `json:"resource_url"`
	R            pgtype.Bool `json:"r"`
	W            pgtype.Bool `json:"w"`
	U            pgtype.Bool `json:"u"`
	D            pgtype.Bool `json:"d"`
}

func (q *Queries) ListUserPermissionsByRoleName(ctx context.Context, name pgtype.Text) ([]ListUserPermissionsByRoleNameRow, error) {
	rows, err := q.db.Query(ctx, listUserPermissionsByRoleName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPermissionsByRoleNameRow{}
	for rows.Next() {
		var i ListUserPermissionsByRoleNameRow
		if err := rows.Scan(
			&i.ResourceName,
			&i.ResourceUrl,
			&i.R,
			&i.W,
			&i.U,
			&i.D,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET role_id = $2, resource_id = $3, r = $4, w = $5, u = $6, d = $7
WHERE id = $1
RETURNING id, role_id, resource_id, r, w, u, d
`

type UpdatePermissionParams struct {
	ID         int64       `json:"id"`
	RoleID     pgtype.Int8 `json:"role_id"`
	ResourceID pgtype.Int8 `json:"resource_id"`
	R          pgtype.Bool `json:"r"`
	W          pgtype.Bool `json:"w"`
	U          pgtype.Bool `json:"u"`
	D          pgtype.Bool `json:"d"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission,
		arg.ID,
		arg.RoleID,
		arg.ResourceID,
		arg.R,
		arg.W,
		arg.U,
		arg.D,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.ResourceID,
		&i.R,
		&i.W,
		&i.U,
		&i.D,
	)
	return i, err
}
