// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, client, budget, budget_currency, description,
                      signed_date_of_contract, date_start, date_end, project_manager)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, client, budget, budget_currency, description,
          signed_date_of_contract, date_start, date_end, project_manager
`

type CreateProjectParams struct {
	Name                 pgtype.Text        `json:"name"`
	Client               pgtype.Text        `json:"client"`
	Budget               pgtype.Numeric     `json:"budget"`
	BudgetCurrency       pgtype.Text        `json:"budget_currency"`
	Description          pgtype.Text        `json:"description"`
	SignedDateOfContract pgtype.Timestamptz `json:"signed_date_of_contract"`
	DateStart            pgtype.Timestamptz `json:"date_start"`
	DateEnd              pgtype.Timestamptz `json:"date_end"`
	ProjectManager       pgtype.Text        `json:"project_manager"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Client,
		arg.Budget,
		arg.BudgetCurrency,
		arg.Description,
		arg.SignedDateOfContract,
		arg.DateStart,
		arg.DateEnd,
		arg.ProjectManager,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Client,
		&i.Budget,
		&i.BudgetCurrency,
		&i.Description,
		&i.SignedDateOfContract,
		&i.DateStart,
		&i.DateEnd,
		&i.ProjectManager,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, client, budget, budget_currency, description,
       signed_date_of_contract, date_start, date_end, project_manager
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Client,
		&i.Budget,
		&i.BudgetCurrency,
		&i.Description,
		&i.SignedDateOfContract,
		&i.DateStart,
		&i.DateEnd,
		&i.ProjectManager,
	)
	return i, err
}

const getProjectName = `-- name: GetProjectName :one
SELECT COALESCE(name, '')::text AS name FROM projects WHERE id = $1
`

func (q *Queries) GetProjectName(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getProjectName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, client, budget, budget_currency, description,
       signed_date_of_contract, date_start, date_end, project_manager
FROM projects
ORDER BY id DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Client,
			&i.Budget,
			&i.BudgetCurrency,
			&i.Description,
			&i.SignedDateOfContract,
			&i.DateStart,
			&i.DateEnd,
			&i.ProjectManager,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsExcludeAdmin = `-- name: ListProjectsExcludeAdmin :many
SELECT id, name, client, budget, budget_currency, description,
       signed_date_of_contract, date_start, date_end, project_manager
FROM projects
WHERE name <> 'Администрирование'
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListProjectsExcludeAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProjectsExcludeAdmin(ctx context.Context, arg ListProjectsExcludeAdminParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsExcludeAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Client,
			&i.Budget,
			&i.BudgetCurrency,
			&i.Description,
			&i.SignedDateOfContract,
			&i.DateStart,
			&i.DateEnd,
			&i.ProjectManager,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, client = $3, budget = $4, budget_currency = $5, description = $6,
    signed_date_of_contract = $7, date_start = $8, date_end = $9, project_manager = $10
WHERE id = $1
RETURNING id, name, client, budget, budget_currency, description,
          signed_date_of_contract, date_start, date_end, project_manager
`

type UpdateProjectParams struct {
	ID                   int64              `json:"id"`
	Name                 pgtype.Text        `json:"name"`
	Client               pgtype.Text        `json:"client"`
	Budget               pgtype.Numeric     `json:"budget"`
	BudgetCurrency       pgtype.Text        `json:"budget_currency"`
	Description          pgtype.Text        `json:"description"`
	SignedDateOfContract pgtype.Timestamptz `json:"signed_date_of_contract"`
	DateStart            pgtype.Timestamptz `json:"date_start"`
	DateEnd              pgtype.Timestamptz `json:"date_end"`
	ProjectManager       pgtype.Text        `json:"project_manager"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Client,
		arg.Budget,
		arg.BudgetCurrency,
		arg.Description,
		arg.SignedDateOfContract,
		arg.DateStart,
		arg.DateEnd,
		arg.ProjectManager,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Client,
		&i.Budget,
		&i.BudgetCurrency,
		&i.Description,
		&i.SignedDateOfContract,
		&i.DateStart,
		&i.DateEnd,
		&i.ProjectManager,
	)
	return i, err
}
