// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConfirmInvoiceInput(ctx context.Context, id int64) error
	ConfirmInvoiceOutput(ctx context.Context, id int64) error
	ConfirmInvoiceOutputOutOfProject(ctx context.Context, id int64) error
	ConfirmInvoiceReturn(ctx context.Context, id int64) error
	// After invoice_output confirmation, serial_number_locations rows for the
	// invoice's serial numbers are flipped from warehouse to team.
	ConfirmSerialNumberLocationsByOutputInvoice(ctx context.Context, arg ConfirmSerialNumberLocationsByOutputInvoiceParams) error
	// After invoice_return confirmation, serial_number_locations rows for the
	// invoice's serial numbers are flipped to the team acceptor.
	ConfirmSerialNumberLocationsByReturnInvoice(ctx context.Context, arg ConfirmSerialNumberLocationsByReturnInvoiceParams) error
	ConfirmSerialNumberMovementsByInvoice(ctx context.Context, arg ConfirmSerialNumberMovementsByInvoiceParams) error
	CountDistricts(ctx context.Context, projectID pgtype.Int8) (int64, error)
	CountInvoiceCorrections(ctx context.Context, arg CountInvoiceCorrectionsParams) (int64, error)
	CountInvoiceInputCreatorInvoices(ctx context.Context, arg CountInvoiceInputCreatorInvoicesParams) (int64, error)
	CountInvoiceInputs(ctx context.Context, projectID pgtype.Int8) (int64, error)
	CountInvoiceInputsByMaterials(ctx context.Context, arg CountInvoiceInputsByMaterialsParams) (int64, error)
	CountInvoiceInputsFiltered(ctx context.Context, arg CountInvoiceInputsFilteredParams) (int64, error)
	CountInvoiceObjectsByProject(ctx context.Context, projectID pgtype.Int8) (int64, error)
	CountInvoiceOutputCreatorInvoices(ctx context.Context, arg CountInvoiceOutputCreatorInvoicesParams) (int64, error)
	CountInvoiceOutputOutOfProjects(ctx context.Context, arg CountInvoiceOutputOutOfProjectsParams) (int64, error)
	CountInvoiceOutputs(ctx context.Context, projectID pgtype.Int8) (int64, error)
	CountInvoiceOutputsByProject(ctx context.Context, projectID pgtype.Int8) (int64, error)
	CountInvoiceReturns(ctx context.Context, projectID pgtype.Int8) (int64, error)
	CountInvoiceReturnsBasedOnType(ctx context.Context, arg CountInvoiceReturnsBasedOnTypeParams) (int64, error)
	CountInvoiceReturnsByProject(ctx context.Context, projectID pgtype.Int8) (int64, error)
	CountInvoiceWriteOffs(ctx context.Context, projectID pgtype.Int8) (int64, error)
	CountInvoiceWriteOffsFiltered(ctx context.Context, arg CountInvoiceWriteOffsFilteredParams) (int64, error)
	CountKL04KVObjectsFiltered(ctx context.Context, arg CountKL04KVObjectsFilteredParams) (int64, error)
	CountMJDObjectsFiltered(ctx context.Context, arg CountMJDObjectsFilteredParams) (int64, error)
	CountMaterialCostsFiltered(ctx context.Context, arg CountMaterialCostsFilteredParams) (int64, error)
	CountMaterialInInvoices(ctx context.Context, id int64) ([]CountMaterialInInvoicesRow, error)
	CountMaterialInLocations(ctx context.Context, id int64) ([]CountMaterialInLocationsRow, error)
	CountMaterialLocations(ctx context.Context) (int64, error)
	CountMaterialsFiltered(ctx context.Context, arg CountMaterialsFilteredParams) (int64, error)
	CountObjects(ctx context.Context) (int64, error)
	CountOperationsFiltered(ctx context.Context, arg CountOperationsFilteredParams) (int64, error)
	CountProjects(ctx context.Context) (int64, error)
	CountSIPObjectsFiltered(ctx context.Context, arg CountSIPObjectsFilteredParams) (int64, error)
	CountSTVTObjectsFiltered(ctx context.Context, arg CountSTVTObjectsFilteredParams) (int64, error)
	CountSubstationCellObjectsFiltered(ctx context.Context, arg CountSubstationCellObjectsFilteredParams) (int64, error)
	CountSubstationObjectsFiltered(ctx context.Context, arg CountSubstationObjectsFilteredParams) (int64, error)
	CountTPObjectsFiltered(ctx context.Context, arg CountTPObjectsFilteredParams) (int64, error)
	CountTeamsFiltered(ctx context.Context, arg CountTeamsFilteredParams) (int64, error)
	CountUserActionsPaginated(ctx context.Context, arg CountUserActionsPaginatedParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkerAttendances(ctx context.Context, projectID pgtype.Int8) (int64, error)
	CountWorkersFiltered(ctx context.Context, arg CountWorkersFilteredParams) (int64, error)
	CreateDistrict(ctx context.Context, arg CreateDistrictParams) (District, error)
	CreateInvoiceCount(ctx context.Context, arg CreateInvoiceCountParams) error
	CreateInvoiceInput(ctx context.Context, arg CreateInvoiceInputParams) (InvoiceInput, error)
	CreateInvoiceMaterialsBatch(ctx context.Context, arg []CreateInvoiceMaterialsBatchParams) (int64, error)
	CreateInvoiceObject(ctx context.Context, arg CreateInvoiceObjectParams) (InvoiceObject, error)
	CreateInvoiceObjectOperator(ctx context.Context, arg CreateInvoiceObjectOperatorParams) error
	CreateInvoiceOperationsBatch(ctx context.Context, arg []CreateInvoiceOperationsBatchParams) (int64, error)
	CreateInvoiceOutput(ctx context.Context, arg CreateInvoiceOutputParams) (InvoiceOutput, error)
	CreateInvoiceOutputOutOfProject(ctx context.Context, arg CreateInvoiceOutputOutOfProjectParams) (InvoiceOutputOutOfProject, error)
	CreateInvoiceReturn(ctx context.Context, arg CreateInvoiceReturnParams) (InvoiceReturn, error)
	CreateInvoiceWriteOff(ctx context.Context, arg CreateInvoiceWriteOffParams) (InvoiceWriteOff, error)
	CreateKL04KVObjectDetail(ctx context.Context, arg CreateKL04KVObjectDetailParams) (Kl04KvObject, error)
	CreateMJDObjectDetail(ctx context.Context, arg CreateMJDObjectDetailParams) (MjdObject, error)
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error)
	CreateMaterialCost(ctx context.Context, arg CreateMaterialCostParams) (MaterialCost, error)
	CreateMaterialCostsBatch(ctx context.Context, arg []CreateMaterialCostsBatchParams) (int64, error)
	CreateMaterialDefect(ctx context.Context, arg CreateMaterialDefectParams) (MaterialDefect, error)
	CreateMaterialLocation(ctx context.Context, arg CreateMaterialLocationParams) (MaterialLocation, error)
	CreateMaterialsBatch(ctx context.Context, arg []CreateMaterialsBatchParams) (int64, error)
	CreateObject(ctx context.Context, arg CreateObjectParams) (Object, error)
	CreateObjectSupervisorsBatch(ctx context.Context, arg []CreateObjectSupervisorsBatchParams) (int64, error)
	CreateObjectTeam(ctx context.Context, arg CreateObjectTeamParams) error
	CreateObjectTeamsBatch(ctx context.Context, arg []CreateObjectTeamsBatchParams) (int64, error)
	CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error)
	CreateOperationMaterial(ctx context.Context, arg CreateOperationMaterialParams) error
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreatePermissionsBatch(ctx context.Context, arg []CreatePermissionsBatchParams) (int64, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSIPObjectDetail(ctx context.Context, amountFeeders pgtype.Int8) (SIpObject, error)
	CreateSTVTObjectDetail(ctx context.Context, arg CreateSTVTObjectDetailParams) (StvtObject, error)
	CreateSerialNumber(ctx context.Context, arg CreateSerialNumberParams) (SerialNumber, error)
	CreateSerialNumberLocationsBatch(ctx context.Context, arg []CreateSerialNumberLocationsBatchParams) (int64, error)
	CreateSerialNumberMovementsBatch(ctx context.Context, arg []CreateSerialNumberMovementsBatchParams) (int64, error)
	CreateSubstationCellNourash(ctx context.Context, arg CreateSubstationCellNourashParams) error
	// substation_cell_objects has only an id column.
	CreateSubstationCellObjectDetail(ctx context.Context) (int64, error)
	CreateSubstationObjectDetail(ctx context.Context, arg CreateSubstationObjectDetailParams) (SubstationObject, error)
	CreateTPNourashesObjectsBatch(ctx context.Context, arg []CreateTPNourashesObjectsBatchParams) (int64, error)
	CreateTPObjectDetail(ctx context.Context, arg CreateTPObjectDetailParams) (TpObject, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamLeader(ctx context.Context, arg CreateTeamLeaderParams) error
	CreateTeamLeadersBatch(ctx context.Context, arg []CreateTeamLeadersBatchParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAction(ctx context.Context, arg CreateUserActionParams) (CreateUserActionRow, error)
	CreateUserInProject(ctx context.Context, arg CreateUserInProjectParams) error
	CreateUserInProjectsBatch(ctx context.Context, arg []CreateUserInProjectsBatchParams) (int64, error)
	CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error)
	CreateWorkerAttendancesBatch(ctx context.Context, arg []CreateWorkerAttendancesBatchParams) (int64, error)
	CreateWorkersBatch(ctx context.Context, arg []CreateWorkersBatchParams) (int64, error)
	DeleteDistrict(ctx context.Context, id int64) error
	DeleteInvoiceInput(ctx context.Context, id int64) error
	DeleteInvoiceMaterialsByInvoice(ctx context.Context, arg DeleteInvoiceMaterialsByInvoiceParams) error
	DeleteInvoiceObject(ctx context.Context, id int64) error
	DeleteInvoiceOutput(ctx context.Context, id int64) error
	DeleteInvoiceOutputOutOfProject(ctx context.Context, id int64) error
	DeleteInvoiceReturn(ctx context.Context, id int64) error
	DeleteInvoiceWriteOff(ctx context.Context, id int64) error
	DeleteKL04KVObjectDetail(ctx context.Context, id int64) error
	DeleteKL04KVObjectSupervisorsCascade(ctx context.Context, arg DeleteKL04KVObjectSupervisorsCascadeParams) error
	DeleteKL04KVObjectTPNourashesCascade(ctx context.Context, arg DeleteKL04KVObjectTPNourashesCascadeParams) error
	DeleteKL04KVObjectTeamsCascade(ctx context.Context, arg DeleteKL04KVObjectTeamsCascadeParams) error
	DeleteMJDObjectDetail(ctx context.Context, id int64) error
	DeleteMJDObjectSupervisorsCascade(ctx context.Context, arg DeleteMJDObjectSupervisorsCascadeParams) error
	DeleteMJDObjectTPNourashesCascade(ctx context.Context, arg DeleteMJDObjectTPNourashesCascadeParams) error
	DeleteMJDObjectTeamsCascade(ctx context.Context, arg DeleteMJDObjectTeamsCascadeParams) error
	DeleteMaterial(ctx context.Context, id int64) error
	DeleteMaterialCost(ctx context.Context, id int64) error
	DeleteMaterialLocation(ctx context.Context, id int64) error
	DeleteObject(ctx context.Context, id int64) error
	DeleteObjectByKL04KVDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error
	DeleteObjectByMJDDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error
	DeleteObjectBySIPDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error
	DeleteObjectBySTVTDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error
	DeleteObjectBySubstationCellDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error
	DeleteObjectBySubstationDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error
	DeleteObjectByTPObjectDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error
	DeleteObjectSupervisorsByObjectID(ctx context.Context, objectID pgtype.Int8) error
	DeleteObjectTeamsByObjectID(ctx context.Context, objectID pgtype.Int8) error
	DeleteOperation(ctx context.Context, id int64) error
	DeleteOperationMaterialsByOperationID(ctx context.Context, operationID pgtype.Int8) error
	DeletePermission(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteSIPObjectDetail(ctx context.Context, id int64) error
	DeleteSIPObjectSupervisorsCascade(ctx context.Context, arg DeleteSIPObjectSupervisorsCascadeParams) error
	DeleteSIPObjectTeamsCascade(ctx context.Context, arg DeleteSIPObjectTeamsCascadeParams) error
	DeleteSTVTObjectDetail(ctx context.Context, id int64) error
	DeleteSTVTObjectSupervisorsCascade(ctx context.Context, arg DeleteSTVTObjectSupervisorsCascadeParams) error
	DeleteSTVTObjectTeamsCascade(ctx context.Context, arg DeleteSTVTObjectTeamsCascadeParams) error
	DeleteSerialNumber(ctx context.Context, id int64) error
	DeleteSerialNumberMovementsByInvoice(ctx context.Context, arg DeleteSerialNumberMovementsByInvoiceParams) error
	DeleteSubstationCellNourashesByCellObjectID(ctx context.Context, substationCellObjectID pgtype.Int8) error
	DeleteSubstationCellObjectDetail(ctx context.Context, id int64) error
	DeleteSubstationCellObjectNourashesCascade(ctx context.Context, arg DeleteSubstationCellObjectNourashesCascadeParams) error
	// The GORM-era SQL had a copy-paste typo (`stvt_objects.id` instead of
	// `substation_cell_objects.id`) that would have raised "missing
	// FROM-clause entry" at execution time. Fixed during phase 6.
	DeleteSubstationCellObjectSupervisorsCascade(ctx context.Context, arg DeleteSubstationCellObjectSupervisorsCascadeParams) error
	DeleteSubstationCellObjectTeamsCascade(ctx context.Context, arg DeleteSubstationCellObjectTeamsCascadeParams) error
	DeleteSubstationObjectDetail(ctx context.Context, id int64) error
	DeleteSubstationObjectSupervisorsCascade(ctx context.Context, arg DeleteSubstationObjectSupervisorsCascadeParams) error
	DeleteSubstationObjectTeamsCascade(ctx context.Context, arg DeleteSubstationObjectTeamsCascadeParams) error
	DeleteTPNourashesObjectsByTarget(ctx context.Context, arg DeleteTPNourashesObjectsByTargetParams) error
	DeleteTPObjectDetail(ctx context.Context, id int64) error
	DeleteTPObjectSupervisorsCascade(ctx context.Context, arg DeleteTPObjectSupervisorsCascadeParams) error
	DeleteTPObjectTeamsCascade(ctx context.Context, arg DeleteTPObjectTeamsCascadeParams) error
	DeleteTeam(ctx context.Context, id int64) error
	DeleteTeamLeadersByTeamID(ctx context.Context, teamID pgtype.Int8) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserInProjectsByProjectID(ctx context.Context, projectID pgtype.Int8) error
	DeleteUserInProjectsByUserID(ctx context.Context, userID pgtype.Int8) error
	DeleteWorker(ctx context.Context, id int64) error
	GetAuctionDataForPrivate(ctx context.Context, id int64) ([]GetAuctionDataForPrivateRow, error)
	GetAuctionDataForPublic(ctx context.Context, id int64) ([]GetAuctionDataForPublicRow, error)
	GetDistrict(ctx context.Context, id int64) (District, error)
	GetDistrictByName(ctx context.Context, name pgtype.Text) (District, error)
	GetInvoiceCount(ctx context.Context, arg GetInvoiceCountParams) (int64, error)
	GetInvoiceInput(ctx context.Context, id int64) (InvoiceInput, error)
	GetInvoiceMaterialByMaterialCostID(ctx context.Context, arg GetInvoiceMaterialByMaterialCostIDParams) (InvoiceMaterial, error)
	GetInvoiceObject(ctx context.Context, id int64) (InvoiceObject, error)
	GetInvoiceObjectDescriptiveDataByID(ctx context.Context, arg GetInvoiceObjectDescriptiveDataByIDParams) (GetInvoiceObjectDescriptiveDataByIDRow, error)
	GetInvoiceOutput(ctx context.Context, id int64) (InvoiceOutput, error)
	GetInvoiceOutputByDeliveryCode(ctx context.Context, arg GetInvoiceOutputByDeliveryCodeParams) (InvoiceOutput, error)
	GetInvoiceOutputDataForExcel(ctx context.Context, id int64) (GetInvoiceOutputDataForExcelRow, error)
	GetInvoiceOutputOutOfProject(ctx context.Context, id int64) (InvoiceOutputOutOfProject, error)
	GetInvoiceOutputOutOfProjectByDeliveryCode(ctx context.Context, arg GetInvoiceOutputOutOfProjectByDeliveryCodeParams) (InvoiceOutputOutOfProject, error)
	GetInvoiceReturn(ctx context.Context, id int64) (InvoiceReturn, error)
	GetInvoiceReturnByDeliveryCode(ctx context.Context, arg GetInvoiceReturnByDeliveryCodeParams) (InvoiceReturn, error)
	GetInvoiceWriteOff(ctx context.Context, id int64) (InvoiceWriteOff, error)
	GetKL04KVObjectDetail(ctx context.Context, id int64) (Kl04KvObject, error)
	GetMJDObjectDetail(ctx context.Context, id int64) (MjdObject, error)
	GetMaterial(ctx context.Context, id int64) (Material, error)
	GetMaterialByMaterialCostID(ctx context.Context, id int64) (Material, error)
	GetMaterialByProjectAndName(ctx context.Context, arg GetMaterialByProjectAndNameParams) (Material, error)
	GetMaterialCost(ctx context.Context, id int64) (MaterialCost, error)
	GetMaterialCostByCostM19AndMaterialID(ctx context.Context, arg GetMaterialCostByCostM19AndMaterialIDParams) (MaterialCost, error)
	GetMaterialDefectByMaterialLocationID(ctx context.Context, materialLocationID pgtype.Int8) (MaterialDefect, error)
	GetMaterialLocation(ctx context.Context, id int64) (MaterialLocation, error)
	// Used by invoice_correction's GetByMaterialCostIDOrCreate idiom: looks up
	// a material_locations row matching all four scope columns.
	GetMaterialLocationByCostAndLocation(ctx context.Context, arg GetMaterialLocationByCostAndLocationParams) (MaterialLocation, error)
	GetObject(ctx context.Context, id int64) (Object, error)
	GetObjectByName(ctx context.Context, name pgtype.Text) (Object, error)
	GetOperation(ctx context.Context, id int64) (Operation, error)
	GetOperationByName(ctx context.Context, arg GetOperationByNameParams) (Operation, error)
	GetOperationMaterialByOperationID(ctx context.Context, operationID pgtype.Int8) (OperationMaterial, error)
	GetPermissionByResourceURL(ctx context.Context, arg GetPermissionByResourceURLParams) (Permission, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectName(ctx context.Context, id int64) (string, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetSIPObjectDetail(ctx context.Context, id int64) (SIpObject, error)
	GetSTVTObjectDetail(ctx context.Context, id int64) (StvtObject, error)
	GetSerialNumberCodesByMaterialIDAndLocation(ctx context.Context, arg GetSerialNumberCodesByMaterialIDAndLocationParams) ([]string, error)
	GetSubstationNameByCellObjectID(ctx context.Context, substationCellObjectID pgtype.Int8) (string, error)
	GetSubstationObjectByName(ctx context.Context, name pgtype.Text) (Object, error)
	GetSubstationObjectDetail(ctx context.Context, id int64) (SubstationObject, error)
	GetTPObjectDetail(ctx context.Context, id int64) (TpObject, error)
	GetTeam(ctx context.Context, id int64) (Team, error)
	GetTeamByNumber(ctx context.Context, number pgtype.Text) (Team, error)
	// Used by invoice_return.GetMaterialAmountByMaterialID — sums material_locations.amount
	// across all material_costs of the given material in the given location, where amount > 0.
	GetTotalAmountInLocation(ctx context.Context, arg GetTotalAmountInLocationParams) (pgtype.Numeric, error)
	GetTotalAmountInTeamsByTeamNumber(ctx context.Context, arg GetTotalAmountInTeamsByTeamNumberParams) (pgtype.Numeric, error)
	GetTotalAmountInWarehouse(ctx context.Context, arg GetTotalAmountInWarehouseParams) (pgtype.Numeric, error)
	GetUniqueMaterialTotalAmount(ctx context.Context, arg GetUniqueMaterialTotalAmountParams) (pgtype.Numeric, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error)
	GetWorker(ctx context.Context, id int64) (Worker, error)
	GetWorkerByCompanyID(ctx context.Context, companyWorkerID pgtype.Text) (Worker, error)
	GetWorkerByName(ctx context.Context, name pgtype.Text) (Worker, error)
	IncrementInvoiceCount(ctx context.Context, arg IncrementInvoiceCountParams) error
	IncrementInvoiceCountBy(ctx context.Context, arg IncrementInvoiceCountByParams) error
	InvoiceMaterialDataForProgressReport(ctx context.Context, projectID pgtype.Int8) ([]InvoiceMaterialDataForProgressReportRow, error)
	InvoiceOperationDataForProgressReport(ctx context.Context, projectID pgtype.Int8) ([]InvoiceOperationDataForProgressReportRow, error)
	InvoiceOperationDataForProgressReportInGivenDate(ctx context.Context, arg InvoiceOperationDataForProgressReportInGivenDateParams) ([]InvoiceOperationDataForProgressReportInGivenDateRow, error)
	ListBalanceReportData(ctx context.Context, arg ListBalanceReportDataParams) ([]ListBalanceReportDataRow, error)
	ListDistinctTeamCompanies(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListDistinctTeamMobileNumbers(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListDistinctTeamNumbers(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListDistinctWorkerCompanyIDs(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListDistinctWorkerJobTitlesInCompany(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListDistinctWorkerJobTitlesInProject(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListDistinctWorkerMobileNumbers(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListDistinctWorkerNames(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListDistricts(ctx context.Context, projectID pgtype.Int8) ([]District, error)
	ListDistrictsPaginated(ctx context.Context, arg ListDistrictsPaginatedParams) ([]District, error)
	// Permissions v2 resolver query. Returns one row per (project_id, resource,
	// action) the user is granted via any role assignment. project_id IS NULL
	// means a global grant; non-null project_id is a per-project grant. The
	// resolver merges these against the request's project_id.
	ListEffectivePermissionsForUser(ctx context.Context, userID int64) ([]ListEffectivePermissionsForUserRow, error)
	ListInvoiceCorrectionMaterialsByInvoiceObjectID(ctx context.Context, invoiceID pgtype.Int8) ([]ListInvoiceCorrectionMaterialsByInvoiceObjectIDRow, error)
	ListInvoiceCorrectionObjectsForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceCorrectionObjectsForSearchRow, error)
	ListInvoiceCorrectionOperationsByInvoiceObjectID(ctx context.Context, invoiceID pgtype.Int8) ([]ListInvoiceCorrectionOperationsByInvoiceObjectIDRow, error)
	ListInvoiceCorrectionReportData(ctx context.Context, arg ListInvoiceCorrectionReportDataParams) ([]ListInvoiceCorrectionReportDataRow, error)
	// The GORM repo's query had a typo (`team.id` instead of `teams.id`)
	// and would have raised "missing FROM-clause entry" at execution time.
	// Fixed in place since preserving would mean this endpoint always errors.
	ListInvoiceCorrectionSerialNumberOfMaterialInTeam(ctx context.Context, arg ListInvoiceCorrectionSerialNumberOfMaterialInTeamParams) ([]string, error)
	ListInvoiceCorrectionTeamsForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceCorrectionTeamsForSearchRow, error)
	ListInvoiceCorrectionUniqueObjects(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceCorrectionUniqueObjectsRow, error)
	ListInvoiceCorrectionUniqueTeams(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceCorrectionUniqueTeamsRow, error)
	ListInvoiceCorrectionsPaginated(ctx context.Context, arg ListInvoiceCorrectionsPaginatedParams) ([]ListInvoiceCorrectionsPaginatedRow, error)
	ListInvoiceInputAllDeliveryCodes(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListInvoiceInputAllMaterialsThatExist(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputAllMaterialsThatExistRow, error)
	ListInvoiceInputAllReleasedWorkers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputAllReleasedWorkersRow, error)
	ListInvoiceInputAllWarehouseManagers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputAllWarehouseManagersRow, error)
	ListInvoiceInputMaterialsForEdit(ctx context.Context, arg ListInvoiceInputMaterialsForEditParams) ([]ListInvoiceInputMaterialsForEditRow, error)
	ListInvoiceInputReportFilterData(ctx context.Context, arg ListInvoiceInputReportFilterDataParams) ([]ListInvoiceInputReportFilterDataRow, error)
	ListInvoiceInputUniqueCreators(ctx context.Context, projectID pgtype.Int8) ([]int64, error)
	ListInvoiceInputUniqueDeliveryCodes(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputUniqueDeliveryCodesRow, error)
	ListInvoiceInputUniqueReleasedWorkers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputUniqueReleasedWorkersRow, error)
	ListInvoiceInputUniqueWarehouseManagers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceInputUniqueWarehouseManagersRow, error)
	ListInvoiceInputs(ctx context.Context) ([]InvoiceInput, error)
	ListInvoiceInputsPaginated(ctx context.Context, arg ListInvoiceInputsPaginatedParams) ([]InvoiceInput, error)
	ListInvoiceInputsPaginatedByMaterials(ctx context.Context, arg ListInvoiceInputsPaginatedByMaterialsParams) ([]ListInvoiceInputsPaginatedByMaterialsRow, error)
	ListInvoiceInputsPaginatedFiltered(ctx context.Context, arg ListInvoiceInputsPaginatedFilteredParams) ([]ListInvoiceInputsPaginatedFilteredRow, error)
	ListInvoiceMaterialsByInvoice(ctx context.Context, arg ListInvoiceMaterialsByInvoiceParams) ([]InvoiceMaterial, error)
	ListInvoiceMaterialsDataForReport(ctx context.Context, arg ListInvoiceMaterialsDataForReportParams) ([]ListInvoiceMaterialsDataForReportRow, error)
	ListInvoiceMaterialsWithSerialNumbers(ctx context.Context, arg ListInvoiceMaterialsWithSerialNumbersParams) ([]ListInvoiceMaterialsWithSerialNumbersRow, error)
	ListInvoiceMaterialsWithoutSerialNumbers(ctx context.Context, arg ListInvoiceMaterialsWithoutSerialNumbersParams) ([]ListInvoiceMaterialsWithoutSerialNumbersRow, error)
	ListInvoiceObjectOperationsBasedOnMaterialsInTeam(ctx context.Context, locationID pgtype.Int8) ([]ListInvoiceObjectOperationsBasedOnMaterialsInTeamRow, error)
	ListInvoiceObjectTeamsByObjectID(ctx context.Context, objectID pgtype.Int8) ([]ListInvoiceObjectTeamsByObjectIDRow, error)
	ListInvoiceObjectsForCorrection(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceObjectsForCorrectionRow, error)
	ListInvoiceObjectsPaginated(ctx context.Context, arg ListInvoiceObjectsPaginatedParams) ([]ListInvoiceObjectsPaginatedRow, error)
	ListInvoiceOutputAvailableMaterialsInWarehouse(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputAvailableMaterialsInWarehouseRow, error)
	ListInvoiceOutputMaterialDataForReport(ctx context.Context, invoiceID pgtype.Int8) ([]ListInvoiceOutputMaterialDataForReportRow, error)
	ListInvoiceOutputMaterialsForEdit(ctx context.Context, arg ListInvoiceOutputMaterialsForEditParams) ([]ListInvoiceOutputMaterialsForEditRow, error)
	ListInvoiceOutputOutOfProjectMaterialsForEdit(ctx context.Context, arg ListInvoiceOutputOutOfProjectMaterialsForEditParams) ([]ListInvoiceOutputOutOfProjectMaterialsForEditRow, error)
	ListInvoiceOutputOutOfProjectReportData(ctx context.Context, arg ListInvoiceOutputOutOfProjectReportDataParams) ([]ListInvoiceOutputOutOfProjectReportDataRow, error)
	ListInvoiceOutputOutOfProjectUniqueNameOfProjects(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListInvoiceOutputOutOfProjectsPaginated(ctx context.Context, arg ListInvoiceOutputOutOfProjectsPaginatedParams) ([]ListInvoiceOutputOutOfProjectsPaginatedRow, error)
	ListInvoiceOutputReportFilterData(ctx context.Context, arg ListInvoiceOutputReportFilterDataParams) ([]ListInvoiceOutputReportFilterDataRow, error)
	ListInvoiceOutputUniqueCodes(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueCodesRow, error)
	ListInvoiceOutputUniqueCreators(ctx context.Context, projectID pgtype.Int8) ([]int64, error)
	ListInvoiceOutputUniqueDistricts(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueDistrictsRow, error)
	ListInvoiceOutputUniqueRecieved(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueRecievedRow, error)
	ListInvoiceOutputUniqueTeams(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueTeamsRow, error)
	ListInvoiceOutputUniqueWarehouseManagers(ctx context.Context, projectID pgtype.Int8) ([]ListInvoiceOutputUniqueWarehouseManagersRow, error)
	ListInvoiceOutputs(ctx context.Context) ([]InvoiceOutput, error)
	ListInvoiceOutputsPaginated(ctx context.Context, arg ListInvoiceOutputsPaginatedParams) ([]InvoiceOutput, error)
	ListInvoiceOutputsPaginatedFiltered(ctx context.Context, arg ListInvoiceOutputsPaginatedFilteredParams) ([]ListInvoiceOutputsPaginatedFilteredRow, error)
	ListInvoiceReturnMaterialsForEdit(ctx context.Context, arg ListInvoiceReturnMaterialsForEditParams) ([]ListInvoiceReturnMaterialsForEditRow, error)
	ListInvoiceReturnReportData(ctx context.Context, arg ListInvoiceReturnReportDataParams) ([]InvoiceReturn, error)
	ListInvoiceReturnUniqueCodes(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListInvoiceReturnUniqueObjects(ctx context.Context, projectID pgtype.Int8) ([]int64, error)
	ListInvoiceReturnUniqueTeams(ctx context.Context, projectID pgtype.Int8) ([]int64, error)
	ListInvoiceReturns(ctx context.Context) ([]InvoiceReturn, error)
	ListInvoiceReturnsPaginatedObject(ctx context.Context, arg ListInvoiceReturnsPaginatedObjectParams) ([]ListInvoiceReturnsPaginatedObjectRow, error)
	ListInvoiceReturnsPaginatedTeam(ctx context.Context, arg ListInvoiceReturnsPaginatedTeamParams) ([]ListInvoiceReturnsPaginatedTeamRow, error)
	ListInvoiceWriteOffMaterialsForEdit(ctx context.Context, arg ListInvoiceWriteOffMaterialsForEditParams) ([]ListInvoiceWriteOffMaterialsForEditRow, error)
	ListInvoiceWriteOffReportData(ctx context.Context, arg ListInvoiceWriteOffReportDataParams) ([]ListInvoiceWriteOffReportDataRow, error)
	ListInvoiceWriteOffs(ctx context.Context) ([]InvoiceWriteOff, error)
	ListInvoiceWriteOffsPaginated(ctx context.Context, arg ListInvoiceWriteOffsPaginatedParams) ([]ListInvoiceWriteOffsPaginatedRow, error)
	ListKL04KVObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListKL04KVObjectNamesForSearchRow, error)
	ListKL04KVObjectsPaginated(ctx context.Context, arg ListKL04KVObjectsPaginatedParams) ([]ListKL04KVObjectsPaginatedRow, error)
	ListMJDObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListMJDObjectNamesForSearchRow, error)
	ListMJDObjectsPaginated(ctx context.Context, arg ListMJDObjectsPaginatedParams) ([]ListMJDObjectsPaginatedRow, error)
	// The Asc-by-cost variant used by invoice_return Create/Update (returner
	// gives back the lowest-cost material first).
	ListMaterialAmountReverseSortedByCostM19InLocation(ctx context.Context, arg ListMaterialAmountReverseSortedByCostM19InLocationParams) ([]ListMaterialAmountReverseSortedByCostM19InLocationRow, error)
	ListMaterialAmountSortedByCostM19InLocation(ctx context.Context, arg ListMaterialAmountSortedByCostM19InLocationParams) ([]ListMaterialAmountSortedByCostM19InLocationRow, error)
	ListMaterialCostIDAndSerialNumberIDByCodes(ctx context.Context, arg ListMaterialCostIDAndSerialNumberIDByCodesParams) ([]ListMaterialCostIDAndSerialNumberIDByCodesRow, error)
	ListMaterialCosts(ctx context.Context) ([]MaterialCost, error)
	ListMaterialCostsByMaterialID(ctx context.Context, materialID pgtype.Int8) ([]MaterialCost, error)
	ListMaterialCostsByMaterialIDSorted(ctx context.Context, materialID pgtype.Int8) ([]MaterialCost, error)
	ListMaterialCostsViewByProject(ctx context.Context, arg ListMaterialCostsViewByProjectParams) ([]ListMaterialCostsViewByProjectRow, error)
	ListMaterialCostsViewFiltered(ctx context.Context, arg ListMaterialCostsViewFilteredParams) ([]ListMaterialCostsViewFilteredRow, error)
	ListMaterialLocations(ctx context.Context) ([]MaterialLocation, error)
	// Used by invoice_writeoff Confirmation: gets all material_locations rows
	// for a given polymorphic location_type (e.g. 'writeoff-warehouse',
	// 'loss-team', etc — these are the writeoff sentinel location types).
	ListMaterialLocationsByLocationType(ctx context.Context, locationType pgtype.Text) ([]MaterialLocation, error)
	// The GORM-era materialLocationRepo.GetMaterialsInLocationBasedOnInvoiceID
	// query: rows in a (location_type, location_id) location whose material_cost_id
	// matches one of the invoice's invoice_materials rows.
	ListMaterialLocationsForInvoiceConfirmation(ctx context.Context, arg ListMaterialLocationsForInvoiceConfirmationParams) ([]MaterialLocation, error)
	ListMaterialLocationsLive(ctx context.Context, arg ListMaterialLocationsLiveParams) ([]ListMaterialLocationsLiveRow, error)
	ListMaterialLocationsPaginated(ctx context.Context, arg ListMaterialLocationsPaginatedParams) ([]MaterialLocation, error)
	// Fixed during phase 6 from the GORM-era SQL that targeted the wrong
	// table (`SELECT * FROM materials`). This query now correctly hits
	// material_locations.
	ListMaterialLocationsPaginatedFiltered(ctx context.Context, arg ListMaterialLocationsPaginatedFilteredParams) ([]MaterialLocation, error)
	ListMaterialsByProject(ctx context.Context, projectID pgtype.Int8) ([]Material, error)
	ListMaterialsByProjectPaginated(ctx context.Context, arg ListMaterialsByProjectPaginatedParams) ([]Material, error)
	ListMaterialsPaginatedFiltered(ctx context.Context, arg ListMaterialsPaginatedFilteredParams) ([]Material, error)
	ListObjectSupervisorsByObjectID(ctx context.Context, objectID pgtype.Int8) ([]ObjectSupervisor, error)
	ListObjectSupervisorsByWorkerID(ctx context.Context, supervisorWorkerID pgtype.Int8) ([]ObjectSupervisor, error)
	ListObjectsByIDs(ctx context.Context, ids []int64) ([]Object, error)
	ListObjectsByProject(ctx context.Context, projectID pgtype.Int8) ([]Object, error)
	ListObjectsByProjectAndType(ctx context.Context, arg ListObjectsByProjectAndTypeParams) ([]Object, error)
	ListObjectsPaginated(ctx context.Context, arg ListObjectsPaginatedParams) ([]Object, error)
	ListObjectsPaginatedFiltered(ctx context.Context, arg ListObjectsPaginatedFilteredParams) ([]ListObjectsPaginatedFilteredRow, error)
	ListOperationsByProject(ctx context.Context, projectID pgtype.Int8) ([]ListOperationsByProjectRow, error)
	ListOperationsPaginated(ctx context.Context, arg ListOperationsPaginatedParams) ([]ListOperationsPaginatedRow, error)
	ListOperationsWithoutMaterials(ctx context.Context, projectID pgtype.Int8) ([]Operation, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPermissionsByRoleID(ctx context.Context, roleID pgtype.Int8) ([]Permission, error)
	ListProjectNamesByUserID(ctx context.Context, userID pgtype.Int8) ([]string, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProjectsExcludeAdmin(ctx context.Context, arg ListProjectsExcludeAdminParams) ([]Project, error)
	ListResources(ctx context.Context) ([]Resource, error)
	// The `code` column was added in 00005_permissions_v2_foundation.sql. Selecting
	// it here keeps sqlc emitting db.Role uniformly; the legacy usecase ignores it.
	ListRoles(ctx context.Context) ([]Role, error)
	ListSIPObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListSIPObjectNamesForSearchRow, error)
	ListSIPObjectsPaginated(ctx context.Context, arg ListSIPObjectsPaginatedParams) ([]ListSIPObjectsPaginatedRow, error)
	ListSTVTObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListSTVTObjectNamesForSearchRow, error)
	ListSTVTObjectsPaginated(ctx context.Context, arg ListSTVTObjectsPaginatedParams) ([]ListSTVTObjectsPaginatedRow, error)
	ListSerialNumberCodesByMaterialID(ctx context.Context, arg ListSerialNumberCodesByMaterialIDParams) ([]string, error)
	ListSerialNumberLocations(ctx context.Context) ([]SerialNumberLocation, error)
	ListSerialNumberMovementsByInvoice(ctx context.Context, arg ListSerialNumberMovementsByInvoiceParams) ([]SerialNumberMovement, error)
	ListSerialNumbers(ctx context.Context) ([]SerialNumber, error)
	ListSerialNumbersByMaterialCostID(ctx context.Context, materialCostID pgtype.Int8) ([]SerialNumber, error)
	ListSubstationCellObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListSubstationCellObjectNamesForSearchRow, error)
	ListSubstationCellObjectsPaginated(ctx context.Context, arg ListSubstationCellObjectsPaginatedParams) ([]ListSubstationCellObjectsPaginatedRow, error)
	ListSubstationObjectNamesByProject(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListSubstationObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListSubstationObjectNamesForSearchRow, error)
	ListSubstationObjectsAll(ctx context.Context, projectID pgtype.Int8) ([]Object, error)
	ListSubstationObjectsPaginated(ctx context.Context, arg ListSubstationObjectsPaginatedParams) ([]ListSubstationObjectsPaginatedRow, error)
	ListSupervisorAndObjectNamesByObjectID(ctx context.Context, arg ListSupervisorAndObjectNamesByObjectIDParams) ([]ListSupervisorAndObjectNamesByObjectIDRow, error)
	ListSupervisorNamesByObjectID(ctx context.Context, id int64) ([]string, error)
	ListTPNourashesObjectNamesByTarget(ctx context.Context, arg ListTPNourashesObjectNamesByTargetParams) ([]string, error)
	ListTPObjectNamesByProject(ctx context.Context, projectID pgtype.Int8) ([]string, error)
	ListTPObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListTPObjectNamesForSearchRow, error)
	ListTPObjectsAll(ctx context.Context, projectID pgtype.Int8) ([]ListTPObjectsAllRow, error)
	ListTPObjectsPaginated(ctx context.Context, arg ListTPObjectsPaginatedParams) ([]ListTPObjectsPaginatedRow, error)
	ListTeamNumberAndLeadersByID(ctx context.Context, arg ListTeamNumberAndLeadersByIDParams) ([]ListTeamNumberAndLeadersByIDRow, error)
	ListTeamNumbersByObjectID(ctx context.Context, id int64) ([]string, error)
	ListTeamsByIDs(ctx context.Context, ids []int64) ([]Team, error)
	ListTeamsByProject(ctx context.Context, projectID pgtype.Int8) ([]Team, error)
	ListTeamsForSelect(ctx context.Context, projectID pgtype.Int8) ([]ListTeamsForSelectRow, error)
	ListTeamsForSelectByObjectID(ctx context.Context, objectID pgtype.Int8) ([]ListTeamsForSelectByObjectIDRow, error)
	ListTeamsPaginated(ctx context.Context, arg ListTeamsPaginatedParams) ([]ListTeamsPaginatedRow, error)
	ListUniqueMaterialCostsFromLocation(ctx context.Context, arg ListUniqueMaterialCostsFromLocationParams) ([]MaterialCost, error)
	// COALESCE on location_id: legacy warehouse rows can land with location_id IS NULL
	// while canonical writes use 0. Normalize so NULL is treated as 0 — matches the
	// semantics of ListBalanceReportData. Without this, materials sitting at
	// (warehouse, NULL) appear in balance reports but are unselectable in the picker.
	ListUniqueMaterialsFromLocation(ctx context.Context, arg ListUniqueMaterialsFromLocationParams) ([]Material, error)
	ListUniqueObjectsForSelectFromMaterialLocations(ctx context.Context, projectID pgtype.Int8) ([]ListUniqueObjectsForSelectFromMaterialLocationsRow, error)
	ListUniqueTeamsForSelectFromMaterialLocations(ctx context.Context, projectID pgtype.Int8) ([]ListUniqueTeamsForSelectFromMaterialLocationsRow, error)
	ListUserActionsByUserID(ctx context.Context, userID pgtype.Int8) ([]ListUserActionsByUserIDRow, error)
	// Optional filters: pass 0 for bigint, '' for text, or sentinel time bounds to disable.
	// DateFrom defaults to '0001-01-01' (no lower bound), DateTo defaults to '9999-12-31'
	// (no upper bound) — caller substitutes these when the filter is unset.
	ListUserActionsPaginated(ctx context.Context, arg ListUserActionsPaginatedParams) ([]ListUserActionsPaginatedRow, error)
	ListUserInProjectsByUserID(ctx context.Context, userID pgtype.Int8) ([]UserInProject, error)
	// Powers the audit-log page's user filter — admins type a name or a login
	// and pick from the dropdown. Returns a flat (id, username, workerName)
	// list, sorted by worker name then username for stable display.
	ListUserOptionsForAudit(ctx context.Context) ([]ListUserOptionsForAuditRow, error)
	ListUserPermissionsByRoleName(ctx context.Context, name pgtype.Text) ([]ListUserPermissionsByRoleNameRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]User, error)
	ListUsersPaginatedFiltered(ctx context.Context, arg ListUsersPaginatedFilteredParams) ([]User, error)
	ListWorkerAttendancesPaginated(ctx context.Context, projectID pgtype.Int8) ([]ListWorkerAttendancesPaginatedRow, error)
	ListWorkersByJobTitleInProject(ctx context.Context, arg ListWorkersByJobTitleInProjectParams) ([]Worker, error)
	ListWorkersByProject(ctx context.Context, projectID pgtype.Int8) ([]Worker, error)
	ListWorkersPaginatedFiltered(ctx context.Context, arg ListWorkersPaginatedFilteredParams) ([]Worker, error)
	MaterialDataForProgressReportInProject(ctx context.Context, projectID pgtype.Int8) ([]MaterialDataForProgressReportInProjectRow, error)
	MaterialDataForProgressReportInProjectInGivenDate(ctx context.Context, arg MaterialDataForProgressReportInProjectInGivenDateParams) ([]MaterialDataForProgressReportInProjectInGivenDateRow, error)
	MaterialDataForRemainingMaterialAnalysis(ctx context.Context, projectID pgtype.Int8) ([]MaterialDataForRemainingMaterialAnalysisRow, error)
	MaterialsInstalledOnObjectForRemainingMaterialAnalysis(ctx context.Context, projectID pgtype.Int8) ([]MaterialsInstalledOnObjectForRemainingMaterialAnalysisRow, error)
	TeamNumberExistsForCreate(ctx context.Context, arg TeamNumberExistsForCreateParams) (bool, error)
	TeamNumberExistsForUpdate(ctx context.Context, arg TeamNumberExistsForUpdateParams) (bool, error)
	UpdateDistrict(ctx context.Context, arg UpdateDistrictParams) (District, error)
	UpdateInvoiceInput(ctx context.Context, arg UpdateInvoiceInputParams) (InvoiceInput, error)
	UpdateInvoiceObjectConfirmation(ctx context.Context, arg UpdateInvoiceObjectConfirmationParams) error
	UpdateInvoiceOutput(ctx context.Context, arg UpdateInvoiceOutputParams) (InvoiceOutput, error)
	UpdateInvoiceOutputOutOfProject(ctx context.Context, arg UpdateInvoiceOutputOutOfProjectParams) (InvoiceOutputOutOfProject, error)
	UpdateInvoiceReturn(ctx context.Context, arg UpdateInvoiceReturnParams) (InvoiceReturn, error)
	UpdateInvoiceWriteOff(ctx context.Context, arg UpdateInvoiceWriteOffParams) (InvoiceWriteOff, error)
	UpdateInvoiceWriteOffConfirmation(ctx context.Context, arg UpdateInvoiceWriteOffConfirmationParams) error
	UpdateKL04KVObjectDetail(ctx context.Context, arg UpdateKL04KVObjectDetailParams) error
	UpdateMJDObjectDetail(ctx context.Context, arg UpdateMJDObjectDetailParams) error
	UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error)
	UpdateMaterialCost(ctx context.Context, arg UpdateMaterialCostParams) (MaterialCost, error)
	UpdateMaterialLocation(ctx context.Context, arg UpdateMaterialLocationParams) error
	UpdateObject(ctx context.Context, arg UpdateObjectParams) (Object, error)
	UpdateOperation(ctx context.Context, arg UpdateOperationParams) error
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSIPObjectDetail(ctx context.Context, arg UpdateSIPObjectDetailParams) error
	UpdateSTVTObjectDetail(ctx context.Context, arg UpdateSTVTObjectDetailParams) error
	UpdateSerialNumber(ctx context.Context, arg UpdateSerialNumberParams) (SerialNumber, error)
	UpdateSubstationObjectDetail(ctx context.Context, arg UpdateSubstationObjectDetailParams) error
	UpdateTPObjectDetail(ctx context.Context, arg UpdateTPObjectDetailParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error)
	// Migration 00002 added a unique index on (auction_item_id, user_id),
	// so the lookup-then-update-or-insert dance collapses into a single
	// atomic upsert that's safe under concurrent writes.
	UpsertAuctionParticipantPrice(ctx context.Context, arg UpsertAuctionParticipantPriceParams) error
	UpsertMaterialDefectByID(ctx context.Context, arg UpsertMaterialDefectByIDParams) error
	// Used by invoice_input.Confirmation: when an existing material_locations
	// row is found for (project_id, material_cost_id, location_type='warehouse'),
	// its amount is updated to the supplied total. The GORM-era code did this
	// via clause.OnConflict on id; here it's an explicit UPDATE since the id
	// is already known at this point.
	UpsertMaterialLocationByID(ctx context.Context, arg UpsertMaterialLocationByIDParams) error
}

var _ Querier = (*Queries)(nil)
