// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: serial_number_location.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateSerialNumberLocationsBatchParams struct {
	SerialNumberID pgtype.Int8 `json:"serial_number_id"`
	ProjectID      pgtype.Int8 `json:"project_id"`
	LocationID     pgtype.Int8 `json:"location_id"`
	LocationType   pgtype.Text `json:"location_type"`
}

const listSerialNumberLocations = `-- name: ListSerialNumberLocations :many
SELECT id, serial_number_id, project_id, location_id, location_type
FROM serial_number_locations
`

func (q *Queries) ListSerialNumberLocations(ctx context.Context) ([]SerialNumberLocation, error) {
	rows, err := q.db.Query(ctx, listSerialNumberLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SerialNumberLocation{}
	for rows.Next() {
		var i SerialNumberLocation
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumberID,
			&i.ProjectID,
			&i.LocationID,
			&i.LocationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
