// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: serial_number.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSerialNumber = `-- name: CreateSerialNumber :one
INSERT INTO serial_numbers (project_id, material_cost_id, code)
VALUES ($1, $2, $3)
RETURNING id, project_id, material_cost_id, code
`

type CreateSerialNumberParams struct {
	ProjectID      pgtype.Int8 `json:"project_id"`
	MaterialCostID pgtype.Int8 `json:"material_cost_id"`
	Code           pgtype.Text `json:"code"`
}

func (q *Queries) CreateSerialNumber(ctx context.Context, arg CreateSerialNumberParams) (SerialNumber, error) {
	row := q.db.QueryRow(ctx, createSerialNumber, arg.ProjectID, arg.MaterialCostID, arg.Code)
	var i SerialNumber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MaterialCostID,
		&i.Code,
	)
	return i, err
}

const deleteSerialNumber = `-- name: DeleteSerialNumber :exec
DELETE FROM serial_numbers WHERE id = $1
`

func (q *Queries) DeleteSerialNumber(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSerialNumber, id)
	return err
}

const getSerialNumberCodesByMaterialIDAndLocation = `-- name: GetSerialNumberCodesByMaterialIDAndLocation :many
SELECT COALESCE(serial_numbers.code, '')::text AS code
FROM material_locations
INNER JOIN serial_numbers ON serial_numbers.material_cost_id = material_locations.material_cost_id
INNER JOIN serial_number_locations ON serial_number_locations.serial_number_id = serial_numbers.id
INNER JOIN material_costs ON material_locations.material_cost_id = material_costs.id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE
    materials.project_id = $1
    AND materials.id = $2
    AND material_locations.location_type = serial_number_locations.location_type
    AND material_locations.location_type = $3
    AND material_locations.location_id = serial_number_locations.location_id
    AND material_locations.location_id = $4
`

type GetSerialNumberCodesByMaterialIDAndLocationParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	ID           int64       `json:"id"`
	LocationType pgtype.Text `json:"location_type"`
	LocationID   pgtype.Int8 `json:"location_id"`
}

func (q *Queries) GetSerialNumberCodesByMaterialIDAndLocation(ctx context.Context, arg GetSerialNumberCodesByMaterialIDAndLocationParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getSerialNumberCodesByMaterialIDAndLocation,
		arg.ProjectID,
		arg.ID,
		arg.LocationType,
		arg.LocationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSerialNumbers = `-- name: ListSerialNumbers :many
SELECT id, project_id, material_cost_id, code
FROM serial_numbers
`

func (q *Queries) ListSerialNumbers(ctx context.Context) ([]SerialNumber, error) {
	rows, err := q.db.Query(ctx, listSerialNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SerialNumber{}
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MaterialCostID,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSerialNumbersByMaterialCostID = `-- name: ListSerialNumbersByMaterialCostID :many
SELECT id, project_id, material_cost_id, code
FROM serial_numbers
WHERE material_cost_id = $1
`

func (q *Queries) ListSerialNumbersByMaterialCostID(ctx context.Context, materialCostID pgtype.Int8) ([]SerialNumber, error) {
	rows, err := q.db.Query(ctx, listSerialNumbersByMaterialCostID, materialCostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SerialNumber{}
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MaterialCostID,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSerialNumber = `-- name: UpdateSerialNumber :one
UPDATE serial_numbers
SET project_id = $2, material_cost_id = $3, code = $4
WHERE id = $1
RETURNING id, project_id, material_cost_id, code
`

type UpdateSerialNumberParams struct {
	ID             int64       `json:"id"`
	ProjectID      pgtype.Int8 `json:"project_id"`
	MaterialCostID pgtype.Int8 `json:"material_cost_id"`
	Code           pgtype.Text `json:"code"`
}

func (q *Queries) UpdateSerialNumber(ctx context.Context, arg UpdateSerialNumberParams) (SerialNumber, error) {
	row := q.db.QueryRow(ctx, updateSerialNumber,
		arg.ID,
		arg.ProjectID,
		arg.MaterialCostID,
		arg.Code,
	)
	var i SerialNumber
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MaterialCostID,
		&i.Code,
	)
	return i, err
}
