// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: serial_number_movement.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmSerialNumberMovementsByInvoice = `-- name: ConfirmSerialNumberMovementsByInvoice :exec
UPDATE serial_number_movements
SET confirmation = true
WHERE invoice_id = $1 AND invoice_type = $2
`

type ConfirmSerialNumberMovementsByInvoiceParams struct {
	InvoiceID   pgtype.Int8 `json:"invoice_id"`
	InvoiceType pgtype.Text `json:"invoice_type"`
}

func (q *Queries) ConfirmSerialNumberMovementsByInvoice(ctx context.Context, arg ConfirmSerialNumberMovementsByInvoiceParams) error {
	_, err := q.db.Exec(ctx, confirmSerialNumberMovementsByInvoice, arg.InvoiceID, arg.InvoiceType)
	return err
}

type CreateSerialNumberMovementsBatchParams struct {
	SerialNumberID pgtype.Int8 `json:"serial_number_id"`
	ProjectID      pgtype.Int8 `json:"project_id"`
	InvoiceID      pgtype.Int8 `json:"invoice_id"`
	InvoiceType    pgtype.Text `json:"invoice_type"`
	IsDefected     pgtype.Bool `json:"is_defected"`
	Confirmation   pgtype.Bool `json:"confirmation"`
}

const deleteSerialNumberMovementsByInvoice = `-- name: DeleteSerialNumberMovementsByInvoice :exec
DELETE FROM serial_number_movements
WHERE invoice_type = $1 AND invoice_id = $2
`

type DeleteSerialNumberMovementsByInvoiceParams struct {
	InvoiceType pgtype.Text `json:"invoice_type"`
	InvoiceID   pgtype.Int8 `json:"invoice_id"`
}

func (q *Queries) DeleteSerialNumberMovementsByInvoice(ctx context.Context, arg DeleteSerialNumberMovementsByInvoiceParams) error {
	_, err := q.db.Exec(ctx, deleteSerialNumberMovementsByInvoice, arg.InvoiceType, arg.InvoiceID)
	return err
}

const listSerialNumberMovementsByInvoice = `-- name: ListSerialNumberMovementsByInvoice :many
SELECT id, serial_number_id, project_id, invoice_id, invoice_type, is_defected, confirmation
FROM serial_number_movements
WHERE invoice_id = $1 AND invoice_type = $2
`

type ListSerialNumberMovementsByInvoiceParams struct {
	InvoiceID   pgtype.Int8 `json:"invoice_id"`
	InvoiceType pgtype.Text `json:"invoice_type"`
}

func (q *Queries) ListSerialNumberMovementsByInvoice(ctx context.Context, arg ListSerialNumberMovementsByInvoiceParams) ([]SerialNumberMovement, error) {
	rows, err := q.db.Query(ctx, listSerialNumberMovementsByInvoice, arg.InvoiceID, arg.InvoiceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SerialNumberMovement{}
	for rows.Next() {
		var i SerialNumberMovement
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumberID,
			&i.ProjectID,
			&i.InvoiceID,
			&i.InvoiceType,
			&i.IsDefected,
			&i.Confirmation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
