// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sip_object.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSIPObjectsFiltered = `-- name: CountSIPObjectsFiltered :one
SELECT COUNT(*)::bigint
FROM (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN s_ip_objects ON objects.object_detailed_id = s_ip_objects.id
    FULL JOIN object_teams ON object_teams.object_id = objects.id
    FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
    FULL JOIN tp_nourashes_objects ON tp_nourashes_objects.target_id = objects.id
    WHERE
        objects.type = 'sip_objects'
        AND objects.project_id = $1
        AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
        AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
        AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
) sub
`

type CountSIPObjectsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
}

func (q *Queries) CountSIPObjectsFiltered(ctx context.Context, arg CountSIPObjectsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSIPObjectsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSIPObjectDetail = `-- name: CreateSIPObjectDetail :one
INSERT INTO s_ip_objects (amount_feeders)
VALUES ($1)
RETURNING id, amount_feeders
`

func (q *Queries) CreateSIPObjectDetail(ctx context.Context, amountFeeders pgtype.Int8) (SIpObject, error) {
	row := q.db.QueryRow(ctx, createSIPObjectDetail, amountFeeders)
	var i SIpObject
	err := row.Scan(&i.ID, &i.AmountFeeders)
	return i, err
}

const deleteObjectBySIPDetailedID = `-- name: DeleteObjectBySIPDetailedID :exec
DELETE FROM objects
WHERE object_detailed_id = $1 AND type = 'sip_objects'
`

func (q *Queries) DeleteObjectBySIPDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteObjectBySIPDetailedID, objectDetailedID)
	return err
}

const deleteSIPObjectDetail = `-- name: DeleteSIPObjectDetail :exec
DELETE FROM s_ip_objects WHERE id = $1
`

func (q *Queries) DeleteSIPObjectDetail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSIPObjectDetail, id)
	return err
}

const deleteSIPObjectSupervisorsCascade = `-- name: DeleteSIPObjectSupervisorsCascade :exec
DELETE FROM object_supervisors
WHERE object_supervisors.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN s_ip_objects ON s_ip_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND s_ip_objects.id = $2
        AND objects.type = 'sip_objects'
)
`

type DeleteSIPObjectSupervisorsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteSIPObjectSupervisorsCascade(ctx context.Context, arg DeleteSIPObjectSupervisorsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteSIPObjectSupervisorsCascade, arg.ProjectID, arg.ID)
	return err
}

const deleteSIPObjectTeamsCascade = `-- name: DeleteSIPObjectTeamsCascade :exec
DELETE FROM object_teams
WHERE object_teams.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN s_ip_objects ON s_ip_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND s_ip_objects.id = $2
        AND objects.type = 'sip_objects'
)
`

type DeleteSIPObjectTeamsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteSIPObjectTeamsCascade(ctx context.Context, arg DeleteSIPObjectTeamsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteSIPObjectTeamsCascade, arg.ProjectID, arg.ID)
	return err
}

const getSIPObjectDetail = `-- name: GetSIPObjectDetail :one
SELECT id, amount_feeders
FROM s_ip_objects
WHERE id = $1
`

func (q *Queries) GetSIPObjectDetail(ctx context.Context, id int64) (SIpObject, error) {
	row := q.db.QueryRow(ctx, getSIPObjectDetail, id)
	var i SIpObject
	err := row.Scan(&i.ID, &i.AmountFeeders)
	return i, err
}

const listSIPObjectNamesForSearch = `-- name: ListSIPObjectNamesForSearch :many
SELECT
    COALESCE(objects.name, '')::text AS label,
    COALESCE(objects.name, '')::text AS value
FROM objects
INNER JOIN s_ip_objects ON s_ip_objects.id = objects.object_detailed_id
WHERE
    objects.project_id = $1
    AND objects.type = 'sip_objects'
`

type ListSIPObjectNamesForSearchRow struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

func (q *Queries) ListSIPObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListSIPObjectNamesForSearchRow, error) {
	rows, err := q.db.Query(ctx, listSIPObjectNamesForSearch, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSIPObjectNamesForSearchRow{}
	for rows.Next() {
		var i ListSIPObjectNamesForSearchRow
		if err := rows.Scan(&i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSIPObjectsPaginated = `-- name: ListSIPObjectsPaginated :many
SELECT DISTINCT
    objects.id                                       AS object_id,
    s_ip_objects.id                                  AS object_detailed_id,
    COALESCE(objects.name, '')::text                 AS name,
    COALESCE(objects.status, '')::text               AS status,
    COALESCE(s_ip_objects.amount_feeders, 0)::bigint AS amount_feeders
FROM objects
INNER JOIN s_ip_objects ON objects.object_detailed_id = s_ip_objects.id
FULL JOIN object_teams ON object_teams.object_id = objects.id
FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
FULL JOIN tp_nourashes_objects ON tp_nourashes_objects.target_id = objects.id
WHERE
    objects.type = 'sip_objects'
    AND objects.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
ORDER BY s_ip_objects.id DESC
LIMIT $5 OFFSET $6
`

type ListSIPObjectsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListSIPObjectsPaginatedRow struct {
	ObjectID         int64  `json:"object_id"`
	ObjectDetailedID int64  `json:"object_detailed_id"`
	Name             string `json:"name"`
	Status           string `json:"status"`
	AmountFeeders    int64  `json:"amount_feeders"`
}

func (q *Queries) ListSIPObjectsPaginated(ctx context.Context, arg ListSIPObjectsPaginatedParams) ([]ListSIPObjectsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listSIPObjectsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSIPObjectsPaginatedRow{}
	for rows.Next() {
		var i ListSIPObjectsPaginatedRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.ObjectDetailedID,
			&i.Name,
			&i.Status,
			&i.AmountFeeders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSIPObjectDetail = `-- name: UpdateSIPObjectDetail :exec
UPDATE s_ip_objects
SET amount_feeders = $2
WHERE id = $1
`

type UpdateSIPObjectDetailParams struct {
	ID            int64       `json:"id"`
	AmountFeeders pgtype.Int8 `json:"amount_feeders"`
}

func (q *Queries) UpdateSIPObjectDetail(ctx context.Context, arg UpdateSIPObjectDetailParams) error {
	_, err := q.db.Exec(ctx, updateSIPObjectDetail, arg.ID, arg.AmountFeeders)
	return err
}
