// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statistics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoiceInputCreatorInvoices = `-- name: CountInvoiceInputCreatorInvoices :one
SELECT COUNT(*)::bigint
FROM invoice_inputs
WHERE project_id = $1 AND released_worker_id = $2
`

type CountInvoiceInputCreatorInvoicesParams struct {
	ProjectID        pgtype.Int8 `json:"project_id"`
	ReleasedWorkerID pgtype.Int8 `json:"released_worker_id"`
}

func (q *Queries) CountInvoiceInputCreatorInvoices(ctx context.Context, arg CountInvoiceInputCreatorInvoicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceInputCreatorInvoices, arg.ProjectID, arg.ReleasedWorkerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoiceInputs = `-- name: CountInvoiceInputs :one
SELECT COUNT(*)::bigint FROM invoice_inputs WHERE project_id = $1
`

func (q *Queries) CountInvoiceInputs(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceInputs, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoiceOutputCreatorInvoices = `-- name: CountInvoiceOutputCreatorInvoices :one
SELECT COUNT(*)::bigint
FROM invoice_outputs
WHERE project_id = $1 AND released_worker_id = $2
`

type CountInvoiceOutputCreatorInvoicesParams struct {
	ProjectID        pgtype.Int8 `json:"project_id"`
	ReleasedWorkerID pgtype.Int8 `json:"released_worker_id"`
}

func (q *Queries) CountInvoiceOutputCreatorInvoices(ctx context.Context, arg CountInvoiceOutputCreatorInvoicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceOutputCreatorInvoices, arg.ProjectID, arg.ReleasedWorkerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoiceOutputs = `-- name: CountInvoiceOutputs :one
SELECT COUNT(*)::bigint FROM invoice_outputs WHERE project_id = $1
`

func (q *Queries) CountInvoiceOutputs(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceOutputs, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoiceReturns = `-- name: CountInvoiceReturns :one
SELECT COUNT(*)::bigint FROM invoice_returns WHERE project_id = $1
`

func (q *Queries) CountInvoiceReturns(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceReturns, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvoiceWriteOffs = `-- name: CountInvoiceWriteOffs :one
SELECT COUNT(*)::bigint FROM invoice_write_offs WHERE project_id = $1
`

func (q *Queries) CountInvoiceWriteOffs(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoiceWriteOffs, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMaterialInInvoices = `-- name: CountMaterialInInvoices :many
SELECT
    COALESCE(invoice_materials.amount, 0)::float8       AS amount,
    COALESCE(invoice_materials.invoice_type, '')::text  AS invoice_type
FROM invoice_materials
INNER JOIN material_costs ON invoice_materials.material_cost_id = material_costs.id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE materials.id = $1
`

type CountMaterialInInvoicesRow struct {
	Amount      float64 `json:"amount"`
	InvoiceType string  `json:"invoice_type"`
}

func (q *Queries) CountMaterialInInvoices(ctx context.Context, id int64) ([]CountMaterialInInvoicesRow, error) {
	rows, err := q.db.Query(ctx, countMaterialInInvoices, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMaterialInInvoicesRow{}
	for rows.Next() {
		var i CountMaterialInInvoicesRow
		if err := rows.Scan(&i.Amount, &i.InvoiceType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMaterialInLocations = `-- name: CountMaterialInLocations :many
SELECT
    COALESCE(material_locations.amount, 0)::float8        AS amount,
    COALESCE(material_locations.location_type, '')::text  AS location_type
FROM material_locations
INNER JOIN material_costs ON material_locations.material_cost_id = material_costs.id
INNER JOIN materials ON materials.id = material_costs.material_id
WHERE materials.id = $1
`

type CountMaterialInLocationsRow struct {
	Amount       float64 `json:"amount"`
	LocationType string  `json:"location_type"`
}

func (q *Queries) CountMaterialInLocations(ctx context.Context, id int64) ([]CountMaterialInLocationsRow, error) {
	rows, err := q.db.Query(ctx, countMaterialInLocations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMaterialInLocationsRow{}
	for rows.Next() {
		var i CountMaterialInLocationsRow
		if err := rows.Scan(&i.Amount, &i.LocationType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceInputUniqueCreators = `-- name: ListInvoiceInputUniqueCreators :many
SELECT DISTINCT(COALESCE(released_worker_id, 0)::bigint)
FROM invoice_inputs
WHERE project_id = $1
`

func (q *Queries) ListInvoiceInputUniqueCreators(ctx context.Context, projectID pgtype.Int8) ([]int64, error) {
	rows, err := q.db.Query(ctx, listInvoiceInputUniqueCreators, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var column_1 int64
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceOutputUniqueCreators = `-- name: ListInvoiceOutputUniqueCreators :many
SELECT DISTINCT(COALESCE(released_worker_id, 0)::bigint)
FROM invoice_outputs
WHERE project_id = $1
`

func (q *Queries) ListInvoiceOutputUniqueCreators(ctx context.Context, projectID pgtype.Int8) ([]int64, error) {
	rows, err := q.db.Query(ctx, listInvoiceOutputUniqueCreators, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var column_1 int64
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
