// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stvt_object.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSTVTObjectsFiltered = `-- name: CountSTVTObjectsFiltered :one
SELECT COUNT(*)::bigint
FROM (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN stvt_objects ON objects.object_detailed_id = stvt_objects.id
    FULL JOIN object_teams ON object_teams.object_id = objects.id
    FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
    FULL JOIN tp_nourashes_objects ON tp_nourashes_objects.target_id = objects.id
    WHERE
        objects.type = 'stvt_objects'
        AND objects.project_id = $1
        AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
        AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
        AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
) sub
`

type CountSTVTObjectsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
}

func (q *Queries) CountSTVTObjectsFiltered(ctx context.Context, arg CountSTVTObjectsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSTVTObjectsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSTVTObjectDetail = `-- name: CreateSTVTObjectDetail :one
INSERT INTO stvt_objects (voltage_class, tt_coefficient)
VALUES ($1, $2)
RETURNING id, voltage_class, tt_coefficient
`

type CreateSTVTObjectDetailParams struct {
	VoltageClass  pgtype.Text `json:"voltage_class"`
	TtCoefficient pgtype.Text `json:"tt_coefficient"`
}

func (q *Queries) CreateSTVTObjectDetail(ctx context.Context, arg CreateSTVTObjectDetailParams) (StvtObject, error) {
	row := q.db.QueryRow(ctx, createSTVTObjectDetail, arg.VoltageClass, arg.TtCoefficient)
	var i StvtObject
	err := row.Scan(&i.ID, &i.VoltageClass, &i.TtCoefficient)
	return i, err
}

const deleteObjectBySTVTDetailedID = `-- name: DeleteObjectBySTVTDetailedID :exec
DELETE FROM objects
WHERE object_detailed_id = $1 AND type = 'stvt_objects'
`

func (q *Queries) DeleteObjectBySTVTDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteObjectBySTVTDetailedID, objectDetailedID)
	return err
}

const deleteSTVTObjectDetail = `-- name: DeleteSTVTObjectDetail :exec
DELETE FROM stvt_objects WHERE id = $1
`

func (q *Queries) DeleteSTVTObjectDetail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSTVTObjectDetail, id)
	return err
}

const deleteSTVTObjectSupervisorsCascade = `-- name: DeleteSTVTObjectSupervisorsCascade :exec
DELETE FROM object_supervisors
WHERE object_supervisors.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN stvt_objects ON stvt_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND stvt_objects.id = $2
        AND objects.type = 'stvt_objects'
)
`

type DeleteSTVTObjectSupervisorsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteSTVTObjectSupervisorsCascade(ctx context.Context, arg DeleteSTVTObjectSupervisorsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteSTVTObjectSupervisorsCascade, arg.ProjectID, arg.ID)
	return err
}

const deleteSTVTObjectTeamsCascade = `-- name: DeleteSTVTObjectTeamsCascade :exec
DELETE FROM object_teams
WHERE object_teams.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN stvt_objects ON stvt_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND stvt_objects.id = $2
        AND objects.type = 'stvt_objects'
)
`

type DeleteSTVTObjectTeamsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteSTVTObjectTeamsCascade(ctx context.Context, arg DeleteSTVTObjectTeamsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteSTVTObjectTeamsCascade, arg.ProjectID, arg.ID)
	return err
}

const getSTVTObjectDetail = `-- name: GetSTVTObjectDetail :one
SELECT id, voltage_class, tt_coefficient
FROM stvt_objects
WHERE id = $1
`

func (q *Queries) GetSTVTObjectDetail(ctx context.Context, id int64) (StvtObject, error) {
	row := q.db.QueryRow(ctx, getSTVTObjectDetail, id)
	var i StvtObject
	err := row.Scan(&i.ID, &i.VoltageClass, &i.TtCoefficient)
	return i, err
}

const listSTVTObjectNamesForSearch = `-- name: ListSTVTObjectNamesForSearch :many
SELECT
    COALESCE(objects.name, '')::text AS label,
    COALESCE(objects.name, '')::text AS value
FROM objects
INNER JOIN stvt_objects ON stvt_objects.id = objects.object_detailed_id
WHERE
    objects.project_id = $1
    AND objects.type = 'stvt_objects'
`

type ListSTVTObjectNamesForSearchRow struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

func (q *Queries) ListSTVTObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListSTVTObjectNamesForSearchRow, error) {
	rows, err := q.db.Query(ctx, listSTVTObjectNamesForSearch, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSTVTObjectNamesForSearchRow{}
	for rows.Next() {
		var i ListSTVTObjectNamesForSearchRow
		if err := rows.Scan(&i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSTVTObjectsPaginated = `-- name: ListSTVTObjectsPaginated :many
SELECT DISTINCT
    objects.id                                    AS object_id,
    stvt_objects.id                               AS object_detailed_id,
    COALESCE(objects.name, '')::text              AS name,
    COALESCE(objects.status, '')::text            AS status,
    COALESCE(stvt_objects.voltage_class, '')::text  AS voltage_class,
    COALESCE(stvt_objects.tt_coefficient, '')::text AS tt_coefficient
FROM objects
INNER JOIN stvt_objects ON objects.object_detailed_id = stvt_objects.id
FULL JOIN object_teams ON object_teams.object_id = objects.id
FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
FULL JOIN tp_nourashes_objects ON tp_nourashes_objects.target_id = objects.id
WHERE
    objects.type = 'stvt_objects'
    AND objects.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
ORDER BY stvt_objects.id DESC
LIMIT $5 OFFSET $6
`

type ListSTVTObjectsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListSTVTObjectsPaginatedRow struct {
	ObjectID         int64  `json:"object_id"`
	ObjectDetailedID int64  `json:"object_detailed_id"`
	Name             string `json:"name"`
	Status           string `json:"status"`
	VoltageClass     string `json:"voltage_class"`
	TtCoefficient    string `json:"tt_coefficient"`
}

func (q *Queries) ListSTVTObjectsPaginated(ctx context.Context, arg ListSTVTObjectsPaginatedParams) ([]ListSTVTObjectsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listSTVTObjectsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSTVTObjectsPaginatedRow{}
	for rows.Next() {
		var i ListSTVTObjectsPaginatedRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.ObjectDetailedID,
			&i.Name,
			&i.Status,
			&i.VoltageClass,
			&i.TtCoefficient,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSTVTObjectDetail = `-- name: UpdateSTVTObjectDetail :exec
UPDATE stvt_objects
SET voltage_class = $2, tt_coefficient = $3
WHERE id = $1
`

type UpdateSTVTObjectDetailParams struct {
	ID            int64       `json:"id"`
	VoltageClass  pgtype.Text `json:"voltage_class"`
	TtCoefficient pgtype.Text `json:"tt_coefficient"`
}

func (q *Queries) UpdateSTVTObjectDetail(ctx context.Context, arg UpdateSTVTObjectDetailParams) error {
	_, err := q.db.Exec(ctx, updateSTVTObjectDetail, arg.ID, arg.VoltageClass, arg.TtCoefficient)
	return err
}
