// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: substation_cell_object.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubstationCellObjectsFiltered = `-- name: CountSubstationCellObjectsFiltered :one
SELECT COUNT(*)::bigint
FROM (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN substation_cell_objects ON objects.object_detailed_id = substation_cell_objects.id
    FULL JOIN object_teams ON object_teams.object_id = objects.id
    FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
    FULL JOIN substation_cell_nourashes_substation_objects
        ON substation_cell_nourashes_substation_objects.substation_cell_object_id = objects.id
    WHERE
        objects.type = 'substation_cell_objects'
        AND objects.project_id = $1
        AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
        AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
        AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
        AND (NULLIF($5::bigint, 0) IS NULL OR substation_cell_nourashes_substation_objects.substation_object_id = $5)
) sub
`

type CountSubstationCellObjectsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Column5   int64       `json:"column_5"`
}

func (q *Queries) CountSubstationCellObjectsFiltered(ctx context.Context, arg CountSubstationCellObjectsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubstationCellObjectsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSubstationCellNourash = `-- name: CreateSubstationCellNourash :exec
INSERT INTO substation_cell_nourashes_substation_objects (substation_object_id, substation_cell_object_id)
VALUES ($1, $2)
`

type CreateSubstationCellNourashParams struct {
	SubstationObjectID     pgtype.Int8 `json:"substation_object_id"`
	SubstationCellObjectID pgtype.Int8 `json:"substation_cell_object_id"`
}

func (q *Queries) CreateSubstationCellNourash(ctx context.Context, arg CreateSubstationCellNourashParams) error {
	_, err := q.db.Exec(ctx, createSubstationCellNourash, arg.SubstationObjectID, arg.SubstationCellObjectID)
	return err
}

const createSubstationCellObjectDetail = `-- name: CreateSubstationCellObjectDetail :one
INSERT INTO substation_cell_objects DEFAULT VALUES
RETURNING id
`

// substation_cell_objects has only an id column.
func (q *Queries) CreateSubstationCellObjectDetail(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, createSubstationCellObjectDetail)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteObjectBySubstationCellDetailedID = `-- name: DeleteObjectBySubstationCellDetailedID :exec
DELETE FROM objects
WHERE object_detailed_id = $1 AND type = 'substation_cell_objects'
`

func (q *Queries) DeleteObjectBySubstationCellDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteObjectBySubstationCellDetailedID, objectDetailedID)
	return err
}

const deleteSubstationCellNourashesByCellObjectID = `-- name: DeleteSubstationCellNourashesByCellObjectID :exec
DELETE FROM substation_cell_nourashes_substation_objects
WHERE substation_cell_object_id = $1
`

func (q *Queries) DeleteSubstationCellNourashesByCellObjectID(ctx context.Context, substationCellObjectID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteSubstationCellNourashesByCellObjectID, substationCellObjectID)
	return err
}

const deleteSubstationCellObjectDetail = `-- name: DeleteSubstationCellObjectDetail :exec
DELETE FROM substation_cell_objects WHERE id = $1
`

func (q *Queries) DeleteSubstationCellObjectDetail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSubstationCellObjectDetail, id)
	return err
}

const deleteSubstationCellObjectNourashesCascade = `-- name: DeleteSubstationCellObjectNourashesCascade :exec
DELETE FROM substation_cell_nourashes_substation_objects
WHERE substation_cell_nourashes_substation_objects.substation_cell_object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN substation_cell_objects ON substation_cell_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND substation_cell_objects.id = $2
        AND objects.type = 'substation_cell_objects'
)
`

type DeleteSubstationCellObjectNourashesCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteSubstationCellObjectNourashesCascade(ctx context.Context, arg DeleteSubstationCellObjectNourashesCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteSubstationCellObjectNourashesCascade, arg.ProjectID, arg.ID)
	return err
}

const deleteSubstationCellObjectSupervisorsCascade = `-- name: DeleteSubstationCellObjectSupervisorsCascade :exec
DELETE FROM object_supervisors
WHERE object_supervisors.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN substation_cell_objects ON substation_cell_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND substation_cell_objects.id = $2
        AND objects.type = 'substation_cell_objects'
)
`

type DeleteSubstationCellObjectSupervisorsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

// The GORM-era SQL had a copy-paste typo (`stvt_objects.id` instead of
// `substation_cell_objects.id`) that would have raised "missing
// FROM-clause entry" at execution time. Fixed during phase 6.
func (q *Queries) DeleteSubstationCellObjectSupervisorsCascade(ctx context.Context, arg DeleteSubstationCellObjectSupervisorsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteSubstationCellObjectSupervisorsCascade, arg.ProjectID, arg.ID)
	return err
}

const deleteSubstationCellObjectTeamsCascade = `-- name: DeleteSubstationCellObjectTeamsCascade :exec
DELETE FROM object_teams
WHERE object_teams.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN substation_cell_objects ON substation_cell_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND substation_cell_objects.id = $2
        AND objects.type = 'substation_cell_objects'
)
`

type DeleteSubstationCellObjectTeamsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteSubstationCellObjectTeamsCascade(ctx context.Context, arg DeleteSubstationCellObjectTeamsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteSubstationCellObjectTeamsCascade, arg.ProjectID, arg.ID)
	return err
}

const getSubstationNameByCellObjectID = `-- name: GetSubstationNameByCellObjectID :one
SELECT COALESCE(substation_objects.name, '')::text AS name
FROM substation_cell_nourashes_substation_objects
INNER JOIN objects AS substation_cell_objects
    ON substation_cell_objects.id = substation_cell_nourashes_substation_objects.substation_cell_object_id
INNER JOIN objects AS substation_objects
    ON substation_objects.id = substation_cell_nourashes_substation_objects.substation_object_id
WHERE
    substation_cell_nourashes_substation_objects.substation_cell_object_id = $1
LIMIT 1
`

func (q *Queries) GetSubstationNameByCellObjectID(ctx context.Context, substationCellObjectID pgtype.Int8) (string, error) {
	row := q.db.QueryRow(ctx, getSubstationNameByCellObjectID, substationCellObjectID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listSubstationCellObjectNamesForSearch = `-- name: ListSubstationCellObjectNamesForSearch :many
SELECT
    COALESCE(objects.name, '')::text AS label,
    COALESCE(objects.name, '')::text AS value
FROM objects
WHERE
    objects.project_id = $1
    AND objects.type = 'substation_cell_objects'
`

type ListSubstationCellObjectNamesForSearchRow struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

func (q *Queries) ListSubstationCellObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListSubstationCellObjectNamesForSearchRow, error) {
	rows, err := q.db.Query(ctx, listSubstationCellObjectNamesForSearch, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubstationCellObjectNamesForSearchRow{}
	for rows.Next() {
		var i ListSubstationCellObjectNamesForSearchRow
		if err := rows.Scan(&i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubstationCellObjectsPaginated = `-- name: ListSubstationCellObjectsPaginated :many
SELECT DISTINCT
    objects.id                          AS object_id,
    substation_cell_objects.id          AS object_detailed_id,
    COALESCE(objects.name, '')::text    AS name,
    COALESCE(objects.status, '')::text  AS status
FROM objects
INNER JOIN substation_cell_objects ON objects.object_detailed_id = substation_cell_objects.id
FULL JOIN object_teams ON object_teams.object_id = objects.id
FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
FULL JOIN substation_cell_nourashes_substation_objects
    ON substation_cell_nourashes_substation_objects.substation_cell_object_id = objects.id
WHERE
    objects.type = 'substation_cell_objects'
    AND objects.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
    AND (NULLIF($5::bigint, 0) IS NULL OR substation_cell_nourashes_substation_objects.substation_object_id = $5)
ORDER BY substation_cell_objects.id DESC
LIMIT $6 OFFSET $7
`

type ListSubstationCellObjectsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Column5   int64       `json:"column_5"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListSubstationCellObjectsPaginatedRow struct {
	ObjectID         int64  `json:"object_id"`
	ObjectDetailedID int64  `json:"object_detailed_id"`
	Name             string `json:"name"`
	Status           string `json:"status"`
}

func (q *Queries) ListSubstationCellObjectsPaginated(ctx context.Context, arg ListSubstationCellObjectsPaginatedParams) ([]ListSubstationCellObjectsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listSubstationCellObjectsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubstationCellObjectsPaginatedRow{}
	for rows.Next() {
		var i ListSubstationCellObjectsPaginatedRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.ObjectDetailedID,
			&i.Name,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
