// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: substation_object.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubstationObjectsFiltered = `-- name: CountSubstationObjectsFiltered :one
SELECT COUNT(*)::bigint
FROM (
    SELECT DISTINCT objects.id
    FROM objects
    FULL JOIN object_teams ON object_teams.object_id = objects.id
    FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
    WHERE
        objects.type = 'substation_objects'
        AND objects.project_id = $1
        AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
        AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
        AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
) sub
`

type CountSubstationObjectsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
}

func (q *Queries) CountSubstationObjectsFiltered(ctx context.Context, arg CountSubstationObjectsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubstationObjectsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSubstationObjectDetail = `-- name: CreateSubstationObjectDetail :one
INSERT INTO substation_objects (voltage_class, number_of_transformers)
VALUES ($1, $2)
RETURNING id, voltage_class, number_of_transformers
`

type CreateSubstationObjectDetailParams struct {
	VoltageClass         pgtype.Text `json:"voltage_class"`
	NumberOfTransformers pgtype.Int8 `json:"number_of_transformers"`
}

func (q *Queries) CreateSubstationObjectDetail(ctx context.Context, arg CreateSubstationObjectDetailParams) (SubstationObject, error) {
	row := q.db.QueryRow(ctx, createSubstationObjectDetail, arg.VoltageClass, arg.NumberOfTransformers)
	var i SubstationObject
	err := row.Scan(&i.ID, &i.VoltageClass, &i.NumberOfTransformers)
	return i, err
}

const deleteObjectBySubstationDetailedID = `-- name: DeleteObjectBySubstationDetailedID :exec
DELETE FROM objects
WHERE object_detailed_id = $1 AND type = 'substation_objects'
`

func (q *Queries) DeleteObjectBySubstationDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteObjectBySubstationDetailedID, objectDetailedID)
	return err
}

const deleteSubstationObjectDetail = `-- name: DeleteSubstationObjectDetail :exec
DELETE FROM substation_objects WHERE id = $1
`

func (q *Queries) DeleteSubstationObjectDetail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSubstationObjectDetail, id)
	return err
}

const deleteSubstationObjectSupervisorsCascade = `-- name: DeleteSubstationObjectSupervisorsCascade :exec
DELETE FROM object_supervisors
WHERE object_supervisors.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN substation_objects ON substation_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND substation_objects.id = $2
        AND objects.type = 'substation_objects'
)
`

type DeleteSubstationObjectSupervisorsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteSubstationObjectSupervisorsCascade(ctx context.Context, arg DeleteSubstationObjectSupervisorsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteSubstationObjectSupervisorsCascade, arg.ProjectID, arg.ID)
	return err
}

const deleteSubstationObjectTeamsCascade = `-- name: DeleteSubstationObjectTeamsCascade :exec
DELETE FROM object_teams
WHERE object_teams.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN substation_objects ON substation_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND substation_objects.id = $2
        AND objects.type = 'substation_objects'
)
`

type DeleteSubstationObjectTeamsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteSubstationObjectTeamsCascade(ctx context.Context, arg DeleteSubstationObjectTeamsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteSubstationObjectTeamsCascade, arg.ProjectID, arg.ID)
	return err
}

const getSubstationObjectByName = `-- name: GetSubstationObjectByName :one
SELECT id, object_detailed_id, type, name, status, project_id
FROM objects
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetSubstationObjectByName(ctx context.Context, name pgtype.Text) (Object, error) {
	row := q.db.QueryRow(ctx, getSubstationObjectByName, name)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.ObjectDetailedID,
		&i.Type,
		&i.Name,
		&i.Status,
		&i.ProjectID,
	)
	return i, err
}

const getSubstationObjectDetail = `-- name: GetSubstationObjectDetail :one
SELECT id, voltage_class, number_of_transformers
FROM substation_objects
WHERE id = $1
`

func (q *Queries) GetSubstationObjectDetail(ctx context.Context, id int64) (SubstationObject, error) {
	row := q.db.QueryRow(ctx, getSubstationObjectDetail, id)
	var i SubstationObject
	err := row.Scan(&i.ID, &i.VoltageClass, &i.NumberOfTransformers)
	return i, err
}

const listSubstationObjectNamesByProject = `-- name: ListSubstationObjectNamesByProject :many
SELECT COALESCE(objects.name, '')::text AS name
FROM objects
WHERE objects.type = 'substation_objects' AND objects.project_id = $1
`

func (q *Queries) ListSubstationObjectNamesByProject(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listSubstationObjectNamesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubstationObjectNamesForSearch = `-- name: ListSubstationObjectNamesForSearch :many
SELECT
    COALESCE(objects.name, '')::text AS label,
    COALESCE(objects.name, '')::text AS value
FROM objects
INNER JOIN substation_objects ON substation_objects.id = objects.object_detailed_id
WHERE
    objects.project_id = $1
    AND objects.type = 'substation_objects'
`

type ListSubstationObjectNamesForSearchRow struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

func (q *Queries) ListSubstationObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListSubstationObjectNamesForSearchRow, error) {
	rows, err := q.db.Query(ctx, listSubstationObjectNamesForSearch, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubstationObjectNamesForSearchRow{}
	for rows.Next() {
		var i ListSubstationObjectNamesForSearchRow
		if err := rows.Scan(&i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubstationObjectsAll = `-- name: ListSubstationObjectsAll :many
SELECT id, object_detailed_id, type, name, status, project_id
FROM objects
WHERE type = 'substation_objects' AND project_id = $1
`

func (q *Queries) ListSubstationObjectsAll(ctx context.Context, projectID pgtype.Int8) ([]Object, error) {
	rows, err := q.db.Query(ctx, listSubstationObjectsAll, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Object{}
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.ObjectDetailedID,
			&i.Type,
			&i.Name,
			&i.Status,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubstationObjectsPaginated = `-- name: ListSubstationObjectsPaginated :many
SELECT DISTINCT
    objects.id                                              AS object_id,
    substation_objects.id                                   AS object_detailed_id,
    COALESCE(objects.name, '')::text                        AS name,
    COALESCE(objects.status, '')::text                      AS status,
    COALESCE(substation_objects.voltage_class, '')::text    AS voltage_class,
    COALESCE(substation_objects.number_of_transformers, 0)::bigint AS number_of_transformers
FROM objects
INNER JOIN substation_objects ON objects.object_detailed_id = substation_objects.id
FULL JOIN object_teams ON object_teams.object_id = objects.id
FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
WHERE
    objects.type = 'substation_objects'
    AND objects.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
ORDER BY substation_objects.id DESC
LIMIT $5 OFFSET $6
`

type ListSubstationObjectsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListSubstationObjectsPaginatedRow struct {
	ObjectID             int64  `json:"object_id"`
	ObjectDetailedID     int64  `json:"object_detailed_id"`
	Name                 string `json:"name"`
	Status               string `json:"status"`
	VoltageClass         string `json:"voltage_class"`
	NumberOfTransformers int64  `json:"number_of_transformers"`
}

func (q *Queries) ListSubstationObjectsPaginated(ctx context.Context, arg ListSubstationObjectsPaginatedParams) ([]ListSubstationObjectsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listSubstationObjectsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubstationObjectsPaginatedRow{}
	for rows.Next() {
		var i ListSubstationObjectsPaginatedRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.ObjectDetailedID,
			&i.Name,
			&i.Status,
			&i.VoltageClass,
			&i.NumberOfTransformers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubstationObjectDetail = `-- name: UpdateSubstationObjectDetail :exec
UPDATE substation_objects
SET voltage_class = $2, number_of_transformers = $3
WHERE id = $1
`

type UpdateSubstationObjectDetailParams struct {
	ID                   int64       `json:"id"`
	VoltageClass         pgtype.Text `json:"voltage_class"`
	NumberOfTransformers pgtype.Int8 `json:"number_of_transformers"`
}

func (q *Queries) UpdateSubstationObjectDetail(ctx context.Context, arg UpdateSubstationObjectDetailParams) error {
	_, err := q.db.Exec(ctx, updateSubstationObjectDetail, arg.ID, arg.VoltageClass, arg.NumberOfTransformers)
	return err
}
