// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTeamsFiltered = `-- name: CountTeamsFiltered :one
SELECT COUNT(*)::bigint
FROM teams
INNER JOIN team_leaders ON team_leaders.team_id = teams.id
INNER JOIN workers ON team_leaders.leader_worker_id = workers.id
WHERE
    teams.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR teams.number = $2)
    AND (NULLIF($3::text, '') IS NULL OR teams.mobile_number = $3)
    AND (NULLIF($4::text, '') IS NULL OR teams.company = $4)
    AND (NULLIF($5::bigint, 0) IS NULL OR team_leaders.leader_worker_id = $5)
`

type CountTeamsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   string      `json:"column_3"`
	Column4   string      `json:"column_4"`
	Column5   int64       `json:"column_5"`
}

func (q *Queries) CountTeamsFiltered(ctx context.Context, arg CountTeamsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (project_id, number, mobile_number, company)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, number, mobile_number, company
`

type CreateTeamParams struct {
	ProjectID    pgtype.Int8 `json:"project_id"`
	Number       pgtype.Text `json:"number"`
	MobileNumber pgtype.Text `json:"mobile_number"`
	Company      pgtype.Text `json:"company"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ProjectID,
		arg.Number,
		arg.MobileNumber,
		arg.Company,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.MobileNumber,
		&i.Company,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, project_id, number, mobile_number, company
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.MobileNumber,
		&i.Company,
	)
	return i, err
}

const getTeamByNumber = `-- name: GetTeamByNumber :one
SELECT id, project_id, number, mobile_number, company
FROM teams
WHERE number = $1
LIMIT 1
`

func (q *Queries) GetTeamByNumber(ctx context.Context, number pgtype.Text) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByNumber, number)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.MobileNumber,
		&i.Company,
	)
	return i, err
}

const listDistinctTeamCompanies = `-- name: ListDistinctTeamCompanies :many
SELECT DISTINCT(COALESCE(company, '')::text) FROM teams WHERE project_id = $1
`

func (q *Queries) ListDistinctTeamCompanies(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctTeamCompanies, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctTeamMobileNumbers = `-- name: ListDistinctTeamMobileNumbers :many
SELECT DISTINCT(COALESCE(mobile_number, '')::text) FROM teams WHERE project_id = $1
`

func (q *Queries) ListDistinctTeamMobileNumbers(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctTeamMobileNumbers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctTeamNumbers = `-- name: ListDistinctTeamNumbers :many
SELECT DISTINCT(COALESCE(number, '')::text) FROM teams WHERE project_id = $1
`

func (q *Queries) ListDistinctTeamNumbers(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctTeamNumbers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamNumberAndLeadersByID = `-- name: ListTeamNumberAndLeadersByID :many
SELECT DISTINCT ON (teams.id)
    COALESCE(teams.number, '')::text   AS team_number,
    COALESCE(workers.name, '')::text   AS team_leader_name
FROM teams
INNER JOIN team_leaders ON team_leaders.team_id = teams.id
INNER JOIN workers ON workers.id = team_leaders.leader_worker_id
WHERE teams.project_id = $1 AND teams.id = $2
ORDER BY teams.id, team_leaders.id
`

type ListTeamNumberAndLeadersByIDParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

type ListTeamNumberAndLeadersByIDRow struct {
	TeamNumber     string `json:"team_number"`
	TeamLeaderName string `json:"team_leader_name"`
}

func (q *Queries) ListTeamNumberAndLeadersByID(ctx context.Context, arg ListTeamNumberAndLeadersByIDParams) ([]ListTeamNumberAndLeadersByIDRow, error) {
	rows, err := q.db.Query(ctx, listTeamNumberAndLeadersByID, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamNumberAndLeadersByIDRow{}
	for rows.Next() {
		var i ListTeamNumberAndLeadersByIDRow
		if err := rows.Scan(&i.TeamNumber, &i.TeamLeaderName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByIDs = `-- name: ListTeamsByIDs :many
SELECT id, project_id, number, mobile_number, company
FROM teams
WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListTeamsByIDs(ctx context.Context, ids []int64) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.MobileNumber,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByProject = `-- name: ListTeamsByProject :many
SELECT id, project_id, number, mobile_number, company
FROM teams
WHERE project_id = $1
ORDER BY id DESC
`

func (q *Queries) ListTeamsByProject(ctx context.Context, projectID pgtype.Int8) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.MobileNumber,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForSelect = `-- name: ListTeamsForSelect :many
SELECT DISTINCT ON (teams.id)
    teams.id                            AS id,
    COALESCE(teams.number, '')::text    AS team_number,
    COALESCE(workers.name, '')::text    AS team_leader_name
FROM teams
INNER JOIN team_leaders ON team_leaders.team_id = teams.id
INNER JOIN workers ON workers.id = team_leaders.leader_worker_id
WHERE teams.project_id = $1
ORDER BY teams.id, team_leaders.id
`

type ListTeamsForSelectRow struct {
	ID             int64  `json:"id"`
	TeamNumber     string `json:"team_number"`
	TeamLeaderName string `json:"team_leader_name"`
}

func (q *Queries) ListTeamsForSelect(ctx context.Context, projectID pgtype.Int8) ([]ListTeamsForSelectRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForSelect, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForSelectRow{}
	for rows.Next() {
		var i ListTeamsForSelectRow
		if err := rows.Scan(&i.ID, &i.TeamNumber, &i.TeamLeaderName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsPaginated = `-- name: ListTeamsPaginated :many
SELECT
    teams.id                                                      AS id,
    COALESCE(teams.number, '')::text                              AS team_number,
    COALESCE(workers.id, 0)::bigint                               AS leader_id,
    COALESCE(workers.name, '')::text                              AS leader_name,
    COALESCE(teams.mobile_number, '')::text                       AS team_mobile_number,
    COALESCE(teams.company, '')::text                             AS team_company
FROM teams
INNER JOIN team_leaders ON team_leaders.team_id = teams.id
INNER JOIN workers ON team_leaders.leader_worker_id = workers.id
WHERE
    teams.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR teams.number = $2)
    AND (NULLIF($3::text, '') IS NULL OR teams.mobile_number = $3)
    AND (NULLIF($4::text, '') IS NULL OR teams.company = $4)
    AND (NULLIF($5::bigint, 0) IS NULL OR team_leaders.leader_worker_id = $5)
ORDER BY teams.id DESC
LIMIT $6 OFFSET $7
`

type ListTeamsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   string      `json:"column_3"`
	Column4   string      `json:"column_4"`
	Column5   int64       `json:"column_5"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListTeamsPaginatedRow struct {
	ID               int64  `json:"id"`
	TeamNumber       string `json:"team_number"`
	LeaderID         int64  `json:"leader_id"`
	LeaderName       string `json:"leader_name"`
	TeamMobileNumber string `json:"team_mobile_number"`
	TeamCompany      string `json:"team_company"`
}

func (q *Queries) ListTeamsPaginated(ctx context.Context, arg ListTeamsPaginatedParams) ([]ListTeamsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listTeamsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsPaginatedRow{}
	for rows.Next() {
		var i ListTeamsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamNumber,
			&i.LeaderID,
			&i.LeaderName,
			&i.TeamMobileNumber,
			&i.TeamCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamNumberExistsForCreate = `-- name: TeamNumberExistsForCreate :one
SELECT EXISTS(
    SELECT 1 FROM teams WHERE teams.number = $1 AND teams.project_id = $2
)::boolean
`

type TeamNumberExistsForCreateParams struct {
	Number    pgtype.Text `json:"number"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) TeamNumberExistsForCreate(ctx context.Context, arg TeamNumberExistsForCreateParams) (bool, error) {
	row := q.db.QueryRow(ctx, teamNumberExistsForCreate, arg.Number, arg.ProjectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const teamNumberExistsForUpdate = `-- name: TeamNumberExistsForUpdate :one
SELECT EXISTS(
    SELECT 1 FROM teams WHERE teams.number = $1 AND teams.id <> $2 AND teams.project_id = $3
)::boolean
`

type TeamNumberExistsForUpdateParams struct {
	Number    pgtype.Text `json:"number"`
	ID        int64       `json:"id"`
	ProjectID pgtype.Int8 `json:"project_id"`
}

func (q *Queries) TeamNumberExistsForUpdate(ctx context.Context, arg TeamNumberExistsForUpdateParams) (bool, error) {
	row := q.db.QueryRow(ctx, teamNumberExistsForUpdate, arg.Number, arg.ID, arg.ProjectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE teams
SET number = $2, mobile_number = $3, company = $4
WHERE id = $1
`

type UpdateTeamParams struct {
	ID           int64       `json:"id"`
	Number       pgtype.Text `json:"number"`
	MobileNumber pgtype.Text `json:"mobile_number"`
	Company      pgtype.Text `json:"company"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.Exec(ctx, updateTeam,
		arg.ID,
		arg.Number,
		arg.MobileNumber,
		arg.Company,
	)
	return err
}
