// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_leader.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamLeader = `-- name: CreateTeamLeader :exec
INSERT INTO team_leaders (team_id, leader_worker_id) VALUES ($1, $2)
`

type CreateTeamLeaderParams struct {
	TeamID         pgtype.Int8 `json:"team_id"`
	LeaderWorkerID pgtype.Int8 `json:"leader_worker_id"`
}

func (q *Queries) CreateTeamLeader(ctx context.Context, arg CreateTeamLeaderParams) error {
	_, err := q.db.Exec(ctx, createTeamLeader, arg.TeamID, arg.LeaderWorkerID)
	return err
}

type CreateTeamLeadersBatchParams struct {
	TeamID         pgtype.Int8 `json:"team_id"`
	LeaderWorkerID pgtype.Int8 `json:"leader_worker_id"`
}

const deleteTeamLeadersByTeamID = `-- name: DeleteTeamLeadersByTeamID :exec
DELETE FROM team_leaders WHERE team_id = $1
`

func (q *Queries) DeleteTeamLeadersByTeamID(ctx context.Context, teamID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteTeamLeadersByTeamID, teamID)
	return err
}
