// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tp_nourashes_object.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateTPNourashesObjectsBatchParams struct {
	TpObjectID pgtype.Int8 `json:"tp_object_id"`
	TargetID   pgtype.Int8 `json:"target_id"`
	TargetType pgtype.Text `json:"target_type"`
}

const deleteTPNourashesObjectsByTarget = `-- name: DeleteTPNourashesObjectsByTarget :exec
DELETE FROM tp_nourashes_objects
WHERE target_id = $1 AND target_type = $2
`

type DeleteTPNourashesObjectsByTargetParams struct {
	TargetID   pgtype.Int8 `json:"target_id"`
	TargetType pgtype.Text `json:"target_type"`
}

func (q *Queries) DeleteTPNourashesObjectsByTarget(ctx context.Context, arg DeleteTPNourashesObjectsByTargetParams) error {
	_, err := q.db.Exec(ctx, deleteTPNourashesObjectsByTarget, arg.TargetID, arg.TargetType)
	return err
}

const listTPNourashesObjectNamesByTarget = `-- name: ListTPNourashesObjectNamesByTarget :many
SELECT COALESCE(objects.name, '')::text AS name
FROM tp_nourashes_objects
INNER JOIN objects ON objects.id = tp_nourashes_objects.tp_object_id
WHERE
    tp_nourashes_objects.target_id = $1
    AND tp_nourashes_objects.target_type = $2
`

type ListTPNourashesObjectNamesByTargetParams struct {
	TargetID   pgtype.Int8 `json:"target_id"`
	TargetType pgtype.Text `json:"target_type"`
}

func (q *Queries) ListTPNourashesObjectNamesByTarget(ctx context.Context, arg ListTPNourashesObjectNamesByTargetParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTPNourashesObjectNamesByTarget, arg.TargetID, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
