// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tp_object.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTPObjectsFiltered = `-- name: CountTPObjectsFiltered :one
SELECT COUNT(*)::bigint
FROM (
    SELECT DISTINCT objects.id
    FROM objects
    FULL JOIN object_teams ON object_teams.object_id = objects.id
    FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
    FULL JOIN tp_nourashes_objects ON tp_nourashes_objects.target_id = objects.id
    WHERE
        objects.type = 'tp_objects'
        AND objects.project_id = $1
        AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
        AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
        AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
) sub
`

type CountTPObjectsFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
}

func (q *Queries) CountTPObjectsFiltered(ctx context.Context, arg CountTPObjectsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTPObjectsFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTPObjectDetail = `-- name: CreateTPObjectDetail :one
INSERT INTO tp_objects (model, voltage_class)
VALUES ($1, $2)
RETURNING id, model, voltage_class
`

type CreateTPObjectDetailParams struct {
	Model        pgtype.Text `json:"model"`
	VoltageClass pgtype.Text `json:"voltage_class"`
}

func (q *Queries) CreateTPObjectDetail(ctx context.Context, arg CreateTPObjectDetailParams) (TpObject, error) {
	row := q.db.QueryRow(ctx, createTPObjectDetail, arg.Model, arg.VoltageClass)
	var i TpObject
	err := row.Scan(&i.ID, &i.Model, &i.VoltageClass)
	return i, err
}

const deleteObjectByTPObjectDetailedID = `-- name: DeleteObjectByTPObjectDetailedID :exec
DELETE FROM objects
WHERE object_detailed_id = $1 AND type = 'tp_objects'
`

func (q *Queries) DeleteObjectByTPObjectDetailedID(ctx context.Context, objectDetailedID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteObjectByTPObjectDetailedID, objectDetailedID)
	return err
}

const deleteTPObjectDetail = `-- name: DeleteTPObjectDetail :exec
DELETE FROM tp_objects WHERE id = $1
`

func (q *Queries) DeleteTPObjectDetail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTPObjectDetail, id)
	return err
}

const deleteTPObjectSupervisorsCascade = `-- name: DeleteTPObjectSupervisorsCascade :exec
DELETE FROM object_supervisors
WHERE object_supervisors.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN tp_objects ON tp_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND tp_objects.id = $2
        AND objects.type = 'tp_objects'
)
`

type DeleteTPObjectSupervisorsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteTPObjectSupervisorsCascade(ctx context.Context, arg DeleteTPObjectSupervisorsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteTPObjectSupervisorsCascade, arg.ProjectID, arg.ID)
	return err
}

const deleteTPObjectTeamsCascade = `-- name: DeleteTPObjectTeamsCascade :exec
DELETE FROM object_teams
WHERE object_teams.object_id = (
    SELECT DISTINCT objects.id
    FROM objects
    INNER JOIN tp_objects ON tp_objects.id = objects.object_detailed_id
    WHERE
        objects.project_id = $1
        AND tp_objects.id = $2
        AND objects.type = 'tp_objects'
)
`

type DeleteTPObjectTeamsCascadeParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	ID        int64       `json:"id"`
}

func (q *Queries) DeleteTPObjectTeamsCascade(ctx context.Context, arg DeleteTPObjectTeamsCascadeParams) error {
	_, err := q.db.Exec(ctx, deleteTPObjectTeamsCascade, arg.ProjectID, arg.ID)
	return err
}

const getTPObjectDetail = `-- name: GetTPObjectDetail :one
SELECT id, model, voltage_class
FROM tp_objects
WHERE id = $1
`

func (q *Queries) GetTPObjectDetail(ctx context.Context, id int64) (TpObject, error) {
	row := q.db.QueryRow(ctx, getTPObjectDetail, id)
	var i TpObject
	err := row.Scan(&i.ID, &i.Model, &i.VoltageClass)
	return i, err
}

const listTPObjectNamesByProject = `-- name: ListTPObjectNamesByProject :many
SELECT COALESCE(objects.name, '')::text AS name
FROM objects
WHERE objects.project_id = $1 AND objects.type = 'tp_objects'
`

func (q *Queries) ListTPObjectNamesByProject(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listTPObjectNamesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTPObjectNamesForSearch = `-- name: ListTPObjectNamesForSearch :many
SELECT
    COALESCE(objects.name, '')::text AS label,
    COALESCE(objects.name, '')::text AS value
FROM objects
INNER JOIN tp_objects ON tp_objects.id = objects.object_detailed_id
WHERE
    objects.project_id = $1
    AND objects.type = 'tp_objects'
`

type ListTPObjectNamesForSearchRow struct {
	Label string `json:"label"`
	Value string `json:"value"`
}

func (q *Queries) ListTPObjectNamesForSearch(ctx context.Context, projectID pgtype.Int8) ([]ListTPObjectNamesForSearchRow, error) {
	rows, err := q.db.Query(ctx, listTPObjectNamesForSearch, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTPObjectNamesForSearchRow{}
	for rows.Next() {
		var i ListTPObjectNamesForSearchRow
		if err := rows.Scan(&i.Label, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTPObjectsAll = `-- name: ListTPObjectsAll :many
SELECT
    objects.id                                   AS object_id,
    objects.object_detailed_id                   AS object_detailed_id,
    COALESCE(objects.name, '')::text             AS name,
    COALESCE(objects.status, '')::text           AS status,
    COALESCE(tp_objects.model, '')::text         AS model,
    COALESCE(tp_objects.voltage_class, '')::text AS voltage_class
FROM objects
INNER JOIN tp_objects ON objects.object_detailed_id = tp_objects.id
WHERE
    objects.type = 'tp_objects'
    AND objects.project_id = $1
ORDER BY tp_objects.id DESC
`

type ListTPObjectsAllRow struct {
	ObjectID         int64       `json:"object_id"`
	ObjectDetailedID pgtype.Int8 `json:"object_detailed_id"`
	Name             string      `json:"name"`
	Status           string      `json:"status"`
	Model            string      `json:"model"`
	VoltageClass     string      `json:"voltage_class"`
}

func (q *Queries) ListTPObjectsAll(ctx context.Context, projectID pgtype.Int8) ([]ListTPObjectsAllRow, error) {
	rows, err := q.db.Query(ctx, listTPObjectsAll, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTPObjectsAllRow{}
	for rows.Next() {
		var i ListTPObjectsAllRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.ObjectDetailedID,
			&i.Name,
			&i.Status,
			&i.Model,
			&i.VoltageClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTPObjectsPaginated = `-- name: ListTPObjectsPaginated :many
SELECT DISTINCT
    objects.id                                   AS object_id,
    tp_objects.id                                AS object_detailed_id,
    COALESCE(objects.name, '')::text             AS name,
    COALESCE(objects.status, '')::text           AS status,
    COALESCE(tp_objects.model, '')::text         AS model,
    COALESCE(tp_objects.voltage_class, '')::text AS voltage_class
FROM objects
INNER JOIN tp_objects ON objects.object_detailed_id = tp_objects.id
FULL JOIN object_teams ON object_teams.object_id = objects.id
FULL JOIN object_supervisors ON object_supervisors.object_id = objects.id
FULL JOIN tp_nourashes_objects ON tp_nourashes_objects.target_id = objects.id
WHERE
    objects.type = 'tp_objects'
    AND objects.project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR objects.name = $2)
    AND (NULLIF($3::bigint, 0) IS NULL OR object_teams.team_id = $3)
    AND (NULLIF($4::bigint, 0) IS NULL OR object_supervisors.supervisor_worker_id = $4)
ORDER BY tp_objects.id DESC
LIMIT $5 OFFSET $6
`

type ListTPObjectsPaginatedParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   int64       `json:"column_3"`
	Column4   int64       `json:"column_4"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListTPObjectsPaginatedRow struct {
	ObjectID         int64  `json:"object_id"`
	ObjectDetailedID int64  `json:"object_detailed_id"`
	Name             string `json:"name"`
	Status           string `json:"status"`
	Model            string `json:"model"`
	VoltageClass     string `json:"voltage_class"`
}

func (q *Queries) ListTPObjectsPaginated(ctx context.Context, arg ListTPObjectsPaginatedParams) ([]ListTPObjectsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listTPObjectsPaginated,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTPObjectsPaginatedRow{}
	for rows.Next() {
		var i ListTPObjectsPaginatedRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.ObjectDetailedID,
			&i.Name,
			&i.Status,
			&i.Model,
			&i.VoltageClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTPObjectDetail = `-- name: UpdateTPObjectDetail :exec
UPDATE tp_objects
SET model = $2, voltage_class = $3
WHERE id = $1
`

type UpdateTPObjectDetailParams struct {
	ID           int64       `json:"id"`
	Model        pgtype.Text `json:"model"`
	VoltageClass pgtype.Text `json:"voltage_class"`
}

func (q *Queries) UpdateTPObjectDetail(ctx context.Context, arg UpdateTPObjectDetailParams) error {
	_, err := q.db.Exec(ctx, updateTPObjectDetail, arg.ID, arg.Model, arg.VoltageClass)
	return err
}
