// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (worker_id, username, password, role_id)
VALUES ($1, $2, $3, $4)
RETURNING id, worker_id, username, password, role_id
`

type CreateUserParams struct {
	WorkerID pgtype.Int8 `json:"worker_id"`
	Username pgtype.Text `json:"username"`
	Password pgtype.Text `json:"password"`
	RoleID   pgtype.Int8 `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.WorkerID,
		arg.Username,
		arg.Password,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Username,
		&i.Password,
		&i.RoleID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, worker_id, username, password, role_id
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Username,
		&i.Password,
		&i.RoleID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, worker_id, username, password, role_id
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Username,
		&i.Password,
		&i.RoleID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, worker_id, username, password, role_id
FROM users
ORDER BY id DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Username,
			&i.Password,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPaginated = `-- name: ListUsersPaginated :many
SELECT id, worker_id, username, password, role_id
FROM users
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListUsersPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Username,
			&i.Password,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPaginatedFiltered = `-- name: ListUsersPaginatedFiltered :many
SELECT id, worker_id, username, password, role_id
FROM users
WHERE
    (NULLIF($1::bigint, 0) IS NULL OR worker_id = $1)
    AND (NULLIF($2::text, '') IS NULL OR username = $2)
ORDER BY id DESC
LIMIT $3 OFFSET $4
`

type ListUsersPaginatedFilteredParams struct {
	Column1 int64  `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListUsersPaginatedFiltered(ctx context.Context, arg ListUsersPaginatedFilteredParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersPaginatedFiltered,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Username,
			&i.Password,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET worker_id = $2,
    username = $3,
    password = COALESCE(NULLIF($4::text, ''), password),
    role_id = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID       int64       `json:"id"`
	WorkerID pgtype.Int8 `json:"worker_id"`
	Username pgtype.Text `json:"username"`
	Column4  string      `json:"column_4"`
	RoleID   pgtype.Int8 `json:"role_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.WorkerID,
		arg.Username,
		arg.Column4,
		arg.RoleID,
	)
	return err
}
