// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_action.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserActionsPaginated = `-- name: CountUserActionsPaginated :one
SELECT COUNT(*)::bigint
FROM user_actions
WHERE
    (NULLIF($1::bigint, 0) IS NULL OR user_actions.user_id = $1)
    AND (NULLIF($2::bigint, 0) IS NULL OR user_actions.project_id = $2)
    AND (NULLIF($3::text, '') IS NULL OR user_actions.action_type = $3)
    AND (NULLIF($4::text, '') IS NULL OR user_actions.http_method = $4)
    AND ($5::boolean IS FALSE OR user_actions.action_status = $6)
    AND user_actions.date_of_action >= $7
    AND user_actions.date_of_action <= $8
`

type CountUserActionsPaginatedParams struct {
	Column1        int64              `json:"column_1"`
	Column2        int64              `json:"column_2"`
	Column3        string             `json:"column_3"`
	Column4        string             `json:"column_4"`
	Column5        bool               `json:"column_5"`
	ActionStatus   pgtype.Bool        `json:"action_status"`
	DateOfAction   pgtype.Timestamptz `json:"date_of_action"`
	DateOfAction_2 pgtype.Timestamptz `json:"date_of_action_2"`
}

func (q *Queries) CountUserActionsPaginated(ctx context.Context, arg CountUserActionsPaginatedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActionsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.ActionStatus,
		arg.DateOfAction,
		arg.DateOfAction_2,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUserAction = `-- name: CreateUserAction :one
INSERT INTO user_actions (action_url, action_type, action_id, action_status,
                          action_status_message, http_method, request_ip,
                          user_id, project_id, date_of_action)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, action_url, action_type, action_id, action_status,
          action_status_message, http_method, request_ip,
          user_id, project_id, date_of_action
`

type CreateUserActionParams struct {
	ActionUrl           pgtype.Text        `json:"action_url"`
	ActionType          pgtype.Text        `json:"action_type"`
	ActionID            pgtype.Int8        `json:"action_id"`
	ActionStatus        pgtype.Bool        `json:"action_status"`
	ActionStatusMessage pgtype.Text        `json:"action_status_message"`
	HttpMethod          pgtype.Text        `json:"http_method"`
	RequestIp           pgtype.Text        `json:"request_ip"`
	UserID              pgtype.Int8        `json:"user_id"`
	ProjectID           pgtype.Int8        `json:"project_id"`
	DateOfAction        pgtype.Timestamptz `json:"date_of_action"`
}

type CreateUserActionRow struct {
	ID                  int64              `json:"id"`
	ActionUrl           pgtype.Text        `json:"action_url"`
	ActionType          pgtype.Text        `json:"action_type"`
	ActionID            pgtype.Int8        `json:"action_id"`
	ActionStatus        pgtype.Bool        `json:"action_status"`
	ActionStatusMessage pgtype.Text        `json:"action_status_message"`
	HttpMethod          pgtype.Text        `json:"http_method"`
	RequestIp           pgtype.Text        `json:"request_ip"`
	UserID              pgtype.Int8        `json:"user_id"`
	ProjectID           pgtype.Int8        `json:"project_id"`
	DateOfAction        pgtype.Timestamptz `json:"date_of_action"`
}

func (q *Queries) CreateUserAction(ctx context.Context, arg CreateUserActionParams) (CreateUserActionRow, error) {
	row := q.db.QueryRow(ctx, createUserAction,
		arg.ActionUrl,
		arg.ActionType,
		arg.ActionID,
		arg.ActionStatus,
		arg.ActionStatusMessage,
		arg.HttpMethod,
		arg.RequestIp,
		arg.UserID,
		arg.ProjectID,
		arg.DateOfAction,
	)
	var i CreateUserActionRow
	err := row.Scan(
		&i.ID,
		&i.ActionUrl,
		&i.ActionType,
		&i.ActionID,
		&i.ActionStatus,
		&i.ActionStatusMessage,
		&i.HttpMethod,
		&i.RequestIp,
		&i.UserID,
		&i.ProjectID,
		&i.DateOfAction,
	)
	return i, err
}

const listUserActionsByUserID = `-- name: ListUserActionsByUserID :many
SELECT id, action_url, action_type, action_id, action_status,
       action_status_message, http_method, request_ip,
       user_id, project_id, date_of_action
FROM user_actions
WHERE user_id = $1
ORDER BY id DESC
`

type ListUserActionsByUserIDRow struct {
	ID                  int64              `json:"id"`
	ActionUrl           pgtype.Text        `json:"action_url"`
	ActionType          pgtype.Text        `json:"action_type"`
	ActionID            pgtype.Int8        `json:"action_id"`
	ActionStatus        pgtype.Bool        `json:"action_status"`
	ActionStatusMessage pgtype.Text        `json:"action_status_message"`
	HttpMethod          pgtype.Text        `json:"http_method"`
	RequestIp           pgtype.Text        `json:"request_ip"`
	UserID              pgtype.Int8        `json:"user_id"`
	ProjectID           pgtype.Int8        `json:"project_id"`
	DateOfAction        pgtype.Timestamptz `json:"date_of_action"`
}

func (q *Queries) ListUserActionsByUserID(ctx context.Context, userID pgtype.Int8) ([]ListUserActionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listUserActionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserActionsByUserIDRow{}
	for rows.Next() {
		var i ListUserActionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionUrl,
			&i.ActionType,
			&i.ActionID,
			&i.ActionStatus,
			&i.ActionStatusMessage,
			&i.HttpMethod,
			&i.RequestIp,
			&i.UserID,
			&i.ProjectID,
			&i.DateOfAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActionsPaginated = `-- name: ListUserActionsPaginated :many
SELECT
    user_actions.id                                     AS id,
    COALESCE(user_actions.action_url, '')::text         AS action_url,
    COALESCE(user_actions.action_type, '')::text        AS action_type,
    COALESCE(user_actions.action_id, 0)::bigint         AS action_id,
    COALESCE(user_actions.action_status, false)::boolean AS action_status,
    COALESCE(user_actions.action_status_message, '')::text AS action_status_message,
    COALESCE(user_actions.http_method, '')::text        AS http_method,
    COALESCE(user_actions.request_ip, '')::text         AS request_ip,
    COALESCE(user_actions.user_id, 0)::bigint           AS user_id,
    COALESCE(user_actions.project_id, 0)::bigint        AS project_id,
    COALESCE(users.username, '')::text                  AS username,
    user_actions.date_of_action                         AS date_of_action
FROM user_actions
LEFT JOIN users ON users.id = user_actions.user_id
WHERE
    (NULLIF($1::bigint, 0) IS NULL OR user_actions.user_id = $1)
    AND (NULLIF($2::bigint, 0) IS NULL OR user_actions.project_id = $2)
    AND (NULLIF($3::text, '') IS NULL OR user_actions.action_type = $3)
    AND (NULLIF($4::text, '') IS NULL OR user_actions.http_method = $4)
    AND ($5::boolean IS FALSE OR user_actions.action_status = $6)
    AND user_actions.date_of_action >= $7
    AND user_actions.date_of_action <= $8
ORDER BY user_actions.date_of_action DESC, user_actions.id DESC
LIMIT $9 OFFSET $10
`

type ListUserActionsPaginatedParams struct {
	Column1        int64              `json:"column_1"`
	Column2        int64              `json:"column_2"`
	Column3        string             `json:"column_3"`
	Column4        string             `json:"column_4"`
	Column5        bool               `json:"column_5"`
	ActionStatus   pgtype.Bool        `json:"action_status"`
	DateOfAction   pgtype.Timestamptz `json:"date_of_action"`
	DateOfAction_2 pgtype.Timestamptz `json:"date_of_action_2"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
}

type ListUserActionsPaginatedRow struct {
	ID                  int64              `json:"id"`
	ActionUrl           string             `json:"action_url"`
	ActionType          string             `json:"action_type"`
	ActionID            int64              `json:"action_id"`
	ActionStatus        bool               `json:"action_status"`
	ActionStatusMessage string             `json:"action_status_message"`
	HttpMethod          string             `json:"http_method"`
	RequestIp           string             `json:"request_ip"`
	UserID              int64              `json:"user_id"`
	ProjectID           int64              `json:"project_id"`
	Username            string             `json:"username"`
	DateOfAction        pgtype.Timestamptz `json:"date_of_action"`
}

// Optional filters: pass 0 for bigint, ” for text, or sentinel time bounds to disable.
// DateFrom defaults to '0001-01-01' (no lower bound), DateTo defaults to '9999-12-31'
// (no upper bound) — caller substitutes these when the filter is unset.
func (q *Queries) ListUserActionsPaginated(ctx context.Context, arg ListUserActionsPaginatedParams) ([]ListUserActionsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listUserActionsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.ActionStatus,
		arg.DateOfAction,
		arg.DateOfAction_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserActionsPaginatedRow{}
	for rows.Next() {
		var i ListUserActionsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionUrl,
			&i.ActionType,
			&i.ActionID,
			&i.ActionStatus,
			&i.ActionStatusMessage,
			&i.HttpMethod,
			&i.RequestIp,
			&i.UserID,
			&i.ProjectID,
			&i.Username,
			&i.DateOfAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOptionsForAudit = `-- name: ListUserOptionsForAudit :many
SELECT
    users.id                                  AS id,
    COALESCE(users.username, '')::text        AS username,
    COALESCE(workers.name, '')::text          AS worker_name
FROM users
LEFT JOIN workers ON workers.id = users.worker_id
ORDER BY worker_name, username
`

type ListUserOptionsForAuditRow struct {
	ID         int64  `json:"id"`
	Username   string `json:"username"`
	WorkerName string `json:"worker_name"`
}

// Powers the audit-log page's user filter — admins type a name or a login
// and pick from the dropdown. Returns a flat (id, username, workerName)
// list, sorted by worker name then username for stable display.
func (q *Queries) ListUserOptionsForAudit(ctx context.Context) ([]ListUserOptionsForAuditRow, error) {
	rows, err := q.db.Query(ctx, listUserOptionsForAudit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOptionsForAuditRow{}
	for rows.Next() {
		var i ListUserOptionsForAuditRow
		if err := rows.Scan(&i.ID, &i.Username, &i.WorkerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
