// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker_attendance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkerAttendances = `-- name: CountWorkerAttendances :one
SELECT COUNT(*)::bigint FROM worker_attendances WHERE project_id = $1
`

func (q *Queries) CountWorkerAttendances(ctx context.Context, projectID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkerAttendances, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

type CreateWorkerAttendancesBatchParams struct {
	ProjectID pgtype.Int8        `json:"project_id"`
	WorkerID  pgtype.Int8        `json:"worker_id"`
	Start     pgtype.Timestamptz `json:"start"`
	End       pgtype.Timestamptz `json:"end"`
}

const listWorkerAttendancesPaginated = `-- name: ListWorkerAttendancesPaginated :many
SELECT
    worker_attendances.id                                          AS id,
    COALESCE(workers.name, '')::text                               AS worker_name,
    COALESCE(workers.company_worker_id, '')::text                  AS company_worker_id,
    worker_attendances.start                                       AS start,
    worker_attendances."end"                                       AS "end"
FROM worker_attendances
INNER JOIN workers ON workers.id = worker_attendances.worker_id
WHERE worker_attendances.project_id = $1
`

type ListWorkerAttendancesPaginatedRow struct {
	ID              int64              `json:"id"`
	WorkerName      string             `json:"worker_name"`
	CompanyWorkerID string             `json:"company_worker_id"`
	Start           pgtype.Timestamptz `json:"start"`
	End             pgtype.Timestamptz `json:"end"`
}

func (q *Queries) ListWorkerAttendancesPaginated(ctx context.Context, projectID pgtype.Int8) ([]ListWorkerAttendancesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listWorkerAttendancesPaginated, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkerAttendancesPaginatedRow{}
	for rows.Next() {
		var i ListWorkerAttendancesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerName,
			&i.CompanyWorkerID,
			&i.Start,
			&i.End,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
