// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkersFiltered = `-- name: CountWorkersFiltered :one
SELECT COUNT(*)::bigint
FROM workers
WHERE
    project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR name = $2)
    AND (NULLIF($3::text, '') IS NULL OR mobile_number = $3)
    AND (NULLIF($4::text, '') IS NULL OR job_title_in_company = $4)
    AND (NULLIF($5::text, '') IS NULL OR job_title_in_project = $5)
`

type CountWorkersFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   string      `json:"column_3"`
	Column4   string      `json:"column_4"`
	Column5   string      `json:"column_5"`
}

func (q *Queries) CountWorkersFiltered(ctx context.Context, arg CountWorkersFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkersFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (project_id, name, company_worker_id, job_title_in_company,
                     job_title_in_project, mobile_number)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, company_worker_id, job_title_in_company,
          job_title_in_project, mobile_number
`

type CreateWorkerParams struct {
	ProjectID         pgtype.Int8 `json:"project_id"`
	Name              pgtype.Text `json:"name"`
	CompanyWorkerID   pgtype.Text `json:"company_worker_id"`
	JobTitleInCompany pgtype.Text `json:"job_title_in_company"`
	JobTitleInProject pgtype.Text `json:"job_title_in_project"`
	MobileNumber      pgtype.Text `json:"mobile_number"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.ProjectID,
		arg.Name,
		arg.CompanyWorkerID,
		arg.JobTitleInCompany,
		arg.JobTitleInProject,
		arg.MobileNumber,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CompanyWorkerID,
		&i.JobTitleInCompany,
		&i.JobTitleInProject,
		&i.MobileNumber,
	)
	return i, err
}

type CreateWorkersBatchParams struct {
	ProjectID         pgtype.Int8 `json:"project_id"`
	Name              pgtype.Text `json:"name"`
	CompanyWorkerID   pgtype.Text `json:"company_worker_id"`
	JobTitleInCompany pgtype.Text `json:"job_title_in_company"`
	JobTitleInProject pgtype.Text `json:"job_title_in_project"`
	MobileNumber      pgtype.Text `json:"mobile_number"`
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM workers WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWorker, id)
	return err
}

const getWorker = `-- name: GetWorker :one
SELECT id, project_id, name, company_worker_id, job_title_in_company,
       job_title_in_project, mobile_number
FROM workers
WHERE id = $1
`

func (q *Queries) GetWorker(ctx context.Context, id int64) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CompanyWorkerID,
		&i.JobTitleInCompany,
		&i.JobTitleInProject,
		&i.MobileNumber,
	)
	return i, err
}

const getWorkerByCompanyID = `-- name: GetWorkerByCompanyID :one
SELECT id, project_id, name, company_worker_id, job_title_in_company,
       job_title_in_project, mobile_number
FROM workers
WHERE company_worker_id = $1
LIMIT 1
`

func (q *Queries) GetWorkerByCompanyID(ctx context.Context, companyWorkerID pgtype.Text) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByCompanyID, companyWorkerID)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CompanyWorkerID,
		&i.JobTitleInCompany,
		&i.JobTitleInProject,
		&i.MobileNumber,
	)
	return i, err
}

const getWorkerByName = `-- name: GetWorkerByName :one
SELECT id, project_id, name, company_worker_id, job_title_in_company,
       job_title_in_project, mobile_number
FROM workers
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetWorkerByName(ctx context.Context, name pgtype.Text) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByName, name)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CompanyWorkerID,
		&i.JobTitleInCompany,
		&i.JobTitleInProject,
		&i.MobileNumber,
	)
	return i, err
}

const listDistinctWorkerCompanyIDs = `-- name: ListDistinctWorkerCompanyIDs :many
SELECT DISTINCT(COALESCE(company_worker_id, '')::text)
FROM workers
WHERE project_id = $1 AND COALESCE(company_worker_id, '') <> ''
`

func (q *Queries) ListDistinctWorkerCompanyIDs(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctWorkerCompanyIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctWorkerJobTitlesInCompany = `-- name: ListDistinctWorkerJobTitlesInCompany :many
SELECT DISTINCT(COALESCE(job_title_in_company, '')::text)
FROM workers
WHERE project_id = $1 AND COALESCE(job_title_in_company, '') <> ''
`

func (q *Queries) ListDistinctWorkerJobTitlesInCompany(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctWorkerJobTitlesInCompany, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctWorkerJobTitlesInProject = `-- name: ListDistinctWorkerJobTitlesInProject :many
SELECT DISTINCT(COALESCE(job_title_in_project, '')::text)
FROM workers
WHERE project_id = $1 AND COALESCE(job_title_in_project, '') <> ''
`

func (q *Queries) ListDistinctWorkerJobTitlesInProject(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctWorkerJobTitlesInProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctWorkerMobileNumbers = `-- name: ListDistinctWorkerMobileNumbers :many
SELECT DISTINCT(COALESCE(mobile_number, '')::text)
FROM workers
WHERE project_id = $1 AND COALESCE(mobile_number, '') <> ''
`

func (q *Queries) ListDistinctWorkerMobileNumbers(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctWorkerMobileNumbers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctWorkerNames = `-- name: ListDistinctWorkerNames :many
SELECT DISTINCT(COALESCE(name, '')::text)
FROM workers
WHERE project_id = $1 AND COALESCE(name, '') <> ''
`

func (q *Queries) ListDistinctWorkerNames(ctx context.Context, projectID pgtype.Int8) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctWorkerNames, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersByJobTitleInProject = `-- name: ListWorkersByJobTitleInProject :many
SELECT id, project_id, name, company_worker_id, job_title_in_company,
       job_title_in_project, mobile_number
FROM workers
WHERE job_title_in_project = $1 AND project_id = $2
ORDER BY id DESC
`

type ListWorkersByJobTitleInProjectParams struct {
	JobTitleInProject pgtype.Text `json:"job_title_in_project"`
	ProjectID         pgtype.Int8 `json:"project_id"`
}

func (q *Queries) ListWorkersByJobTitleInProject(ctx context.Context, arg ListWorkersByJobTitleInProjectParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersByJobTitleInProject, arg.JobTitleInProject, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CompanyWorkerID,
			&i.JobTitleInCompany,
			&i.JobTitleInProject,
			&i.MobileNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersByProject = `-- name: ListWorkersByProject :many
SELECT id, project_id, name, company_worker_id, job_title_in_company,
       job_title_in_project, mobile_number
FROM workers
WHERE id <> 1 AND project_id = $1
ORDER BY id DESC
`

func (q *Queries) ListWorkersByProject(ctx context.Context, projectID pgtype.Int8) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CompanyWorkerID,
			&i.JobTitleInCompany,
			&i.JobTitleInProject,
			&i.MobileNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersPaginatedFiltered = `-- name: ListWorkersPaginatedFiltered :many
SELECT id, project_id, name, company_worker_id, job_title_in_company,
       job_title_in_project, mobile_number
FROM workers
WHERE
    project_id = $1
    AND (NULLIF($2::text, '') IS NULL OR name = $2)
    AND (NULLIF($3::text, '') IS NULL OR mobile_number = $3)
    AND (NULLIF($4::text, '') IS NULL OR job_title_in_company = $4)
    AND (NULLIF($5::text, '') IS NULL OR job_title_in_project = $5)
    AND (NULLIF($6::text, '') IS NULL OR company_worker_id = $6)
ORDER BY id DESC
LIMIT $7 OFFSET $8
`

type ListWorkersPaginatedFilteredParams struct {
	ProjectID pgtype.Int8 `json:"project_id"`
	Column2   string      `json:"column_2"`
	Column3   string      `json:"column_3"`
	Column4   string      `json:"column_4"`
	Column5   string      `json:"column_5"`
	Column6   string      `json:"column_6"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListWorkersPaginatedFiltered(ctx context.Context, arg ListWorkersPaginatedFilteredParams) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersPaginatedFiltered,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CompanyWorkerID,
			&i.JobTitleInCompany,
			&i.JobTitleInProject,
			&i.MobileNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorker = `-- name: UpdateWorker :one
UPDATE workers
SET project_id = $2, name = $3, company_worker_id = $4,
    job_title_in_company = $5, job_title_in_project = $6, mobile_number = $7
WHERE id = $1
RETURNING id, project_id, name, company_worker_id, job_title_in_company,
          job_title_in_project, mobile_number
`

type UpdateWorkerParams struct {
	ID                int64       `json:"id"`
	ProjectID         pgtype.Int8 `json:"project_id"`
	Name              pgtype.Text `json:"name"`
	CompanyWorkerID   pgtype.Text `json:"company_worker_id"`
	JobTitleInCompany pgtype.Text `json:"job_title_in_company"`
	JobTitleInProject pgtype.Text `json:"job_title_in_project"`
	MobileNumber      pgtype.Text `json:"mobile_number"`
}

func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorker,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.CompanyWorkerID,
		arg.JobTitleInCompany,
		arg.JobTitleInProject,
		arg.MobileNumber,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CompanyWorkerID,
		&i.JobTitleInCompany,
		&i.JobTitleInProject,
		&i.MobileNumber,
	)
	return i, err
}
